/*****************************************************************************
 *                                CEA - LIST                                 *
 *  Reproduction and Communication of this document is strictly prohibited   *
 *        unless specifically authorized in writing by CEA - LIST.           *
 * ------------------------------------------------------------------------- *
 *                            LIST / DCSIN / LFIM                            *
 * ------------------------------------------------------------------------- *
 * @file    csram_base.h                                                     *
 * @date    January 2021                                                     *
 * @author  Roman Gauchi <roman.gauchi@cea.fr>                               *
 * @version 2.0                                                              *
 ****************************************************************************/

#ifndef __CSRAM_BASE_H__
#define __CSRAM_BASE_H__

#include "csram_opcodes.h"

#include "csram_isa.h"

#include <stdint.h>

#ifndef CSRAM_VECTOR_SIZE    // line size (128 columns / 8 = 16 bytes)
#define CSRAM_VECTOR_SIZE    16
#endif

/*****************************************************************************
 *                    Bit Manipulation Macros Functions                      *
 ****************************************************************************/

#define _SET_ISA_ADDRESS(value, PATTERN) \
    (((uint64_t)((((uint32_t)(value))/CSRAM_VECTOR_SIZE) & CSRAM_ISA_ ## PATTERN ## _MASK) << CSRAM_ISA_ ## PATTERN ##_START))

#define _SET_ISA_IMMEDIAT(value, PATTERN) \
    (((uint64_t)(((uint32_t)(value)) & CSRAM_ISA_ ## PATTERN ## _MASK) << CSRAM_ISA_ ## PATTERN ## _START))

#define _SET_ISA_VALUE(value, PATTERN) \
    _SET_ISA_IMMEDIAT(value, PATTERN)

// R-Type
#define _MAKE_CSRAM_ISA_RTYPE(_op, _dest, _src1, _src2) (uint64_t) ( \
    _SET_ISA_VALUE(CSRAM_ISA_NMC_ENABLE_VALUE, NMC_ENABLE) | \
    _SET_ISA_VALUE(CSRAM_OPC_##_op, OPCODE) | \
    _SET_ISA_ADDRESS(_dest, RTYPE_DEST) | \
    _SET_ISA_ADDRESS(_src1, RTYPE_SRC1) | \
    _SET_ISA_ADDRESS(_src2, RTYPE_SRC2) )

// I-Type
#define _MAKE_CSRAM_ISA_ITYPE(_op, _dest, _src1, _imm) (uint64_t) ( \
    _SET_ISA_VALUE(CSRAM_ISA_NMC_ENABLE_VALUE, NMC_ENABLE) | \
    _SET_ISA_VALUE(CSRAM_OPC_##_op, OPCODE) | \
    _SET_ISA_ADDRESS(_dest, ITYPE_DEST) | \
    _SET_ISA_ADDRESS(_src1, ITYPE_SRC1) | \
    _SET_ISA_IMMEDIAT(_imm, ITYPE_IMM) )

// U-Type
#define _MAKE_CSRAM_ISA_UTYPE(_op, _dest, _imm) (uint64_t) ( \
    _SET_ISA_VALUE(CSRAM_ISA_NMC_ENABLE_VALUE, NMC_ENABLE) | \
    _SET_ISA_VALUE(CSRAM_OPC_##_op, OPCODE) | \
    _SET_ISA_ADDRESS( _dest, UTYPE_DEST) | \
    _SET_ISA_IMMEDIAT(_imm, UTYPE_IMM) )


/*****************************************************************************
 *                         CSRAM Type Macro Functions                        *
 ****************************************************************************/

#define _csram_rtype(_mnemonic, _dest, _src1, _src2) do { \
    uint64_t _storeword = _MAKE_CSRAM_ISA_RTYPE(_mnemonic, _dest, _src1, _src2); \
    volatile uintptr_t* _storeaddress = (uintptr_t*)((uint32_t)(_storeword >> 32)); \
    uint32_t _storedata = (uint32_t)(_storeword); \
    *_storeaddress = _storedata; \
    asm("" ::: "memory"); \
} while(0)

#define _csram_itype(_mnemonic, _dest, _src1, _imm) do { \
    uint64_t _storeword = _MAKE_CSRAM_ISA_ITYPE(_mnemonic, _dest, _src1, _imm); \
    volatile uintptr_t* _storeaddress = (uintptr_t*)((uint32_t)(_storeword >> 32)); \
    uint32_t _storedata = (uint32_t)(_storeword); \
    *_storeaddress = _storedata; \
    asm("" ::: "memory"); \
} while(0)

#define _csram_utype(_mnemonic, _dest, _imm) do { \
    uint64_t _storeword = _MAKE_CSRAM_ISA_UTYPE(_mnemonic, _dest, _imm); \
    volatile uintptr_t* _storeaddress = (uintptr_t*)((uint32_t)(_storeword >> 32)); \
    uint32_t _storedata = (uint32_t)(_storeword); \
    *_storeaddress = _storedata; \
    asm("" ::: "memory"); \
} while(0)


/*****************************************************************************
 *             WARNING: This part is auto-generated by PyISAGen              *
 ****************************************************************************/
#define _cm_copyeq8(dst, a, b)                  _csram_rtype(COPYEQ8, &dst, &a, &b)
#define _cm_copygeq8(dst, a, b)                 _csram_rtype(COPYGEQ8, &dst, &a, &b)
#define _cm_copygt8(dst, a, b)                  _csram_rtype(COPYGT8, &dst, &a, &b)
#define _cm_copyleq8(dst, a, b)                 _csram_rtype(COPYLEQ8, &dst, &a, &b)
#define _cm_copylt8(dst, a, b)                  _csram_rtype(COPYLT8, &dst, &a, &b)
#define _cm_copyneq8(dst, a, b)                 _csram_rtype(COPYNEQ8, &dst, &a, &b)
#define _cm_bcast8(dst, imm32)                  _csram_utype(BCAST8, &dst, imm32)
#define _cm_slli8(dst, a, imm16)                _csram_itype(SLLI8, &dst, &a, imm16)
#define _cm_srli8(dst, a, imm16)                _csram_itype(SRLI8, &dst, &a, imm16)
#define _cm_adds8(dst, a, b)                    _csram_rtype(ADDS8, &dst, &a, &b)
#define _cm_add8(dst, a, b)                     _csram_rtype(ADD8, &dst, &a, &b)
#define _cm_sub8(dst, a, b)                     _csram_rtype(SUB8, &dst, &a, &b)
#define _cm_subs8(dst, a, b)                    _csram_rtype(SUBS8, &dst, &a, &b)
#define _cm_cmp8(dst, a, b)                     _csram_rtype(CMP8, &dst, &a, &b)
#define _cm_mul8(dst, a, b)                     _csram_rtype(MUL8, &dst, &a, &b)
#define _cm_fmac8(dst, a, b)                    _csram_rtype(FMAC8, &dst, &a, &b)
#define _cm_copyeq16(dst, a, b)                 _csram_rtype(COPYEQ16, &dst, &a, &b)
#define _cm_copygeq16(dst, a, b)                _csram_rtype(COPYGEQ16, &dst, &a, &b)
#define _cm_copygt16(dst, a, b)                 _csram_rtype(COPYGT16, &dst, &a, &b)
#define _cm_copyleq16(dst, a, b)                _csram_rtype(COPYLEQ16, &dst, &a, &b)
#define _cm_copylt16(dst, a, b)                 _csram_rtype(COPYLT16, &dst, &a, &b)
#define _cm_copyneq16(dst, a, b)                _csram_rtype(COPYNEQ16, &dst, &a, &b)
#define _cm_bcast16(dst, imm32)                 _csram_utype(BCAST16, &dst, imm32)
#define _cm_slli16(dst, a, imm16)               _csram_itype(SLLI16, &dst, &a, imm16)
#define _cm_srli16(dst, a, imm16)               _csram_itype(SRLI16, &dst, &a, imm16)
#define _cm_adds16(dst, a, b)                   _csram_rtype(ADDS16, &dst, &a, &b)
#define _cm_add16(dst, a, b)                    _csram_rtype(ADD16, &dst, &a, &b)
#define _cm_sub16(dst, a, b)                    _csram_rtype(SUB16, &dst, &a, &b)
#define _cm_subs16(dst, a, b)                   _csram_rtype(SUBS16, &dst, &a, &b)
#define _cm_cmp16(dst, a, b)                    _csram_rtype(CMP16, &dst, &a, &b)
#define _cm_mul16(dst, a, b)                    _csram_rtype(MUL16, &dst, &a, &b)
#define _cm_fmac16(dst, a, b)                   _csram_rtype(FMAC16, &dst, &a, &b)
#define _cm_hswap32(dst, a)                     _csram_itype(HSWAP32, &dst, &a, 0)
#define _cm_copyeq32(dst, a, b)                 _csram_rtype(COPYEQ32, &dst, &a, &b)
#define _cm_copygeq32(dst, a, b)                _csram_rtype(COPYGEQ32, &dst, &a, &b)
#define _cm_copygt32(dst, a, b)                 _csram_rtype(COPYGT32, &dst, &a, &b)
#define _cm_copyleq32(dst, a, b)                _csram_rtype(COPYLEQ32, &dst, &a, &b)
#define _cm_copylt32(dst, a, b)                 _csram_rtype(COPYLT32, &dst, &a, &b)
#define _cm_copyneq32(dst, a, b)                _csram_rtype(COPYNEQ32, &dst, &a, &b)
#define _cm_bcast32(dst, imm32)                 _csram_utype(BCAST32, &dst, imm32)
#define _cm_slli32(dst, a, imm16)               _csram_itype(SLLI32, &dst, &a, imm16)
#define _cm_srli32(dst, a, imm16)               _csram_itype(SRLI32, &dst, &a, imm16)
#define _cm_adds32(dst, a, b)                   _csram_rtype(ADDS32, &dst, &a, &b)
#define _cm_add32(dst, a, b)                    _csram_rtype(ADD32, &dst, &a, &b)
#define _cm_sub32(dst, a, b)                    _csram_rtype(SUB32, &dst, &a, &b)
#define _cm_subs32(dst, a, b)                   _csram_rtype(SUBS32, &dst, &a, &b)
#define _cm_cmp32(dst, a, b)                    _csram_rtype(CMP32, &dst, &a, &b)
#define _cm_mul32(dst, a, b)                    _csram_rtype(MUL32, &dst, &a, &b)
#define _cm_fmac32(dst, a, b)                   _csram_rtype(FMAC32, &dst, &a, &b)
#define _cm_hswap64(dst, a)                     _csram_itype(HSWAP64, &dst, &a, 0)
#define _cm_copy(dst, a)                        _csram_itype(COPY, &dst, &a, 0)
#define _cm_not(dst, a)                         _csram_itype(NOT, &dst, &a, 0)
#define _cm_redor(dst, a)                       _csram_itype(REDOR, &dst, &a, 0)
#define _cm_and(dst, a, b)                      _csram_rtype(AND, &dst, &a, &b)
#define _cm_or(dst, a, b)                       _csram_rtype(OR, &dst, &a, &b)
#define _cm_xor(dst, a, b)                      _csram_rtype(XOR, &dst, &a, &b)
#define _cm_nand(dst, a, b)                     _csram_rtype(NAND, &dst, &a, &b)
#define _cm_nor(dst, a, b)                      _csram_rtype(NOR, &dst, &a, &b)
#define _cm_xnor(dst, a, b)                     _csram_rtype(XNOR, &dst, &a, &b)
/*****************************************************************************
 *                    WARNING: End of auto-generated part                    *
 ****************************************************************************/

#endif /* __CSRAM_BASE_H__ */
