/* Begin Header autogenerated part */
#ifndef H2_COMMON
#define H2_COMMON
/* Common HybroGen inserted code */
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdbool.h>
#include <stdint.h>

bool h2_codeGenerationOK;	 // Does code generation fail ?
typedef int32_t h2_regSet_t; // Register set (signed, use -1 when not allocated)
static  uint32_t h2_insnGenerated;
typedef unsigned long long ticks_t;
static  ticks_t h2_codeGenTime;

typedef enum { H2REGISTER,    H2VALUE, } VALORREG;
typedef struct
{
  int ValOrReg; // is H2REGISTER or immediate VALUE ?
  char arith;   // int, flt or other arithmetic
  int vLen;     // vector len
  int wLen;     // word len
  int regNro;   // register number (if register)
  int valueImm; // immediate value (if not register)
  bool dontFree; // if register, don't free
} h2_sValue_t;
#define sValueDef(VALUE, ARITH, VECTORLEN, WORDLEN, REGNO, IMMVAL) ((h2_sValue_t){.ValOrReg = VALUE, .arith = ARITH, .vLen = VECTORLEN, .wLen = WORDLEN, .regNro = REGNO, .valueImm = IMMVAL})
#define intsValue(V)      sValueDef(H2VALUE, 'i', 1, 32, -1, V)
#define intReg32sValue(R) sValueDef(H2REGISTER, 'i', 1, 32, R, 0)
#define immValueZero intsValue(0)
// Usefull macro instruction to simplify instruction selector code
#define isInt64_1(P)  ((P.arith == 'i') && (P.wLen <= 64) && (P.vLen == 1))
#define isInt32_1(P)  ((P.arith == 'i') && (P.wLen <= 32) && (P.vLen == 1))
#define isInt0(P)     ((P.arith == 'i') && (P.ValOrReg == H2VALUE) && (0 == P.valueImm))
#define isInt1(P)     ((P.arith == 'i') && (P.ValOrReg == H2VALUE) && (1 == P.valueImm))
#define isValue(P)    ((P.arith == 'i') && (P.ValOrReg == H2VALUE))
#define isReg32(P, X) ((P.arith == 'i') && (P.ValOrReg == H2REGISTER) && (X == P.regNro))
#define isRRR(P0, P1, P2) (P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
#define isRRV(P0, P1, P2) (P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)


typedef union {
    float f;
    unsigned long i;
} h2_float_int_u;

static int h2_log2(int value)
{ // integer logarithm
  int log = 0;
  while (value >>= 1) { ++log; }
  return log;
}
// Print register map : F for free register, . for allocated
void printRev (int value, int pos)
{ // Print a bitset in reversal order (recursive)
  if (pos != 0)
	printRev (value >> 1, pos - 1);
  printf ("%1c", (value % 2)?'.':'F');
}

// Dynamic register allocation handling
// h2_regSet mask : 0 mean free register, 1 register set
//  3           2            1  Bit position = reg Number
// 1098 7654 3210 9876 5432 1098 7654 3210
// 1111 1111 1111 1111 0000 0001 0011 1111
typedef struct
{	// Register allocation sets for
  	// int, float, vector of ints, vector of floats
  int intSet, fltSet, vintSet, vfltSet ;
} h2_RegSets_t;

h2_RegSets_t h2_regSet, h2_regSetInit;

// Print integer register set
void printRegState(char * msg, int regNo, int registerSet)
{
  int count = 8 * sizeof (registerSet) - 1;
  h2_regSet_t tmpReg = registerSet;
  printf ("%02d : Reg %s\n", regNo, msg);
  for (int i = count; i >= 0; i--) // Tens
	(0 == (i % 10))?printf ("%d", i/10):printf (" ");
  printf ("\n");
  for (int i = count; i >= 0; i--) // Unit
	  printf ("%d", i%10);
  printf ("\n");
  printRev (tmpReg, count); // Bit set
  printf ("\n");
}

// Initialize registers sets allocation
static void h2_initRegisterMasks(int intmask, int fltmask, int vectorintmask, int vectorfltmask)
{ // See H2SymbolTable & H2RegisterBank
  h2_regSetInit  = (h2_RegSets_t){intmask, fltmask, vectorintmask, vectorfltmask};
}

static void h2_resetRegisterMasks() // Reset register set from initializers
{
  h2_regSet = h2_regSetInit;
#ifdef H2_DEBUG_REGISTER
  printRegState("RESET", -1, h2_regSet.intSet);
#endif // H2_DEBUG_REGISTER
}
int h2_getReg () // Get new register
{
  /* Search for the 1st free register */
  h2_regSet_t tmpReg = h2_regSet.intSet;
  for (int i = 0; i < 8 * sizeof (h2_regSet.intSet); i++)
	{
	  if (tmpReg % 2 == 0)
		{						/* Free register found */
		  h2_regSet.intSet = h2_regSet.intSet | (1 << i); /* Update regSet */
#ifdef H2_DEBUG_REGISTER
		  printRegState("GET", i, h2_regSet.intSet);
#endif // H2_DEBUG_REGISTER
		  return i;
		}
	  tmpReg >>= 1;
	}
  printf ("Register allocation failed\n");
  h2_codeGenerationOK = false;
  return -1;
}

// h2_regSet_t regToBeFreed[32];

void h2_freeReg (h2_regSet_t v) // Free a register
{
#if 1 // TODO : To be rethinked
      // Is the register freeable ?
  int isOK = (h2_regSetInit.intSet >> v) & 1;
  if (0 == isOK)
    {
	h2_regSet.intSet = h2_regSet.intSet & ~(1 << v); /* Update regSet */
#ifdef H2_DEBUG_REGISTER
    printRegState("FREE", v, h2_regSet.intSet);
#endif // H2_DEBUG_REGISTER
    }
#endif
}
#endif /*H2_COMMON*/
#ifndef H2_POWER
#define H2_POWER

#define H2SYS 					/* Has  operating system */

#include <stdint.h>
#ifdef H2SYS
#include <sys/mman.h>
#endif

/* aarch64 / power examples :
   https://github.com/FFTW/fftw3/blob/master/kernel/cycle.h */

typedef uint32_t      h2_insn_t;
static  h2_insn_t     *h2_asm_pc;
static  h2_insn_t     *h2_save_asm_pc;

static ticks_t h2_getticks(void)
{
     unsigned int tbl, tbu0, tbu1;

     do {
	  __asm__ __volatile__ ("mftbu %0" : "=r"(tbu0));
	  __asm__ __volatile__ ("mftb %0" : "=r"(tbl));
	  __asm__ __volatile__ ("mftbu %0" : "=r"(tbu1));
     } while (tbu0 != tbu1);

     return (((unsigned long long)tbu0) << 32) | tbl;
}

static void h2_iflush(void *addr, void *last)
{
	h2_insnGenerated = (last-addr)/sizeof (h2_insn_t);
#ifdef H2SYS
    long pageSize= getpagesize();
    void *ptmp= (char *)((long)addr & ~(pageSize - 1));
    if (mprotect(ptmp, (last - addr), PROT_READ | PROT_WRITE | PROT_EXEC))
    {
        perror("iflush: mprotect");
        exit(-1);
    }
#endif
#ifdef H2_DEBUG
    printf ("Flush data cache from %p to %p\n", addr, last);
	printf ("%ld insn generated in %ld ticks. %ld ticks / insn\n", h2_insnGenerated, h2_codeGenTime, h2_codeGenTime/h2_insnGenerated);
#endif
	if (!h2_codeGenerationOK)
	  {
		fprintf (stderr, "(iflush) Failed code generation\n");
		exit(-5);
	  }
}

static h2_insn_t *h2_malloc (size_t size)
{
  return malloc (size);
}

#endif /*H2_POWER*/
/* In memory instruction generator */
#define power_G32(INSN){ *(h2_asm_pc++) = (INSN);}

/* Single instruction binary code generator*/
#define P1_BLR__I_32_1() do /* ret */ { 	power_G32(((0x4e800020 >> 0) & 0xffffffff)); \
 } while(0);
#define V2_03_VADDSBS_RRR_I_8_16(r0,r1,r2) do /* add */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x300 & 0x7ff) >> 0)); } while(0);
#define V2_03_VADDUBS_RRR_I_8_16(r0,r1,r2) do /* add */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x200 & 0x7ff) >> 0)); } while(0);
#define V2_03_VADDSHS_RRR_I_16_8(r0,r1,r2) do /* add */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x340 & 0x7ff) >> 0)); } while(0);
#define V2_03_VADDUHS_RRR_I_16_8(r0,r1,r2) do /* add */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x240 & 0x7ff) >> 0)); } while(0);
#define V2_03_VADDUWS_RRR_I_32_4(r0,r1,r2) do /* add */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x280 & 0x7ff) >> 0)); } while(0);
#define P1_ADDI_RRI_I_32_1(r0,r1,i0) do /* add */ { 	power_G32(((0xe & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define V2_03_VADDSWS_RRR_I_32_4(r0,r1,r2) do /* add */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x380 & 0x7ff) >> 0)); } while(0);
#define P1_ADD_RRR_I_32_1(r0,r1,r2) do /* add */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x214 & 0x7ff) >> 0)); } while(0);
#define P1_ADD_RRR_I_64_1(r0,r1,r2) do /* add */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x214 & 0x7ff) >> 0)); } while(0);
#define P1_ADDI_RRI_I_64_1(r0,r1,i0) do /* add */ { 	power_G32(((0xe & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_SUBI_RRI_I_32_1(r0,r1,i0) do /* sub */ { 	power_G32(((0xe & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|(((-i0) & 0xffff) >> 0)); } while(0);
#define PPC_SUB_RRR_I_32_1(r0,r2,r1) do /* sub */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x50 & 0x7ff) >> 0)); } while(0);
#define P1_MULLW_RRR_I_32_1(r0,r1,r2) do /* mul */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x1d6 & 0x7ff) >> 0)); } while(0);
#define P1_MULLI_RRI_I_64_1(r0,r1,i0) do /* mul */ { 	power_G32(((0x7 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define PPC_DIVW_RRR_I_32_1(r0,r1,r2) do /* div */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x3d6 & 0x7ff) >> 0)); } while(0);
#define PPC_DIVD_RRR_I_64_1(r0,r1,r2) do /* div */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x3d2 & 0x7ff) >> 0)); } while(0);
#define PPC_DIVD__RRR_I_64_1(r0,r1,r2) do /* div */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x3d3 & 0x7ff) >> 0)); } while(0);
#define PPC_DIVDO_RRR_I_64_1(r0,r1,r2) do /* div */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x7d2 & 0x7ff) >> 0)); } while(0);
#define PPC_DIVDO__RRR_I_64_1(r0,r1,r2) do /* div */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x7d3 & 0x7ff) >> 0)); } while(0);
#define V2_03_VSLB_RRR_I_8_16(r0,r1,r2) do /* sl */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x104 & 0x7ff) >> 0)); } while(0);
#define V2_03_VSLH_RRR_I_16_8(r0,r1,r2) do /* sl */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x144 & 0x7ff) >> 0)); } while(0);
#define P1_SLW_RRR_I_32_1(r1,r0,r2) do /* sl */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x30 & 0x7ff) >> 0)); } while(0);
#define P1_SLW__RRR_I_32_1(r1,r0,r2) do /* sl */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x31 & 0x7ff) >> 0)); } while(0);
#define V2_03_VSLW_RRR_I_32_4(r0,r1,r2) do /* sl */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x184 & 0x7ff) >> 0)); } while(0);
#define PPC_SLD_RRR_I_64_1(r1,r0,r2) do /* sl */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x36 & 0x7ff) >> 0)); } while(0);
#define PPC_SLD__RRR_I_64_1(r1,r0,r2) do /* sl */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x37 & 0x7ff) >> 0)); } while(0);
#define V2_07_VSLD_RRR_I_64_2(r0,r1,r2) do /* sl */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x5c4 & 0x7ff) >> 0)); } while(0);
#define V2_03_VSL_RRR_I_128_1(r0,r1,r2) do /* sl */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x1c4 & 0x7ff) >> 0)); } while(0);
#define V2_03_VSRB_RRR_I_8_16(r0,r1,r2) do /* sr */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x204 & 0x7ff) >> 0)); } while(0);
#define V2_03_VSRH_RRR_I_16_8(r0,r1,r2) do /* sr */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x244 & 0x7ff) >> 0)); } while(0);
#define V2_03_VSRW_RRR_I_32_4(r0,r1,r2) do /* sr */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x284 & 0x7ff) >> 0)); } while(0);
#define V2_07_VSRD_RRR_I_64_2(r0,r1,r2) do /* sr */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x6c4 & 0x7ff) >> 0)); } while(0);
#define V2_03_VSR_RRR_I_128_1(r0,r1,r2) do /* sr */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x2c4 & 0x7ff) >> 0)); } while(0);
#define P1_STB_RRI_I_8_1(r1,r0,i0) do /* w */ { 	power_G32(((0x26 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_STBX_RRR_I_8_1(r1,r0,r2) do /* w */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x1ae & 0x7ff) >> 0)); } while(0);
#define P1_STH_RRI_I_16_1(r1,r0,i0) do /* w */ { 	power_G32(((0x2c & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_STW_RRI_I_32_1(r1,r0,i0) do /* w */ { 	power_G32(((0x24 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_STWX_RRR_I_32_1(r0,r1,r2) do /* w */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x12e & 0x7ff) >> 0)); } while(0);
#define PPC_STD_RRI_I_64_1(r1,r0,i0) do /* w */ { 	power_G32(((0x3e & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0x3fff) << 2)|((0x0 & 0x3) >> 0)); } while(0);
#define P1_LI_RI_I_32_1(r0,i0) do /* mv */ { 	power_G32(((0xe & 0x3f) << 26)|((r0 & 0x1f) << 21)|((0x0 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_MV_RR_I_32_1(r0,r1) do /* mv */ { 	power_G32(((0xe & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((0x0 & 0xffff) >> 0)); } while(0);
#define P1_LI_RI_I_64_1(r0,i0) do /* mv */ { 	power_G32(((0xe & 0x3f) << 26)|((r0 & 0x1f) << 21)|((0x0 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_LBZ_RRI_I_8_1(r0,r1,i0) do /* r */ { 	power_G32(((0x22 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_LBZX_RRR_I_8_1(r0,r1,r2) do /* r */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0xae & 0x7ff) >> 0)); } while(0);
#define P1_LHZ_RRI_I_16_1(r0,r1,i0) do /* r */ { 	power_G32(((0x28 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_LWZ_RRI_I_32_1(r0,r1,i0) do /* r */ { 	power_G32(((0x20 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_LWZU_RRI_I_32_1(r0,r1,i0) do /* r */ { 	power_G32(((0x21 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_LWZUX_RRR_I_32_1(r0,r1,r2) do /* r */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x6e & 0x7ff) >> 0)); } while(0);
#define P1_LWZX_RRR_I_32_1(r0,r1,r2) do /* r */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x2e & 0x7ff) >> 0)); } while(0);
h2_sValue_t power_genADD_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t power_genR_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t power_genSUB_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t power_genW_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t power_genRET_0();
h2_sValue_t power_genSL_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t power_genDIV_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t power_genMV_2(h2_sValue_t P0,h2_sValue_t P1);
h2_sValue_t power_genSR_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t power_genMUL_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t power_genADD_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for ADD instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
/* -*- c -*- */
// If 2 operands are constants do addition
if  ((P2.ValOrReg == H2VALUE) && (P1.ValOrReg == H2VALUE) && (P1.arith == 'i')&& (P2.arith == 'i'))
{
  return sValueDef(H2VALUE, P1.arith, P1.vLen, P1.wLen, -1, P1.valueImm + P2.valueImm );
}
if (isInt0 (P2))
  { // P0 = P1 + 0
    #ifdef H2_DEBUG_INSN
	printf ("Optim add for 0 (generic) return reg %d\n", P1.regNro);
    #endif
	P1.dontFree = true;
	return P1;
  }
if (isInt0 (P1))
  { // P0 = 0 + P2
    #ifdef H2_DEBUG_INSN
    printf ("Optim add for 0  (generic) return reg %d\n", P2.regNro);
    #endif
	P2.dontFree = true;
    return P2;
  }

// No specific optimisation for ADD/power

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 16) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VADDSBS_RRR_I_8_16(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 16) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VADDUBS_RRR_I_8_16(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VADDSHS_RRR_I_16_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VADDUHS_RRR_I_16_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VADDUWS_RRR_I_32_4(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_ADDI_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VADDSWS_RRR_I_32_4(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_ADD_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_ADD_RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_ADDI_RRI_I_64_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }
	printf ("Warning, ADD instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t power_genR_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for R instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for R

// No specific optimisation for R/power

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_LBZ_RRI_I_8_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_LBZX_RRR_I_8_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_LHZ_RRI_I_16_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_LWZ_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_LWZU_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_LWZUX_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_LWZX_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, R instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t power_genSUB_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for SUB instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
/* -*- c -*- */
// if 2 operands are constants do substraction evaluation (Thanks Kilian for the bug report)
if  ((P2.ValOrReg == H2VALUE) && (P1.ValOrReg == H2VALUE) && (P1.arith == 'i')&& (P2.arith == 'i'))
{
  return (h2_sValue_t) {H2VALUE, P1.arith, P1.vLen, P1.wLen, -1, P1.valueImm - P2.valueImm };
}

// No specific optimisation for SUB/power

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_SUBI_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	PPC_SUB_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, SUB instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t power_genW_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for W instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for W

/* -*- c -*- */
if (isValue(P1))
  { // Store constant (Should use RRI variant)
	h2_sValue_t PTMP = {H2REGISTER, P1.arith, P1.vLen, P1.wLen, h2_getReg()};
    #ifdef H2_DEBUG_INSN
      printf ("Fallback for no RI W (power)\\n");
    #endif
	// MV const in tmp register
	P1 = power_genMV_2(PTMP,  P1);
	// No return continue instruction selection
  }

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P1.arith == 'i') && (P1.wLen <= 8) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_STB_RRI_I_8_1(P0.regNro, P1.regNro, P2.valueImm);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 8) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_STBX_RRR_I_8_1(P0.regNro, P1.regNro, P2.regNro);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 16) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_STH_RRI_I_16_1(P0.regNro, P1.regNro, P2.valueImm);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 32) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_STW_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 32) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_STWX_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 64) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	PPC_STD_RRI_I_64_1(P0.regNro, P1.regNro, P2.valueImm);
	return P1;
    }
	printf ("Warning, W instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t power_genRET_0()
{
// No generic optimisation for RET

// No specific optimisation for RET/power

P1_BLR__I_32_1();
	
}
h2_sValue_t power_genSL_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for SL instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for SL

// No specific optimisation for SL/power

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 16) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VSLB_RRR_I_8_16(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VSLH_RRR_I_16_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_SLW_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_SLW__RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VSLW_RRR_I_32_4(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	PPC_SLD_RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	PPC_SLD__RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_07_VSLD_RRR_I_64_2(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 128) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VSL_RRR_I_128_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, SL instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t power_genDIV_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for DIV instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
/* -*- c -*- */
// if 2 operands are constants do division evaluation
if  ((P2.ValOrReg == H2VALUE) && (P1.ValOrReg == H2VALUE) && (P1.arith == 'i')&& (P2.arith == 'i'))
{
  return (h2_sValue_t) {H2VALUE, P1.arith, P1.vLen, P1.wLen, -1, P1.valueImm / P2.valueImm };
}
// Transform RIR in RRI : P1 & P2 permutation
if  ((P1.ValOrReg == H2VALUE) && (P2.ValOrReg == H2REGISTER))
    {
       h2_sValue_t PTMP = P2;
       P2 = P1;
       P1 = PTMP;
    }

/* -*- c -*- */
if  ((P2.ValOrReg == H2VALUE) && (P2.arith == 'i'))
{
	h2_sValue_t PTMP = {H2REGISTER, P2.arith, P2.vLen, P2.wLen, h2_getReg()};
    #ifdef H2_DEBUG_INSN
      printf ("Fallback for no RRI div (power)\\n");
    #endif
	P2 = power_genMV_2(PTMP,  P2);
}

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	PPC_DIVW_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	PPC_DIVD_RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	PPC_DIVD__RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	PPC_DIVDO_RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	PPC_DIVDO__RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, DIV instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t power_genMV_2(h2_sValue_t P0,h2_sValue_t P1)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for MV instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for MV

// No specific optimisation for MV/power

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2VALUE)
    {
	P1_LI_RI_I_32_1(P0.regNro, P1.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	P1_MV_RR_I_32_1(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2VALUE)
    {
	P1_LI_RI_I_64_1(P0.regNro, P1.valueImm);
	return P0;
    }
	printf ("Warning, MV instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);return immValueZero;
}
h2_sValue_t power_genSR_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for SR instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for SR

// No specific optimisation for SR/power

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 16) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VSRB_RRR_I_8_16(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VSRH_RRR_I_16_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VSRW_RRR_I_32_4(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_07_VSRD_RRR_I_64_2(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 128) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VSR_RRR_I_128_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, SR instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t power_genMUL_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for MUL instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
/* -*- c -*- */
  // if 2 operands are constants do multiplication evaluation (Thanks Kilian for the bug report)
  if  ((P2.ValOrReg == H2VALUE) && (P1.ValOrReg == H2VALUE) && (P1.arith == 'i')&& (P2.arith == 'i'))
  {
    return (h2_sValue_t) {H2VALUE, P1.arith, P1.vLen, P1.wLen, -1, P1.valueImm * P2.valueImm };
  }
  /* if (isInt0(P2) || isInt0(P1)) */
  /*  {    // X * 0 = 0 Avoid 1 operation mul & 1 mv */
  /*       #ifdef H2_DEBUG_INSN */
  /*       printf ("Optim for *0 P2 (generic)\n"); */
  /*       #endif */
  /*       return immValueZero; */
  /*   } */
  /* if (isInt1(P2)) */
  /*   { // X * 1 = X propagate register result */
  /*       #ifdef H2_DEBUG_INSN */
  /*       printf ("Optim for *1 P2 (generic)\n"); */
  /*       #endif */
  /* 		P1.dontFree = true; */
  /*       return P1; */
  /*   } */
  /* if (isInt1(P1)) */
  /*   { // 1 * X = X propagate register result */
  /*       #ifdef H2_DEBUG_INSN */
  /*       printf ("Optim for *1 P1 (generic)\n"); */
  /*       #endif */
  /* 		P2.dontFree = true; */
  /*       return P2; */
  /*   } */

// No specific optimisation for MUL/power

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_MULLW_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_MULLI_RRI_I_64_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }
	printf ("Warning, MUL instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}

/* End Header autogenerated part */
// -*- c -*-
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <assert.h>
#include "ReadPgmImage.h"

typedef  int (*pifc)(int[], int, int, int);


void printImage(imgStruct_t *img, char *imageName)
{
  printf ("ImageName & size: %s %dx%d\n", imageName, img->height, img->width);
  for(int line = 0 ; line < img->height ; line++)
	{
	  for(int column = 0 ; column < img->width ; column++)
		{
		  printf("%03d ", img->pixelsArray[line*img->width+column]);
		}
	  printf("\n");
	}
  printf("\n");
}

int imgSum (imgStruct_t *img)
{
  int line, column, sum;
  sum = 0;
  for(int line = 0 ; line < img->height ; line++)
	{
	  for(int column = 0 ; column < img->width; column++)
		{
		  sum += img->pixelsArray[line*img->width+column];
		}
	}
  return (0 == sum)?1:sum;
}

#if 0
unsigned char clamp(int value)
{
  return (unsigned char)(0 > value)?0:(255 < value)?255:value;
}
#else
#define clamp(value) ((unsigned char)(0 > value)?0:(255 < value)?255:value)
#endif

pifc genKernel1x1(pifc ptr, int* Filter, int coeff)
{
	/* Code Generation of 3 instructions */
	/* Symbol table :*/
	/*VarName = {ValOrLen, arith, vectorLen, wordLen, regNo, ValueImm, dontFree} */
	h2_sValue_t In = {H2REGISTER, 'i', 1, 32, 3, true};
	h2_sValue_t line = {H2REGISTER, 'i', 1, 32, 4, true};
	h2_sValue_t column = {H2REGISTER, 'i', 1, 32, 5, true};
	h2_sValue_t imgWidth = {H2REGISTER, 'i', 1, 32, 6, true};
	h2_sValue_t h2_outputVarName = {H2REGISTER, 'i', 1, 32, 3, true};
	h2_sValue_t sum = {H2REGISTER, 'i', 1, 32, 14, true};
	h2_sValue_t tmp0000 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0001 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0002 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0003 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0004 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0005 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0006 = {H2REGISTER, 'i', 1, 32, -1, false};

	/* Label  table :*/
/* No label table to avoid C warning for empty table ... */
	h2_asm_pc = (h2_insn_t *) ptr;
	h2_codeGenerationOK = true;
	h2_codeGenTime = h2_getticks();
	h2_initRegisterMasks(0x787F, 0, 0, 0);
	h2_resetRegisterMasks();
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask initialization\n");
	#endif // H2_DEBUG_REGISTER
	
							tmp0000 = power_genMUL_3(tmp0000, line, imgWidth);
						tmp0001 = power_genADD_3(tmp0001, tmp0000, column);
					if (!tmp0001.dontFree) h2_freeReg(tmp0000.regNro);
					tmp0002 = power_genMUL_3(tmp0002, tmp0001, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
				if (!tmp0002.dontFree) h2_freeReg(tmp0001.regNro);
					tmp0003 = power_genADD_3(tmp0003, In, tmp0002);
			if (!tmp0003.dontFree) h2_freeReg(tmp0002.regNro);
			tmp0004 = power_genR_3(tmp0004, tmp0003, immValueZero);
		sum = power_genMUL_3(sum, tmp0004, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[0]))});
	if (!sum.dontFree) h2_freeReg(tmp0004.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
			tmp0005 = power_genDIV_3(tmp0005, sum, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((coeff))});
			h2_outputVarName = power_genMV_2(h2_outputVarName, tmp0005);
	if (!tmp0006.dontFree) h2_freeReg(tmp0005.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	power_genRET_0();
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	/* Call back code for loops */
	h2_save_asm_pc = h2_asm_pc;
	h2_asm_pc = h2_save_asm_pc;
	h2_codeGenTime = h2_getticks() - h2_codeGenTime;
	h2_iflush(ptr, h2_asm_pc);

  return ptr;
}

pifc genKernel3x3(pifc ptr, int* Filter, int coeff)
{
	/* Code Generation of 19 instructions */
	/* Symbol table :*/
	/*VarName = {ValOrLen, arith, vectorLen, wordLen, regNo, ValueImm, dontFree} */
	h2_sValue_t In = {H2REGISTER, 'i', 1, 32, 3, true};
	h2_sValue_t line = {H2REGISTER, 'i', 1, 32, 4, true};
	h2_sValue_t column = {H2REGISTER, 'i', 1, 32, 5, true};
	h2_sValue_t imgWidth = {H2REGISTER, 'i', 1, 32, 6, true};
	h2_sValue_t h2_outputVarName = {H2REGISTER, 'i', 1, 32, 3, true};
	h2_sValue_t sum = {H2REGISTER, 'i', 1, 32, 14, true};
	h2_sValue_t ni = {H2REGISTER, 'i', 1, 32, 15, true};
	h2_sValue_t njp1 = {H2REGISTER, 'i', 1, 32, 16, true};
	h2_sValue_t njm1 = {H2REGISTER, 'i', 1, 32, 17, true};
	h2_sValue_t stride = {H2REGISTER, 'i', 1, 32, 18, true};
	h2_sValue_t tmp0000 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0001 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0002 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0003 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0004 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0005 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0006 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0007 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0008 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0009 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0010 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0011 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0012 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0013 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0014 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0015 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0016 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0017 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0018 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0019 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0020 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0021 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0022 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0023 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0024 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0025 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0026 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0027 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0028 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0029 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0030 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0031 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0032 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0033 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0034 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0035 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0036 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0037 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0038 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0039 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0040 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0041 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0042 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0043 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0044 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0045 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0046 = {H2REGISTER, 'i', 1, 32, -1, false};

	/* Label  table :*/
/* No label table to avoid C warning for empty table ... */
	h2_asm_pc = (h2_insn_t *) ptr;
	h2_codeGenerationOK = true;
	h2_codeGenTime = h2_getticks();
	h2_initRegisterMasks(0x7F87F, 0, 0, 0);
	h2_resetRegisterMasks();
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask initialization\n");
	#endif // H2_DEBUG_REGISTER
	
		njp1 = power_genADD_3(njp1, column, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(1)});
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		njm1 = power_genSUB_3(njm1, column, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(1)});
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		ni = power_genSUB_3(ni, line, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(1)});
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		stride = power_genMUL_3(stride, ni, imgWidth);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
						tmp0000 = power_genADD_3(tmp0000, stride, njm1);
					tmp0001 = power_genMUL_3(tmp0001, tmp0000, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
				if (!tmp0001.dontFree) h2_freeReg(tmp0000.regNro);
					tmp0002 = power_genADD_3(tmp0002, In, tmp0001);
			if (!tmp0002.dontFree) h2_freeReg(tmp0001.regNro);
			tmp0003 = power_genR_3(tmp0003, tmp0002, immValueZero);
		sum = power_genMUL_3(sum, tmp0003, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[0]))});
	if (!sum.dontFree) h2_freeReg(tmp0003.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0004 = power_genADD_3(tmp0004, stride, column);
						tmp0005 = power_genMUL_3(tmp0005, tmp0004, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0005.dontFree) h2_freeReg(tmp0004.regNro);
						tmp0006 = power_genADD_3(tmp0006, In, tmp0005);
				if (!tmp0006.dontFree) h2_freeReg(tmp0005.regNro);
				tmp0007 = power_genR_3(tmp0007, tmp0006, immValueZero);
			tmp0008 = power_genMUL_3(tmp0008, tmp0007, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[1]))});
		if (!tmp0008.dontFree) h2_freeReg(tmp0007.regNro);
			sum = power_genADD_3(sum, sum, tmp0008);
	if (!sum.dontFree) h2_freeReg(tmp0008.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0009 = power_genADD_3(tmp0009, stride, njp1);
						tmp0010 = power_genMUL_3(tmp0010, tmp0009, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0010.dontFree) h2_freeReg(tmp0009.regNro);
						tmp0011 = power_genADD_3(tmp0011, In, tmp0010);
				if (!tmp0011.dontFree) h2_freeReg(tmp0010.regNro);
				tmp0012 = power_genR_3(tmp0012, tmp0011, immValueZero);
			tmp0013 = power_genMUL_3(tmp0013, tmp0012, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[2]))});
		if (!tmp0013.dontFree) h2_freeReg(tmp0012.regNro);
			sum = power_genADD_3(sum, sum, tmp0013);
	if (!sum.dontFree) h2_freeReg(tmp0013.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		ni = power_genMV_2(ni, line);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		stride = power_genMUL_3(stride, ni, imgWidth);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0015 = power_genADD_3(tmp0015, stride, njm1);
						tmp0016 = power_genMUL_3(tmp0016, tmp0015, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0016.dontFree) h2_freeReg(tmp0015.regNro);
						tmp0017 = power_genADD_3(tmp0017, In, tmp0016);
				if (!tmp0017.dontFree) h2_freeReg(tmp0016.regNro);
				tmp0018 = power_genR_3(tmp0018, tmp0017, immValueZero);
			tmp0019 = power_genMUL_3(tmp0019, tmp0018, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[1*3+0]))});
		if (!tmp0019.dontFree) h2_freeReg(tmp0018.regNro);
			sum = power_genADD_3(sum, sum, tmp0019);
	if (!sum.dontFree) h2_freeReg(tmp0019.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0020 = power_genADD_3(tmp0020, stride, column);
						tmp0021 = power_genMUL_3(tmp0021, tmp0020, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0021.dontFree) h2_freeReg(tmp0020.regNro);
						tmp0022 = power_genADD_3(tmp0022, In, tmp0021);
				if (!tmp0022.dontFree) h2_freeReg(tmp0021.regNro);
				tmp0023 = power_genR_3(tmp0023, tmp0022, immValueZero);
			tmp0024 = power_genMUL_3(tmp0024, tmp0023, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[1*3+1]))});
		if (!tmp0024.dontFree) h2_freeReg(tmp0023.regNro);
			sum = power_genADD_3(sum, sum, tmp0024);
	if (!sum.dontFree) h2_freeReg(tmp0024.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0025 = power_genADD_3(tmp0025, stride, njp1);
						tmp0026 = power_genMUL_3(tmp0026, tmp0025, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0026.dontFree) h2_freeReg(tmp0025.regNro);
						tmp0027 = power_genADD_3(tmp0027, In, tmp0026);
				if (!tmp0027.dontFree) h2_freeReg(tmp0026.regNro);
				tmp0028 = power_genR_3(tmp0028, tmp0027, immValueZero);
			tmp0029 = power_genMUL_3(tmp0029, tmp0028, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[1*3+2]))});
		if (!tmp0029.dontFree) h2_freeReg(tmp0028.regNro);
			sum = power_genADD_3(sum, sum, tmp0029);
	if (!sum.dontFree) h2_freeReg(tmp0029.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		ni = power_genADD_3(ni, line, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(1)});
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		stride = power_genMUL_3(stride, ni, imgWidth);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0030 = power_genADD_3(tmp0030, stride, njm1);
						tmp0031 = power_genMUL_3(tmp0031, tmp0030, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0031.dontFree) h2_freeReg(tmp0030.regNro);
						tmp0032 = power_genADD_3(tmp0032, In, tmp0031);
				if (!tmp0032.dontFree) h2_freeReg(tmp0031.regNro);
				tmp0033 = power_genR_3(tmp0033, tmp0032, immValueZero);
			tmp0034 = power_genMUL_3(tmp0034, tmp0033, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[2*3+0]))});
		if (!tmp0034.dontFree) h2_freeReg(tmp0033.regNro);
			sum = power_genADD_3(sum, sum, tmp0034);
	if (!sum.dontFree) h2_freeReg(tmp0034.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0035 = power_genADD_3(tmp0035, stride, column);
						tmp0036 = power_genMUL_3(tmp0036, tmp0035, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0036.dontFree) h2_freeReg(tmp0035.regNro);
						tmp0037 = power_genADD_3(tmp0037, In, tmp0036);
				if (!tmp0037.dontFree) h2_freeReg(tmp0036.regNro);
				tmp0038 = power_genR_3(tmp0038, tmp0037, immValueZero);
			tmp0039 = power_genMUL_3(tmp0039, tmp0038, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[2*3+1]))});
		if (!tmp0039.dontFree) h2_freeReg(tmp0038.regNro);
			sum = power_genADD_3(sum, sum, tmp0039);
	if (!sum.dontFree) h2_freeReg(tmp0039.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0040 = power_genADD_3(tmp0040, stride, njp1);
						tmp0041 = power_genMUL_3(tmp0041, tmp0040, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0041.dontFree) h2_freeReg(tmp0040.regNro);
						tmp0042 = power_genADD_3(tmp0042, In, tmp0041);
				if (!tmp0042.dontFree) h2_freeReg(tmp0041.regNro);
				tmp0043 = power_genR_3(tmp0043, tmp0042, immValueZero);
			tmp0044 = power_genMUL_3(tmp0044, tmp0043, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[2*3+2]))});
		if (!tmp0044.dontFree) h2_freeReg(tmp0043.regNro);
			sum = power_genADD_3(sum, sum, tmp0044);
	if (!sum.dontFree) h2_freeReg(tmp0044.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
			tmp0045 = power_genDIV_3(tmp0045, sum, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((coeff))});
			h2_outputVarName = power_genMV_2(h2_outputVarName, tmp0045);
	if (!tmp0046.dontFree) h2_freeReg(tmp0045.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	power_genRET_0();
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	/* Call back code for loops */
	h2_save_asm_pc = h2_asm_pc;
	h2_asm_pc = h2_save_asm_pc;
	h2_codeGenTime = h2_getticks() - h2_codeGenTime;
	h2_iflush(ptr, h2_asm_pc);

  return ptr;
}

pifc genKernel5x5(pifc ptr, int* Filter, int coeff)
{
	/* Code Generation of 41 instructions */
	/* Symbol table :*/
	/*VarName = {ValOrLen, arith, vectorLen, wordLen, regNo, ValueImm, dontFree} */
	h2_sValue_t In = {H2REGISTER, 'i', 1, 32, 3, true};
	h2_sValue_t line = {H2REGISTER, 'i', 1, 32, 4, true};
	h2_sValue_t column = {H2REGISTER, 'i', 1, 32, 5, true};
	h2_sValue_t imgWidth = {H2REGISTER, 'i', 1, 32, 6, true};
	h2_sValue_t h2_outputVarName = {H2REGISTER, 'i', 1, 32, 3, true};
	h2_sValue_t sum = {H2REGISTER, 'i', 1, 32, 14, true};
	h2_sValue_t ni = {H2REGISTER, 'i', 1, 32, 15, true};
	h2_sValue_t njm2 = {H2REGISTER, 'i', 1, 32, 16, true};
	h2_sValue_t njm1 = {H2REGISTER, 'i', 1, 32, 17, true};
	h2_sValue_t njp1 = {H2REGISTER, 'i', 1, 32, 18, true};
	h2_sValue_t njp2 = {H2REGISTER, 'i', 1, 32, 19, true};
	h2_sValue_t stride = {H2REGISTER, 'i', 1, 32, 20, true};
	h2_sValue_t tmp0000 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0001 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0002 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0003 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0004 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0005 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0006 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0007 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0008 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0009 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0010 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0011 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0012 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0013 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0014 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0015 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0016 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0017 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0018 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0019 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0020 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0021 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0022 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0023 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0024 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0025 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0026 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0027 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0028 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0029 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0030 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0031 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0032 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0033 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0034 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0035 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0036 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0037 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0038 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0039 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0040 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0041 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0042 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0043 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0044 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0045 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0046 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0047 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0048 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0049 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0050 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0051 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0052 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0053 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0054 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0055 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0056 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0057 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0058 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0059 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0060 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0061 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0062 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0063 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0064 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0065 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0066 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0067 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0068 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0069 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0070 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0071 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0072 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0073 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0074 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0075 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0076 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0077 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0078 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0079 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0080 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0081 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0082 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0083 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0084 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0085 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0086 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0087 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0088 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0089 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0090 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0091 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0092 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0093 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0094 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0095 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0096 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0097 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0098 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0099 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0100 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0101 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0102 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0103 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0104 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0105 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0106 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0107 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0108 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0109 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0110 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0111 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0112 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0113 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0114 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0115 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0116 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0117 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0118 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0119 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0120 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0121 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0122 = {H2REGISTER, 'i', 1, 64, -1, false};
	h2_sValue_t tmp0123 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0124 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0125 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0126 = {H2REGISTER, 'i', 1, 32, -1, false};

	/* Label  table :*/
/* No label table to avoid C warning for empty table ... */
	h2_asm_pc = (h2_insn_t *) ptr;
	h2_codeGenerationOK = true;
	h2_codeGenTime = h2_getticks();
	h2_initRegisterMasks(0x1FF87F, 0, 0, 0);
	h2_resetRegisterMasks();
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask initialization\n");
	#endif // H2_DEBUG_REGISTER
	
		njm2 = power_genSUB_3(njm2, column, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(2)});
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		njm1 = power_genSUB_3(njm1, column, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(1)});
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		njp1 = power_genADD_3(njp1, column, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(1)});
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		njp2 = power_genADD_3(njp2, column, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(2)});
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		ni = power_genSUB_3(ni, line, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(2)});
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		stride = power_genMUL_3(stride, ni, imgWidth);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
						tmp0000 = power_genADD_3(tmp0000, stride, njm2);
					tmp0001 = power_genMUL_3(tmp0001, tmp0000, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
				if (!tmp0001.dontFree) h2_freeReg(tmp0000.regNro);
					tmp0002 = power_genADD_3(tmp0002, In, tmp0001);
			if (!tmp0002.dontFree) h2_freeReg(tmp0001.regNro);
			tmp0003 = power_genR_3(tmp0003, tmp0002, immValueZero);
		sum = power_genMUL_3(sum, tmp0003, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[0*5+0]))});
	if (!sum.dontFree) h2_freeReg(tmp0003.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0004 = power_genADD_3(tmp0004, stride, njm1);
						tmp0005 = power_genMUL_3(tmp0005, tmp0004, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0005.dontFree) h2_freeReg(tmp0004.regNro);
						tmp0006 = power_genADD_3(tmp0006, In, tmp0005);
				if (!tmp0006.dontFree) h2_freeReg(tmp0005.regNro);
				tmp0007 = power_genR_3(tmp0007, tmp0006, immValueZero);
			tmp0008 = power_genMUL_3(tmp0008, tmp0007, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[0*5+1]))});
		if (!tmp0008.dontFree) h2_freeReg(tmp0007.regNro);
			sum = power_genADD_3(sum, sum, tmp0008);
	if (!sum.dontFree) h2_freeReg(tmp0008.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0009 = power_genADD_3(tmp0009, stride, column);
						tmp0010 = power_genMUL_3(tmp0010, tmp0009, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0010.dontFree) h2_freeReg(tmp0009.regNro);
						tmp0011 = power_genADD_3(tmp0011, In, tmp0010);
				if (!tmp0011.dontFree) h2_freeReg(tmp0010.regNro);
				tmp0012 = power_genR_3(tmp0012, tmp0011, immValueZero);
			tmp0013 = power_genMUL_3(tmp0013, tmp0012, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[0*5+2]))});
		if (!tmp0013.dontFree) h2_freeReg(tmp0012.regNro);
			sum = power_genADD_3(sum, sum, tmp0013);
	if (!sum.dontFree) h2_freeReg(tmp0013.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0014 = power_genADD_3(tmp0014, stride, njp1);
						tmp0015 = power_genMUL_3(tmp0015, tmp0014, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0015.dontFree) h2_freeReg(tmp0014.regNro);
						tmp0016 = power_genADD_3(tmp0016, In, tmp0015);
				if (!tmp0016.dontFree) h2_freeReg(tmp0015.regNro);
				tmp0017 = power_genR_3(tmp0017, tmp0016, immValueZero);
			tmp0018 = power_genMUL_3(tmp0018, tmp0017, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[0*5+3]))});
		if (!tmp0018.dontFree) h2_freeReg(tmp0017.regNro);
			sum = power_genADD_3(sum, sum, tmp0018);
	if (!sum.dontFree) h2_freeReg(tmp0018.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0019 = power_genADD_3(tmp0019, stride, njp2);
						tmp0020 = power_genMUL_3(tmp0020, tmp0019, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0020.dontFree) h2_freeReg(tmp0019.regNro);
						tmp0021 = power_genADD_3(tmp0021, In, tmp0020);
				if (!tmp0021.dontFree) h2_freeReg(tmp0020.regNro);
				tmp0022 = power_genR_3(tmp0022, tmp0021, immValueZero);
			tmp0023 = power_genMUL_3(tmp0023, tmp0022, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[0*5+4]))});
		if (!tmp0023.dontFree) h2_freeReg(tmp0022.regNro);
			sum = power_genADD_3(sum, sum, tmp0023);
	if (!sum.dontFree) h2_freeReg(tmp0023.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		ni = power_genSUB_3(ni, line, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(1)});
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		stride = power_genMUL_3(stride, ni, imgWidth);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0024 = power_genADD_3(tmp0024, stride, njm2);
						tmp0025 = power_genMUL_3(tmp0025, tmp0024, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0025.dontFree) h2_freeReg(tmp0024.regNro);
						tmp0026 = power_genADD_3(tmp0026, In, tmp0025);
				if (!tmp0026.dontFree) h2_freeReg(tmp0025.regNro);
				tmp0027 = power_genR_3(tmp0027, tmp0026, immValueZero);
			tmp0028 = power_genMUL_3(tmp0028, tmp0027, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[1*5+0]))});
		if (!tmp0028.dontFree) h2_freeReg(tmp0027.regNro);
			sum = power_genADD_3(sum, sum, tmp0028);
	if (!sum.dontFree) h2_freeReg(tmp0028.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0029 = power_genADD_3(tmp0029, stride, njm1);
						tmp0030 = power_genMUL_3(tmp0030, tmp0029, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0030.dontFree) h2_freeReg(tmp0029.regNro);
						tmp0031 = power_genADD_3(tmp0031, In, tmp0030);
				if (!tmp0031.dontFree) h2_freeReg(tmp0030.regNro);
				tmp0032 = power_genR_3(tmp0032, tmp0031, immValueZero);
			tmp0033 = power_genMUL_3(tmp0033, tmp0032, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[1*5+1]))});
		if (!tmp0033.dontFree) h2_freeReg(tmp0032.regNro);
			sum = power_genADD_3(sum, sum, tmp0033);
	if (!sum.dontFree) h2_freeReg(tmp0033.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0034 = power_genADD_3(tmp0034, stride, column);
						tmp0035 = power_genMUL_3(tmp0035, tmp0034, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0035.dontFree) h2_freeReg(tmp0034.regNro);
						tmp0036 = power_genADD_3(tmp0036, In, tmp0035);
				if (!tmp0036.dontFree) h2_freeReg(tmp0035.regNro);
				tmp0037 = power_genR_3(tmp0037, tmp0036, immValueZero);
			tmp0038 = power_genMUL_3(tmp0038, tmp0037, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[1*5+2]))});
		if (!tmp0038.dontFree) h2_freeReg(tmp0037.regNro);
			sum = power_genADD_3(sum, sum, tmp0038);
	if (!sum.dontFree) h2_freeReg(tmp0038.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0039 = power_genADD_3(tmp0039, stride, njp1);
						tmp0040 = power_genMUL_3(tmp0040, tmp0039, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0040.dontFree) h2_freeReg(tmp0039.regNro);
						tmp0041 = power_genADD_3(tmp0041, In, tmp0040);
				if (!tmp0041.dontFree) h2_freeReg(tmp0040.regNro);
				tmp0042 = power_genR_3(tmp0042, tmp0041, immValueZero);
			tmp0043 = power_genMUL_3(tmp0043, tmp0042, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[1*5+3]))});
		if (!tmp0043.dontFree) h2_freeReg(tmp0042.regNro);
			sum = power_genADD_3(sum, sum, tmp0043);
	if (!sum.dontFree) h2_freeReg(tmp0043.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0044 = power_genADD_3(tmp0044, stride, njp2);
						tmp0045 = power_genMUL_3(tmp0045, tmp0044, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0045.dontFree) h2_freeReg(tmp0044.regNro);
						tmp0046 = power_genADD_3(tmp0046, In, tmp0045);
				if (!tmp0046.dontFree) h2_freeReg(tmp0045.regNro);
				tmp0047 = power_genR_3(tmp0047, tmp0046, immValueZero);
			tmp0048 = power_genMUL_3(tmp0048, tmp0047, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[1*5+4]))});
		if (!tmp0048.dontFree) h2_freeReg(tmp0047.regNro);
			sum = power_genADD_3(sum, sum, tmp0048);
	if (!sum.dontFree) h2_freeReg(tmp0048.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		ni = power_genMV_2(ni, line);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		stride = power_genMUL_3(stride, ni, imgWidth);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0050 = power_genADD_3(tmp0050, stride, njm2);
						tmp0051 = power_genMUL_3(tmp0051, tmp0050, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0051.dontFree) h2_freeReg(tmp0050.regNro);
						tmp0052 = power_genADD_3(tmp0052, In, tmp0051);
				if (!tmp0052.dontFree) h2_freeReg(tmp0051.regNro);
				tmp0053 = power_genR_3(tmp0053, tmp0052, immValueZero);
			tmp0054 = power_genMUL_3(tmp0054, tmp0053, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[2*5+0]))});
		if (!tmp0054.dontFree) h2_freeReg(tmp0053.regNro);
			sum = power_genADD_3(sum, sum, tmp0054);
	if (!sum.dontFree) h2_freeReg(tmp0054.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0055 = power_genADD_3(tmp0055, stride, njm1);
						tmp0056 = power_genMUL_3(tmp0056, tmp0055, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0056.dontFree) h2_freeReg(tmp0055.regNro);
						tmp0057 = power_genADD_3(tmp0057, In, tmp0056);
				if (!tmp0057.dontFree) h2_freeReg(tmp0056.regNro);
				tmp0058 = power_genR_3(tmp0058, tmp0057, immValueZero);
			tmp0059 = power_genMUL_3(tmp0059, tmp0058, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[2*5+1]))});
		if (!tmp0059.dontFree) h2_freeReg(tmp0058.regNro);
			sum = power_genADD_3(sum, sum, tmp0059);
	if (!sum.dontFree) h2_freeReg(tmp0059.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0060 = power_genADD_3(tmp0060, stride, column);
						tmp0061 = power_genMUL_3(tmp0061, tmp0060, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0061.dontFree) h2_freeReg(tmp0060.regNro);
						tmp0062 = power_genADD_3(tmp0062, In, tmp0061);
				if (!tmp0062.dontFree) h2_freeReg(tmp0061.regNro);
				tmp0063 = power_genR_3(tmp0063, tmp0062, immValueZero);
			tmp0064 = power_genMUL_3(tmp0064, tmp0063, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[2*5+2]))});
		if (!tmp0064.dontFree) h2_freeReg(tmp0063.regNro);
			sum = power_genADD_3(sum, sum, tmp0064);
	if (!sum.dontFree) h2_freeReg(tmp0064.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0065 = power_genADD_3(tmp0065, stride, njp1);
						tmp0066 = power_genMUL_3(tmp0066, tmp0065, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0066.dontFree) h2_freeReg(tmp0065.regNro);
						tmp0067 = power_genADD_3(tmp0067, In, tmp0066);
				if (!tmp0067.dontFree) h2_freeReg(tmp0066.regNro);
				tmp0068 = power_genR_3(tmp0068, tmp0067, immValueZero);
			tmp0069 = power_genMUL_3(tmp0069, tmp0068, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[2*5+3]))});
		if (!tmp0069.dontFree) h2_freeReg(tmp0068.regNro);
			sum = power_genADD_3(sum, sum, tmp0069);
	if (!sum.dontFree) h2_freeReg(tmp0069.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0070 = power_genADD_3(tmp0070, stride, njp2);
						tmp0071 = power_genMUL_3(tmp0071, tmp0070, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0071.dontFree) h2_freeReg(tmp0070.regNro);
						tmp0072 = power_genADD_3(tmp0072, In, tmp0071);
				if (!tmp0072.dontFree) h2_freeReg(tmp0071.regNro);
				tmp0073 = power_genR_3(tmp0073, tmp0072, immValueZero);
			tmp0074 = power_genMUL_3(tmp0074, tmp0073, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[2*5+4]))});
		if (!tmp0074.dontFree) h2_freeReg(tmp0073.regNro);
			sum = power_genADD_3(sum, sum, tmp0074);
	if (!sum.dontFree) h2_freeReg(tmp0074.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		ni = power_genADD_3(ni, line, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(1)});
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		stride = power_genMUL_3(stride, ni, imgWidth);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0075 = power_genADD_3(tmp0075, stride, njm2);
						tmp0076 = power_genMUL_3(tmp0076, tmp0075, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0076.dontFree) h2_freeReg(tmp0075.regNro);
						tmp0077 = power_genADD_3(tmp0077, In, tmp0076);
				if (!tmp0077.dontFree) h2_freeReg(tmp0076.regNro);
				tmp0078 = power_genR_3(tmp0078, tmp0077, immValueZero);
			tmp0079 = power_genMUL_3(tmp0079, tmp0078, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[3*5+0]))});
		if (!tmp0079.dontFree) h2_freeReg(tmp0078.regNro);
			sum = power_genADD_3(sum, sum, tmp0079);
	if (!sum.dontFree) h2_freeReg(tmp0079.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0080 = power_genADD_3(tmp0080, stride, njm1);
						tmp0081 = power_genMUL_3(tmp0081, tmp0080, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0081.dontFree) h2_freeReg(tmp0080.regNro);
						tmp0082 = power_genADD_3(tmp0082, In, tmp0081);
				if (!tmp0082.dontFree) h2_freeReg(tmp0081.regNro);
				tmp0083 = power_genR_3(tmp0083, tmp0082, immValueZero);
			tmp0084 = power_genMUL_3(tmp0084, tmp0083, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[3*5+1]))});
		if (!tmp0084.dontFree) h2_freeReg(tmp0083.regNro);
			sum = power_genADD_3(sum, sum, tmp0084);
	if (!sum.dontFree) h2_freeReg(tmp0084.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0085 = power_genADD_3(tmp0085, stride, column);
						tmp0086 = power_genMUL_3(tmp0086, tmp0085, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0086.dontFree) h2_freeReg(tmp0085.regNro);
						tmp0087 = power_genADD_3(tmp0087, In, tmp0086);
				if (!tmp0087.dontFree) h2_freeReg(tmp0086.regNro);
				tmp0088 = power_genR_3(tmp0088, tmp0087, immValueZero);
			tmp0089 = power_genMUL_3(tmp0089, tmp0088, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[3*5+2]))});
		if (!tmp0089.dontFree) h2_freeReg(tmp0088.regNro);
			sum = power_genADD_3(sum, sum, tmp0089);
	if (!sum.dontFree) h2_freeReg(tmp0089.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0090 = power_genADD_3(tmp0090, stride, njp1);
						tmp0091 = power_genMUL_3(tmp0091, tmp0090, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0091.dontFree) h2_freeReg(tmp0090.regNro);
						tmp0092 = power_genADD_3(tmp0092, In, tmp0091);
				if (!tmp0092.dontFree) h2_freeReg(tmp0091.regNro);
				tmp0093 = power_genR_3(tmp0093, tmp0092, immValueZero);
			tmp0094 = power_genMUL_3(tmp0094, tmp0093, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[3*5+3]))});
		if (!tmp0094.dontFree) h2_freeReg(tmp0093.regNro);
			sum = power_genADD_3(sum, sum, tmp0094);
	if (!sum.dontFree) h2_freeReg(tmp0094.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0095 = power_genADD_3(tmp0095, stride, njp2);
						tmp0096 = power_genMUL_3(tmp0096, tmp0095, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0096.dontFree) h2_freeReg(tmp0095.regNro);
						tmp0097 = power_genADD_3(tmp0097, In, tmp0096);
				if (!tmp0097.dontFree) h2_freeReg(tmp0096.regNro);
				tmp0098 = power_genR_3(tmp0098, tmp0097, immValueZero);
			tmp0099 = power_genMUL_3(tmp0099, tmp0098, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[3*5+4]))});
		if (!tmp0099.dontFree) h2_freeReg(tmp0098.regNro);
			sum = power_genADD_3(sum, sum, tmp0099);
	if (!sum.dontFree) h2_freeReg(tmp0099.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		ni = power_genADD_3(ni, line, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(2)});
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		stride = power_genMUL_3(stride, ni, imgWidth);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0100 = power_genADD_3(tmp0100, stride, njm2);
						tmp0101 = power_genMUL_3(tmp0101, tmp0100, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0101.dontFree) h2_freeReg(tmp0100.regNro);
						tmp0102 = power_genADD_3(tmp0102, In, tmp0101);
				if (!tmp0102.dontFree) h2_freeReg(tmp0101.regNro);
				tmp0103 = power_genR_3(tmp0103, tmp0102, immValueZero);
			tmp0104 = power_genMUL_3(tmp0104, tmp0103, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[4*5+0]))});
		if (!tmp0104.dontFree) h2_freeReg(tmp0103.regNro);
			sum = power_genADD_3(sum, sum, tmp0104);
	if (!sum.dontFree) h2_freeReg(tmp0104.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0105 = power_genADD_3(tmp0105, stride, njm1);
						tmp0106 = power_genMUL_3(tmp0106, tmp0105, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0106.dontFree) h2_freeReg(tmp0105.regNro);
						tmp0107 = power_genADD_3(tmp0107, In, tmp0106);
				if (!tmp0107.dontFree) h2_freeReg(tmp0106.regNro);
				tmp0108 = power_genR_3(tmp0108, tmp0107, immValueZero);
			tmp0109 = power_genMUL_3(tmp0109, tmp0108, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[4*5+1]))});
		if (!tmp0109.dontFree) h2_freeReg(tmp0108.regNro);
			sum = power_genADD_3(sum, sum, tmp0109);
	if (!sum.dontFree) h2_freeReg(tmp0109.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0110 = power_genADD_3(tmp0110, stride, column);
						tmp0111 = power_genMUL_3(tmp0111, tmp0110, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0111.dontFree) h2_freeReg(tmp0110.regNro);
						tmp0112 = power_genADD_3(tmp0112, In, tmp0111);
				if (!tmp0112.dontFree) h2_freeReg(tmp0111.regNro);
				tmp0113 = power_genR_3(tmp0113, tmp0112, immValueZero);
			tmp0114 = power_genMUL_3(tmp0114, tmp0113, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[4*5+2]))});
		if (!tmp0114.dontFree) h2_freeReg(tmp0113.regNro);
			sum = power_genADD_3(sum, sum, tmp0114);
	if (!sum.dontFree) h2_freeReg(tmp0114.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0115 = power_genADD_3(tmp0115, stride, njp1);
						tmp0116 = power_genMUL_3(tmp0116, tmp0115, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0116.dontFree) h2_freeReg(tmp0115.regNro);
						tmp0117 = power_genADD_3(tmp0117, In, tmp0116);
				if (!tmp0117.dontFree) h2_freeReg(tmp0116.regNro);
				tmp0118 = power_genR_3(tmp0118, tmp0117, immValueZero);
			tmp0119 = power_genMUL_3(tmp0119, tmp0118, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[4*5+3]))});
		if (!tmp0119.dontFree) h2_freeReg(tmp0118.regNro);
			sum = power_genADD_3(sum, sum, tmp0119);
	if (!sum.dontFree) h2_freeReg(tmp0119.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
							tmp0120 = power_genADD_3(tmp0120, stride, njp2);
						tmp0121 = power_genMUL_3(tmp0121, tmp0120, (h2_sValue_t) {H2VALUE, 'i', 1, 64, 0, (int)((1 * 32) / 8)});
					if (!tmp0121.dontFree) h2_freeReg(tmp0120.regNro);
						tmp0122 = power_genADD_3(tmp0122, In, tmp0121);
				if (!tmp0122.dontFree) h2_freeReg(tmp0121.regNro);
				tmp0123 = power_genR_3(tmp0123, tmp0122, immValueZero);
			tmp0124 = power_genMUL_3(tmp0124, tmp0123, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((Filter[4*5+4]))});
		if (!tmp0124.dontFree) h2_freeReg(tmp0123.regNro);
			sum = power_genADD_3(sum, sum, tmp0124);
	if (!sum.dontFree) h2_freeReg(tmp0124.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
			tmp0125 = power_genDIV_3(tmp0125, sum, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((coeff))});
			h2_outputVarName = power_genMV_2(h2_outputVarName, tmp0125);
	if (!tmp0126.dontFree) h2_freeReg(tmp0125.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	power_genRET_0();
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	/* Call back code for loops */
	h2_save_asm_pc = h2_asm_pc;
	h2_asm_pc = h2_save_asm_pc;
	h2_codeGenTime = h2_getticks() - h2_codeGenTime;
	h2_iflush(ptr, h2_asm_pc);

  return ptr;
#if 0
#endif
}

// Compute a stencil for 1 point
int kernelStatic(imgStruct_t *In, int l, int c, imgStruct_t *Filter, int coeff)
{
  int line, column, sum = 0;
  int offset = (Filter->width)/2;

  for (line = 0; line < Filter->height; line++)
	{
      for (column = 0; column < Filter->width; column++)
		{
		  int ni = (l   + line)   - offset;
		  int nj = (c   + column) - offset;
		  sum += In->pixelsArray[ni*In->width+nj] * Filter->pixelsArray[line*Filter->width+column];
		}
	}
    return sum / coeff;
}


void convolutionStatic(imgStruct_t *In, imgStruct_t *Out, imgStruct_t *Filter, int coeff)
{
  int offset = Filter->width/2;
  int result;
  for (int line = offset; line < In->height - offset; line++)
	{
	  for (int column = offset; column < In->width - offset; column++)
		{
		  result = kernelStatic(In, line, column, Filter, coeff);
		  Out->pixelsArray[line*Out->width+column] =  clamp(result);
		}
    }
}

void convolutionH4(imgStruct_t* In, imgStruct_t *Out, imgStruct_t *Filter, pifc kernelHL)
{
  int offset = Filter->width/2;
  int result;
  for (int line = offset; line < In->height - offset; line++)
    {
      for (int column = offset; column <  In->width - offset; column++)
        {
          result = kernelHL(In->pixelsArray, line, column, In->width);
          Out->pixelsArray[line*Out->width+column] = clamp(result);
        }
    }
}

int compareImages(imgStruct_t *staticImg, imgStruct_t *H4Img)
{
  int errors = 0;
  for(int line = 0 ; line < staticImg->height ; line++)
	{
	  for(int column = 0 ; column < staticImg->width ; column++)
		{
		  if((staticImg->pixelsArray[line*staticImg->width+column] - H4Img->pixelsArray[line*H4Img->width+column])  != 0)
			{
			  if (0 == errors)
                {
                  printf("Alert : first difference at line %i column %i\n", line, column);
                }
			  errors++;
			}
		}
	}
  return errors;
}

int main(int argc, char *argv[])
{
  int error, coeff, nXperiment = 20;
  imgStruct_t *In, *OutH4, *OutStatic, *Filter;
  char *filterImageName, *inputImageName;
  if (argc < 5)
    {
      printf ("./Stencil <InputImageName> <outputStaticImageName> <outputH4ImageName> <Filter Img>\n");
      exit(-1);
    }

  inputImageName  = argv[1];
  filterImageName = argv[4];
  In     = readPgmImage(inputImageName);
  Filter = readPgmImage(filterImageName);
  coeff = imgSum (Filter);
#ifdef VERBOSE
  printf ("%s: coeff %d\n", filterImageName, coeff);
  printImage (Filter, "Filter");
#endif
  assert (Filter->width == Filter->height); // Only square filters
  OutStatic = createImage (In->height, In->width);
  OutH4     = createImage (In->height, In->width);
#ifdef VERBOSE
  printf ("after init\n");
  printImage(In, "In");
#endif
  ticks_t timeStatic = h2_getticks();   // Static convolution
  for (int i = 0; i < nXperiment; i++)
	{
	  convolutionStatic(In, OutStatic, Filter, coeff);
	}
  timeStatic = h2_getticks() - timeStatic;
#ifdef VERBOSE
  printf ("after static\n");
  printImage(OutStatic, "Out");
#endif

  pifc kernelHL = (pifc)h2_malloc(8192);
  ticks_t timeCodeGen = h2_getticks();
  switch (Filter->width)
    {
    case 1 : kernelHL = genKernel1x1 (kernelHL, Filter->pixelsArray, coeff); break;
    case 3 : kernelHL = genKernel3x3 (kernelHL, Filter->pixelsArray, coeff); break;
    case 5 : kernelHL = genKernel5x5 (kernelHL, Filter->pixelsArray, coeff); break;
    default: printf ("Unknown filter size\n"); exit(-1);
    }
  timeCodeGen = h2_getticks() - timeCodeGen;

#ifdef VERBOSE
  printf ("after codegen\n");
#endif

  ticks_t timeH4 = h2_getticks(); // Compilette convolution
  for (int i = 0; i < nXperiment; i++)
	{
	  convolutionH4(In, OutH4, Filter, kernelHL);
	}
  timeH4 = h2_getticks() - timeH4;
#ifdef VERBOSE
  printf ("after h2\n");
  printImage(OutH4, "Out H4");
#endif
  error = compareImages(OutH4, OutStatic);
  printf("%s;%ix%i;%ix%i;%lld;%lld;%lld;%d;%d\n",
		 filterImageName,
		 Filter->width, Filter->height, In->width, In->height,
		 timeStatic/nXperiment, timeH4/nXperiment,
		 h2_codeGenTime, h2_insnGenerated,
         error);

#if VERBOSE
  writePgmImage(OutStatic, argv[2]);
  writePgmImage(OutH4,     argv[3]);
#endif

  return (0 == error)?0:-1;
}
