/* Begin Header autogenerated part */
#ifndef H2_COMMON
#define H2_COMMON
/* Common HybroGen inserted code */
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdbool.h>
#include <stdint.h>

bool h2_codeGenerationOK;	 // Does code generation fail ?
typedef int32_t h2_regSet_t; // Register set (signed, use -1 when not allocated)
static  uint32_t h2_insnGenerated;
typedef unsigned long long ticks_t;
static  ticks_t h2_codeGenTime;

typedef enum { H2REGISTER,    H2VALUE, } VALORREG;
typedef struct
{
  int ValOrReg; // is H2REGISTER or immediate VALUE ?
  char arith;   // int, flt or other arithmetic
  int vLen;     // vector len
  int wLen;     // word len
  int regNro;   // register number (if register)
  int valueImm; // immediate value (if not register)
  bool dontFree; // if register, don't free
} h2_sValue_t;
#define sValueDef(VALUE, ARITH, VECTORLEN, WORDLEN, REGNO, IMMVAL) ((h2_sValue_t){.ValOrReg = VALUE, .arith = ARITH, .vLen = VECTORLEN, .wLen = WORDLEN, .regNro = REGNO, .valueImm = IMMVAL})
#define intsValue(V)      sValueDef(H2VALUE, 'i', 1, 32, -1, V)
#define intReg32sValue(R) sValueDef(H2REGISTER, 'i', 1, 32, R, 0)
#define immValueZero intsValue(0)
// Usefull macro instruction to simplify instruction selector code
#define isInt64_1(P)  ((P.arith == 'i') && (P.wLen <= 64) && (P.vLen == 1))
#define isInt32_1(P)  ((P.arith == 'i') && (P.wLen <= 32) && (P.vLen == 1))
#define isInt0(P)     ((P.arith == 'i') && (P.ValOrReg == H2VALUE) && (0 == P.valueImm))
#define isInt1(P)     ((P.arith == 'i') && (P.ValOrReg == H2VALUE) && (1 == P.valueImm))
#define isValue(P)    ((P.arith == 'i') && (P.ValOrReg == H2VALUE))
#define isReg32(P, X) ((P.arith == 'i') && (P.ValOrReg == H2REGISTER) && (X == P.regNro))
#define isRRR(P0, P1, P2) (P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
#define isRRV(P0, P1, P2) (P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)


typedef union {
    float f;
    unsigned long i;
} h2_float_int_u;

static int h2_log2(int value)
{ // integer logarithm
  int log = 0;
  while (value >>= 1) { ++log; }
  return log;
}
// Print register map : F for free register, . for allocated
void printRev (int value, int pos)
{ // Print a bitset in reversal order (recursive)
  if (pos != 0)
	printRev (value >> 1, pos - 1);
  printf ("%1c", (value % 2)?'.':'F');
}

// Dynamic register allocation handling
// h2_regSet mask : 0 mean free register, 1 register set
//  3           2            1  Bit position = reg Number
// 1098 7654 3210 9876 5432 1098 7654 3210
// 1111 1111 1111 1111 0000 0001 0011 1111
typedef struct
{	// Register allocation sets for
  	// int, float, vector of ints, vector of floats
  int intSet, fltSet, vintSet, vfltSet ;
} h2_RegSets_t;

h2_RegSets_t h2_regSet, h2_regSetInit;

// Print integer register set
void printRegState(char * msg, int regNo, int registerSet)
{
  int count = 8 * sizeof (registerSet) - 1;
  h2_regSet_t tmpReg = registerSet;
  printf ("%02d : Reg %s\n", regNo, msg);
  for (int i = count; i >= 0; i--) // Tens
	(0 == (i % 10))?printf ("%d", i/10):printf (" ");
  printf ("\n");
  for (int i = count; i >= 0; i--) // Unit
	  printf ("%d", i%10);
  printf ("\n");
  printRev (tmpReg, count); // Bit set
  printf ("\n");
}

// Initialize registers sets allocation
static void h2_initRegisterMasks(int intmask, int fltmask, int vectorintmask, int vectorfltmask)
{ // See H2SymbolTable & H2RegisterBank
  h2_regSetInit  = (h2_RegSets_t){intmask, fltmask, vectorintmask, vectorfltmask};
}

static void h2_resetRegisterMasks() // Reset register set from initializers
{
  h2_regSet = h2_regSetInit;
#ifdef H2_DEBUG_REGISTER
  printRegState("RESET", -1, h2_regSet.intSet);
#endif // H2_DEBUG_REGISTER
}
int h2_getReg () // Get new register
{
  /* Search for the 1st free register */
  h2_regSet_t tmpReg = h2_regSet.intSet;
  for (int i = 0; i < 8 * sizeof (h2_regSet.intSet); i++)
	{
	  if (tmpReg % 2 == 0)
		{						/* Free register found */
		  h2_regSet.intSet = h2_regSet.intSet | (1 << i); /* Update regSet */
#ifdef H2_DEBUG_REGISTER
		  printRegState("GET", i, h2_regSet.intSet);
#endif // H2_DEBUG_REGISTER
		  return i;
		}
	  tmpReg >>= 1;
	}
  printf ("Register allocation failed\n");
  h2_codeGenerationOK = false;
  return -1;
}

// h2_regSet_t regToBeFreed[32];

void h2_freeReg (h2_regSet_t v) // Free a register
{
#if 1 // TODO : To be rethinked
      // Is the register freeable ?
  int isOK = (h2_regSetInit.intSet >> v) & 1;
  if (0 == isOK)
    {
	h2_regSet.intSet = h2_regSet.intSet & ~(1 << v); /* Update regSet */
#ifdef H2_DEBUG_REGISTER
    printRegState("FREE", v, h2_regSet.intSet);
#endif // H2_DEBUG_REGISTER
    }
#endif
}
#endif /*H2_COMMON*/
#ifndef H2_AARCH64
#define H2_AARCH64

#define H2SYS 					/* Has  operating system */

#ifdef H2SYS
#include <sys/mman.h>
#endif

typedef uint32_t   h2_insn_t;   /* Instruction size */
static  h2_insn_t  *h2_asm_pc; /* PC for code generation */
static  h2_insn_t  *h2_save_asm_pc;
#define H2Aarch64SP  (h2_sValue_t) {REGISTER, 'i', 1, 32, 31, 0}
/* aarch64 / power examples :
   https://github.com/FFTW/fftw3/blob/master/kernel/cycle.h */

static inline ticks_t h2_getticks(void)
{
  uint64_t Rt;
  asm volatile("mrs %0,  CNTVCT_EL0" : "=r" (Rt));
  return Rt;
}

static void h2_iflush(void *addr, void *last)
{
	h2_insnGenerated = (last-addr)/sizeof (h2_insn_t);
#ifdef H2SYS
  __clear_cache((char *)addr, (char *)last); // Flush data cache where binary code were written
  long pageSize= getpagesize();              // Make the page executable
  void *ptmp= (char *)((long)addr & ~(pageSize - 1));
  if (mprotect(ptmp, (last - addr), PROT_READ | PROT_WRITE | PROT_EXEC))
    {
      perror("iflush: mprotect");
      exit(-1);
    }
    /* Gcc function to clear data cache after code generation */
    __clear_cache((char *)addr, (char *)last);
#endif
#ifdef H2_DEBUG
    printf ("Flush data cache from %p to %p\n", addr, last);
	printf ("%ld insn generated in %ld ticks. %ld ticks / insn\n", h2_insnGenerated, h2_codeGenTime, h2_codeGenTime/h2_insnGenerated);
#endif
	if (!h2_codeGenerationOK)
	  {
		fprintf (stderr, "(iflush) Failed code generation\n");
		exit(-5);
	  }
}

static h2_insn_t *h2_malloc (size_t size)
{
  return malloc (size);
}


#endif /* H2_AARCH64 */
/* In memory instruction generator */
#define aarch64_G32(INSN){ *(h2_asm_pc++) = (INSN);}

/* Single instruction binary code generator*/
#define A64_RET__I_64_1() do /* ret */ { 	aarch64_G32(((0xd65f03c0 >> 0) & 0xffffffff)); \
 } while(0);
#define A64_LSL_RRI_I_32_1(r0,r1,i0) do /* sl */ { 	aarch64_G32(((0x14c & 0x3ff) << 22)|((((32 - i0)% 32) & 0x3f) << 16)|(((31 - i0) & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LSL_RRR_I_32_1(r0,r1,r2) do /* sl */ { 	aarch64_G32(((0xd6 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x8 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LSL_RRI_I_64_1(r0,r1,i0) do /* sl */ { 	aarch64_G32(((0x34d & 0x3ff) << 22)|((((64 - i0)% 64) & 0x3f) << 16)|(((63 - i0) & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LSL_RRR_I_64_1(r0,r1,r2) do /* sl */ { 	aarch64_G32(((0x4d6 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x8 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MOV_RRR_I_8_8(r0,r1,r2) do /* mv */ { 	aarch64_G32(((0x75 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x7 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MOV_RRR_I_16_8(r0,r1,r2) do /* mv */ { 	aarch64_G32(((0x275 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x7 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MV_RR_I_32_4(r0,r1) do /* mv */ { 	aarch64_G32(((0x275 & 0x7ff) << 21)|((r1 & 0x1f) << 16)|((0x7 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MOV_RR_I_32_1(r0,r1) do /* mv */ { 	aarch64_G32(((0x44000 & 0x3fffff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MOVI_RI_I_32_4(r0,i0) do /* mv */ { 	aarch64_G32(((0x9e0 & 0x1fff) << 19)|(((i0 >> 5) & 0x7) << 16)|((0x1 & 0x3f) << 10)|((i0 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MOVI_RI_I_32_2(r0,i0) do /* mv */ { 	aarch64_G32(((0x1e0 & 0x1fff) << 19)|(((i0 >> 5) & 0x7) << 16)|((0x1 & 0x3f) << 10)|((i0 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_DUP_RR_I_32_4(r0,r1) do /* mv */ { 	aarch64_G32(((0x178101 & 0x3fffff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MOV_RI_I_32_1(r0,i0) do /* mv */ { 	aarch64_G32(((0x294 & 0x7ff) << 21)|((i0 & 0xffff) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MOV_RR_I_32_2(r0,r1) do /* mv */ { 	aarch64_G32(((0x138207 & 0x3fffff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_DUP_RR_I_32_1(r0,r1) do /* mv */ { 	aarch64_G32(((0x178101 & 0x3fffff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_DUP_RR_I_32_2(r0,r1) do /* mv */ { 	aarch64_G32(((0x38101 & 0x3fffff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MOV_RR_I_64_1(r0,r1) do /* mv */ { 	aarch64_G32(((0x244000 & 0x3fffff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MOV_RI_I_64_1(r0,i0) do /* mv */ { 	aarch64_G32(((0x694 & 0x7ff) << 21)|((i0 & 0xffff) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_DUP_RR_I_64_1(r0,r1) do /* mv */ { 	aarch64_G32(((0x178201 & 0x3fffff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_DUP_RR_I_64_2(r0,r1) do /* mv */ { 	aarch64_G32(((0x138201 & 0x3fffff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_SUB_RRR_I_8_8(r0,r1,r2) do /* sub */ { 	aarch64_G32(((0x171 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x21 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_SUB_RRR_I_8_16(r0,r1,r2) do /* sub */ { 	aarch64_G32(((0x371 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x21 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_SUB_RRR_I_16_8(r0,r1,r2) do /* sub */ { 	aarch64_G32(((0x373 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x21 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_SUB_RRR_I_16_4(r0,r1,r2) do /* sub */ { 	aarch64_G32(((0x173 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x21 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_SUB_RRR_I_32_1(r0,r1,r2) do /* sub */ { 	aarch64_G32(((0x258 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x0 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_SUB_RRI_I_32_1(r0,r1,i0) do /* sub */ { 	aarch64_G32(((0x144 & 0x3ff) << 22)|((i0 & 0xfff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_SUB_RRR_I_32_2(r0,r1,r2) do /* sub */ { 	aarch64_G32(((0x175 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x21 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_SUB_RRR_I_32_4(r0,r1,r2) do /* sub */ { 	aarch64_G32(((0x375 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x21 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_SUB_RRR_I_64_2(r0,r1,r2) do /* sub */ { 	aarch64_G32(((0x377 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x21 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_SUB_RRI_I_64_1(r0,r1,i0) do /* sub */ { 	aarch64_G32(((0x344 & 0x3ff) << 22)|((i0 & 0xfff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_SUB_RRR_I_64_1(r0,r1,r2) do /* sub */ { 	aarch64_G32(((0x658 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x0 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_ST1_RR_I_8_8(r0,r1) do /* w */ { 	aarch64_G32(((0x3001c & 0x3fffff) << 10)|((r0 & 0x1f) << 5)|((r1 & 0x1f) >> 0)); } while(0);
#define A64_ST1_RR_I_8_16(r0,r1) do /* w */ { 	aarch64_G32(((0x13001c & 0x3fffff) << 10)|((r0 & 0x1f) << 5)|((r1 & 0x1f) >> 0)); } while(0);
#define A64_STRB_RRI_I_8_1(r0,r1,i0) do /* w */ { 	aarch64_G32(((0x1c0 & 0x7ff) << 21)|((i0 & 0x1ff) << 12)|((0x1 & 0x3) << 10)|((r0 & 0x1f) << 5)|((r1 & 0x1f) >> 0)); } while(0);
#define A64_ST1_RR_I_16_8(r0,r1) do /* w */ { 	aarch64_G32(((0x13001d & 0x3fffff) << 10)|((r0 & 0x1f) << 5)|((r1 & 0x1f) >> 0)); } while(0);
#define A64_ST1_RR_I_16_4(r0,r1) do /* w */ { 	aarch64_G32(((0x3001d & 0x3fffff) << 10)|((r0 & 0x1f) << 5)|((r1 & 0x1f) >> 0)); } while(0);
#define A64_STRH_RRI_I_16_1(r0,r1,i0) do /* w */ { 	aarch64_G32(((0x3c0 & 0x7ff) << 21)|((i0 & 0x1ff) << 12)|((0x1 & 0x3) << 10)|((r0 & 0x1f) << 5)|((r1 & 0x1f) >> 0)); } while(0);
#define A64_STR_RRR_I_32_1(r0,r1,r2) do /* w */ { 	aarch64_G32(((0x5c1 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x36 & 0x3f) << 10)|((r0 & 0x1f) << 5)|((r1 & 0x1f) >> 0)); } while(0);
#define A64_STR_RRI_I_32_1(r0,r1,i0) do /* w */ { 	aarch64_G32(((0x5c0 & 0x7ff) << 21)|((i0 & 0x1ff) << 12)|((0x1 & 0x3) << 10)|((r0 & 0x1f) << 5)|((r1 & 0x1f) >> 0)); } while(0);
#define A64_STR_RRI_I_32_2(r0,r1,i0) do /* w */ { 	aarch64_G32(((0x7e0 & 0x7ff) << 21)|((i0 & 0x1ff) << 12)|((0x0 & 0x3) << 10)|((r0 & 0x1f) << 5)|((r1 & 0x1f) >> 0)); } while(0);
#define A64_ST1_RR_I_32_4(r0,r1) do /* w */ { 	aarch64_G32(((0x13001e & 0x3fffff) << 10)|((r0 & 0x1f) << 5)|((r1 & 0x1f) >> 0)); } while(0);
#define A64_STR_RRR_I_64_1(r0,r1,r2) do /* w */ { 	aarch64_G32(((0x7c1 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x36 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_ST1_RR_I_64_2(r0,r1) do /* w */ { 	aarch64_G32(((0x3001f & 0x3fffff) << 10)|((r0 & 0x1f) << 5)|((r1 & 0x1f) >> 0)); } while(0);
#define A64_STR_RRI_I_64_1(r0,r1,i0) do /* w */ { 	aarch64_G32(((0x7c0 & 0x7ff) << 21)|((i0 & 0x1ff) << 12)|((0x1 & 0x3) << 10)|((r0 & 0x1f) << 5)|((r1 & 0x1f) >> 0)); } while(0);
#define A64_MUL_RRR_I_8_8(r0,r1,r2) do /* mul */ { 	aarch64_G32(((0x71 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x27 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MUL_RRR_I_8_16(r0,r1,r2) do /* mul */ { 	aarch64_G32(((0x271 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x27 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MUL_RRR_I_16_4(r0,r1,r2) do /* mul */ { 	aarch64_G32(((0x73 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x27 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MUL_RRR_I_16_8(r0,r1,r2) do /* mul */ { 	aarch64_G32(((0x273 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x27 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MUL_RRR_I_32_4(r0,r1,r2) do /* mul */ { 	aarch64_G32(((0x275 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x27 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MUL_RRR_I_32_1(r0,r1,r2) do /* mul */ { 	aarch64_G32(((0xd8 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x1f & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MUL_RRR_I_32_2(r0,r1,r2) do /* mul */ { 	aarch64_G32(((0x75 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x27 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_MUL_RRR_I_64_1(r0,r1,r2) do /* mul */ { 	aarch64_G32(((0x4d8 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x1f & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_ADD_RRR_I_8_8(r0,r1,r2) do /* add */ { 	aarch64_G32(((0x71 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x21 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_ADD_RRR_I_8_16(r0,r1,r2) do /* add */ { 	aarch64_G32(((0x271 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x21 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_ADD_RRR_I_16_8(r0,r1,r2) do /* add */ { 	aarch64_G32(((0x273 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x21 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_ADD_RRR_I_16_4(r0,r1,r2) do /* add */ { 	aarch64_G32(((0x73 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x21 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_ADD_RRI_I_32_1(r0,r1,i0) do /* add */ { 	aarch64_G32(((0x44 & 0x3ff) << 22)|((i0 & 0xfff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_ADD_RRR_I_32_1(r0,r1,r2) do /* add */ { 	aarch64_G32(((0x58 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x0 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_ADD_RRR_I_32_2(r0,r1,r2) do /* add */ { 	aarch64_G32(((0x75 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x21 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_ADD_RRR_I_32_4(r0,r1,r2) do /* add */ { 	aarch64_G32(((0x275 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x21 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_ADD_RRR_I_64_2(r0,r1,r2) do /* add */ { 	aarch64_G32(((0x277 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x21 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_ADD_RRR_I_64_1(r0,r1,r2) do /* add */ { 	aarch64_G32(((0x458 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x0 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_ADD_RRI_I_64_1(r0,r1,i0) do /* add */ { 	aarch64_G32(((0x244 & 0x3ff) << 22)|((i0 & 0xfff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LSR_RRI_I_32_1(r0,r1,i0) do /* sr */ { 	aarch64_G32(((0x14c & 0x3ff) << 22)|((i0 & 0x3f) << 16)|((0x1f & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LSR_RRR_I_32_1(r0,r1,r2) do /* sr */ { 	aarch64_G32(((0xd6 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x9 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LSR_RRI_I_64_1(r0,r1,i0) do /* sr */ { 	aarch64_G32(((0x34c & 0x3ff) << 22)|((i0 & 0x3f) << 16)|((0x3f & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LSR_RRR_I_64_1(r0,r1,r2) do /* sr */ { 	aarch64_G32(((0x4d6 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x9 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_FDIV_RRR_I_16_8(r0,r1,r2) do /* div */ { 	aarch64_G32(((0x372 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0xf & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_FDIV_RRR_I_16_4(r0,r1,r2) do /* div */ { 	aarch64_G32(((0x172 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0xf & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_SDIV_RRR_I_32_1(r0,r1,r2) do /* div */ { 	aarch64_G32(((0xd6 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x3 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_FDIV_RRR_I_32_2(r0,r1,r2) do /* div */ { 	aarch64_G32(((0x171 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x3f & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_FDIV_RRR_I_32_4(r0,r1,r2) do /* div */ { 	aarch64_G32(((0x371 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x3f & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_FDIV_RRR_I_64_2(r0,r1,r2) do /* div */ { 	aarch64_G32(((0x373 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x3f & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_SDIV_RRR_I_64_1(r0,r1,r2) do /* div */ { 	aarch64_G32(((0x4d6 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x3 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LD1_RR_I_8_16(r0,r1) do /* r */ { 	aarch64_G32(((0x13101c & 0x3fffff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LDRB_RRI_I_8_1(r0,r1,i0) do /* r */ { 	aarch64_G32(((0xe5 & 0x3ff) << 22)|((i0 & 0xfff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LD1_RR_I_8_8(r0,r1) do /* r */ { 	aarch64_G32(((0x3101c & 0x3fffff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LD1_RR_I_16_4(r0,r1) do /* r */ { 	aarch64_G32(((0x3101d & 0x3fffff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LDRH_RRI_I_16_1(r0,r1,i0) do /* r */ { 	aarch64_G32(((0x1e5 & 0x3ff) << 22)|((i0 & 0xfff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LD1_RR_I_16_8(r0,r1) do /* r */ { 	aarch64_G32(((0x13101d & 0x3fffff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LDR_RRI_I_32_1(r0,r1,i0) do /* r */ { 	aarch64_G32(((0x2e5 & 0x3ff) << 22)|((i0 & 0xfff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LDP_RRI_I_32_2(r0,r1,i0) do /* r */ { 	aarch64_G32(((0xb3 & 0x3ff) << 22)|((i0 & 0x7f) << 15)|((0x0 & 0x1f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LD1_RR_I_32_2(r0,r1) do /* r */ { 	aarch64_G32(((0x3101e & 0x3fffff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LD1_RR_I_32_4(r0,r1) do /* r */ { 	aarch64_G32(((0x13101e & 0x3fffff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LDR_RRR_I_64_1(r0,r1,r2) do /* r */ { 	aarch64_G32(((0x7e3 & 0x7ff) << 21)|((r2 & 0x1f) << 16)|((0x36 & 0x3f) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
#define A64_LD1_RR_I_64_2(r0,r1) do /* r */ { 	aarch64_G32(((0x13101f & 0x3fffff) << 10)|((r1 & 0x1f) << 5)|((r0 & 0x1f) >> 0)); } while(0);
h2_sValue_t aarch64_genMV_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t aarch64_genDIV_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t aarch64_genMUL_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t aarch64_genW_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t aarch64_genSL_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t aarch64_genSUB_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t aarch64_genSR_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t aarch64_genRET_0();
h2_sValue_t aarch64_genR_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t aarch64_genADD_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t aarch64_genMV_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for MV instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for MV

// No specific optimisation for MV/aarch64

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_MV_RR_I_32_4(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_MOV_RR_I_32_1(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2VALUE)
    {
	A64_MOVI_RI_I_32_4(P0.regNro, P1.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2VALUE)
    {
	A64_MOVI_RI_I_32_2(P0.regNro, P1.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_DUP_RR_I_32_4(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2VALUE)
    {
	A64_MOV_RI_I_32_1(P0.regNro, P1.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_MOV_RR_I_32_2(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_DUP_RR_I_32_1(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_DUP_RR_I_32_2(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_MOV_RR_I_64_1(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2VALUE)
    {
	A64_MOV_RI_I_64_1(P0.regNro, P1.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_DUP_RR_I_64_1(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_DUP_RR_I_64_2(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_MOV_RRR_I_8_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_MOV_RRR_I_16_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, MV instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);return immValueZero;
}
h2_sValue_t aarch64_genDIV_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for DIV instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
/* -*- c -*- */
// if 2 operands are constants do division evaluation
if  ((P2.ValOrReg == H2VALUE) && (P1.ValOrReg == H2VALUE) && (P1.arith == 'i')&& (P2.arith == 'i'))
{
  return (h2_sValue_t) {H2VALUE, P1.arith, P1.vLen, P1.wLen, -1, P1.valueImm / P2.valueImm };
}
// Transform RIR in RRI : P1 & P2 permutation
if  ((P1.ValOrReg == H2VALUE) && (P2.ValOrReg == H2REGISTER))
    {
       h2_sValue_t PTMP = P2;
       P2 = P1;
       P1 = PTMP;
    }

/* -*- c -*- */
// X * NPowerOf2 = X >> N (immediate shift left)
if  (isValue(P2) && ((P2.valueImm != 0) && !(P2.valueImm & (P2.valueImm - 1))))
  {
	int shiftValue = h2_log2(P2.valueImm);
    #ifdef H2_DEBUG_INSN
      printf ("Optim for DIV %d (power of 2) -> sr %d (aarch64)\n", P2.valueImm, shiftValue);
    #endif
	P2.valueImm = shiftValue; 	// Instruction shift left immediat
	return aarch64_genSR_3(P0, P1, P2);
  }
if  ((P2.ValOrReg == H2VALUE) && (P2.arith == 'i'))
{
	h2_sValue_t PTMP = {H2REGISTER, P2.arith, P2.vLen, P2.wLen, h2_getReg()};
    #ifdef H2_DEBUG_INSN
      printf ("Fallback for no RRI div (aarch64)\\n");
    #endif
	P2 = aarch64_genMV_3(PTMP,  P2, immValueZero);
}

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_FDIV_RRR_I_16_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_FDIV_RRR_I_16_4(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_SDIV_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_FDIV_RRR_I_32_2(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_FDIV_RRR_I_32_4(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_FDIV_RRR_I_64_2(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_SDIV_RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, DIV instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t aarch64_genMUL_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for MUL instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
/* -*- c -*- */
  // if 2 operands are constants do multiplication evaluation (Thanks Kilian for the bug report)
  if  ((P2.ValOrReg == H2VALUE) && (P1.ValOrReg == H2VALUE) && (P1.arith == 'i')&& (P2.arith == 'i'))
  {
    return (h2_sValue_t) {H2VALUE, P1.arith, P1.vLen, P1.wLen, -1, P1.valueImm * P2.valueImm };
  }
  /* if (isInt0(P2) || isInt0(P1)) */
  /*  {    // X * 0 = 0 Avoid 1 operation mul & 1 mv */
  /*       #ifdef H2_DEBUG_INSN */
  /*       printf ("Optim for *0 P2 (generic)\n"); */
  /*       #endif */
  /*       return immValueZero; */
  /*   } */
  /* if (isInt1(P2)) */
  /*   { // X * 1 = X propagate register result */
  /*       #ifdef H2_DEBUG_INSN */
  /*       printf ("Optim for *1 P2 (generic)\n"); */
  /*       #endif */
  /* 		P1.dontFree = true; */
  /*       return P1; */
  /*   } */
  /* if (isInt1(P1)) */
  /*   { // 1 * X = X propagate register result */
  /*       #ifdef H2_DEBUG_INSN */
  /*       printf ("Optim for *1 P1 (generic)\n"); */
  /*       #endif */
  /* 		P2.dontFree = true; */
  /*       return P2; */
  /*   } */

/* -*- c -*- */
// Transform RIR in RRI : P1 & P2 permutation
if  ((P1.ValOrReg == H2VALUE) && (P2.ValOrReg == H2REGISTER))
    {
       h2_sValue_t PTMP = P2;
       P2 = P1;
       P1 = PTMP;
    }

if (isInt0(P2))
  { //   X * 0 = 0 Avoid 1 operation mul
#ifdef H2_DEBUG_INSN
	printf ("Optim for *0 P2 (aarch64)\n");
#endif
	return 	aarch64_genMV_3(P0, immValueZero, P1);
  }

if (isInt1(P2))
  { //   X * 1 = X Avoid 1 operation mul
#ifdef H2_DEBUG_INSN
	printf ("Optim for *1 P2 (aarch64)\n");
#endif
	return 	aarch64_genMV_3(P0, P1, P1);
  }

if (isInt1(P1))
  { //   X * 1 = X Avoid 1 operation mul
#ifdef H2_DEBUG_INSN
	printf ("Optim for *1 P1 (aarch64)\n");
#endif
	return 	aarch64_genMV_3(P0, P2, P2);
  }

if  (isValue(P2) && ((P2.valueImm != 0) && !(P2.valueImm & (P2.valueImm - 1))))
  {
	int shiftValue = h2_log2(P2.valueImm);
    #ifdef H2_DEBUG_INSN
      printf ("Optim for MUL %d (power of 2) -> sl %d (aarch64)\n", P2.valueImm, shiftValue);
    #endif
	P2.valueImm = shiftValue; 	// Instruction shift left immediat
	return aarch64_genSL_3(P0, P1, P2);
  }

// Mv constant value in register, then do division
if  ((P2.ValOrReg == H2VALUE) && (P2.arith == 'i'))
{
	h2_sValue_t PTMP = {H2REGISTER, P2.arith, P2.vLen, P2.wLen, h2_getReg()};
    #ifdef H2_DEBUG_INSN
      printf ("Fallback for no RRI mul (aarch64)\n");
    #endif
	P2 = aarch64_genMV_3(PTMP,  P2, immValueZero);
	// No return continue instruction selection
}

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_MUL_RRR_I_8_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 16) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_MUL_RRR_I_8_16(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_MUL_RRR_I_16_4(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_MUL_RRR_I_16_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_MUL_RRR_I_32_4(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_MUL_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_MUL_RRR_I_32_2(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_MUL_RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, MUL instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t aarch64_genW_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for W instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for W

/* -*- c -*- */

/* if (isInt32_1(P0) && isInt0(P1)  && isInt0(P2) ) */
/*   {  */
/*     #ifdef H2_DEBUG_INSN */
/*     // Store const 0 in memory (alias store, r31 interpreted as 0) */
/*     printf ("Store 0 (aarch64)\\n"); */
/*     #endif */
/*     A64_STR_RRI_I_32_1(P0.regNro, 31, 0); */
/*     return P0; */
/*   } */

if (isValue(P1))
  { // Store constant (Should use RRI variant)
	h2_sValue_t PTMP = {H2REGISTER, P1.arith, P1.vLen, P1.wLen, h2_getReg()};
    #ifdef H2_DEBUG_INSN
      printf ("Fallback for no RI W (aarch64)\n");
    #endif
	// MV const in tmp register
	P1 = aarch64_genMV_3(PTMP,  P1, immValueZero);
	// No return continue instruction selection
  }

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P1.arith == 'i') && (P1.wLen <= 8) && (P1.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_ST1_RR_I_8_8(P0.regNro, P1.regNro);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 8) && (P1.vLen == 16) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_ST1_RR_I_8_16(P0.regNro, P1.regNro);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 16) && (P1.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_ST1_RR_I_16_8(P0.regNro, P1.regNro);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 16) && (P1.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_ST1_RR_I_16_4(P0.regNro, P1.regNro);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 32) && (P1.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_ST1_RR_I_32_4(P0.regNro, P1.regNro);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 64) && (P1.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_ST1_RR_I_64_2(P0.regNro, P1.regNro);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 8) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_STRB_RRI_I_8_1(P0.regNro, P1.regNro, P2.valueImm);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 16) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_STRH_RRI_I_16_1(P0.regNro, P1.regNro, P2.valueImm);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 32) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_STR_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 32) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_STR_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 32) && (P1.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_STR_RRI_I_32_2(P0.regNro, P1.regNro, P2.valueImm);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 64) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_STR_RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 64) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_STR_RRI_I_64_1(P0.regNro, P1.regNro, P2.valueImm);
	return P1;
    }
	printf ("Warning, W instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);return immValueZero;
}
h2_sValue_t aarch64_genSL_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for SL instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for SL

// No specific optimisation for SL/aarch64

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_LSL_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_LSL_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_LSL_RRI_I_64_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_LSL_RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, SL instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t aarch64_genSUB_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for SUB instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
/* -*- c -*- */
// if 2 operands are constants do substraction evaluation (Thanks Kilian for the bug report)
if  ((P2.ValOrReg == H2VALUE) && (P1.ValOrReg == H2VALUE) && (P1.arith == 'i')&& (P2.arith == 'i'))
{
  return (h2_sValue_t) {H2VALUE, P1.arith, P1.vLen, P1.wLen, -1, P1.valueImm - P2.valueImm };
}

// No specific optimisation for SUB/aarch64

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_SUB_RRR_I_8_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 16) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_SUB_RRR_I_8_16(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_SUB_RRR_I_16_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_SUB_RRR_I_16_4(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_SUB_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_SUB_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_SUB_RRR_I_32_2(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_SUB_RRR_I_32_4(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_SUB_RRR_I_64_2(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_SUB_RRI_I_64_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_SUB_RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, SUB instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t aarch64_genSR_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for SR instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for SR

// No specific optimisation for SR/aarch64

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_LSR_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_LSR_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_LSR_RRI_I_64_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_LSR_RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, SR instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t aarch64_genRET_0()
{
// No generic optimisation for RET

// No specific optimisation for RET/aarch64

A64_RET__I_64_1();
	
}
h2_sValue_t aarch64_genR_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for R instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for R

// No specific optimisation for R/aarch64

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 16) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_LD1_RR_I_8_16(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_LD1_RR_I_8_8(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_LD1_RR_I_16_4(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_LD1_RR_I_16_8(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_LD1_RR_I_32_2(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_LD1_RR_I_32_4(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	A64_LD1_RR_I_64_2(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_LDRB_RRI_I_8_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_LDRH_RRI_I_16_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_LDR_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_LDP_RRI_I_32_2(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_LDR_RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, R instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);return immValueZero;
}
h2_sValue_t aarch64_genADD_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for ADD instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
/* -*- c -*- */
// If 2 operands are constants do addition
if  ((P2.ValOrReg == H2VALUE) && (P1.ValOrReg == H2VALUE) && (P1.arith == 'i')&& (P2.arith == 'i'))
{
  return sValueDef(H2VALUE, P1.arith, P1.vLen, P1.wLen, -1, P1.valueImm + P2.valueImm );
}
if (isInt0 (P2))
  { // P0 = P1 + 0
    #ifdef H2_DEBUG_INSN
	printf ("Optim add for 0 (generic) return reg %d\n", P1.regNro);
    #endif
	P1.dontFree = true;
	return P1;
  }
if (isInt0 (P1))
  { // P0 = 0 + P2
    #ifdef H2_DEBUG_INSN
    printf ("Optim add for 0  (generic) return reg %d\n", P2.regNro);
    #endif
	P2.dontFree = true;
    return P2;
  }

// No specific optimisation for ADD/aarch64

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_ADD_RRR_I_8_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 16) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_ADD_RRR_I_8_16(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_ADD_RRR_I_16_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_ADD_RRR_I_16_4(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_ADD_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_ADD_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_ADD_RRR_I_32_2(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_ADD_RRR_I_32_4(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_ADD_RRR_I_64_2(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	A64_ADD_RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	A64_ADD_RRI_I_64_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }
	printf ("Warning, ADD instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}

/* End Header autogenerated part */
// -*- c -*-
#include <stdio.h>
#include <stdlib.h>

typedef  int (*pifi)(int);

h2_insn_t * genC2F(h2_insn_t * ptr)
{
	/* Code Generation of 3 instructions */
	/* Symbol table :*/
	/*VarName = {ValOrLen, arith, vectorLen, wordLen, regNo, ValueImm, dontFree} */
	h2_sValue_t a = {H2REGISTER, 'i', 1, 32, 0, true};
	h2_sValue_t h2_outputVarName = {H2REGISTER, 'i', 1, 32, 0, true};
	h2_sValue_t r = {H2REGISTER, 'i', 1, 32, 9, true};
	h2_sValue_t tmp0000 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0001 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0002 = {H2REGISTER, 'i', 1, 32, -1, false};

	/* Label  table :*/
/* No label table to avoid C warning for empty table ... */
	h2_asm_pc = (h2_insn_t *) ptr;
	h2_codeGenerationOK = true;
	h2_codeGenTime = h2_getticks();
	h2_initRegisterMasks(0xFFFF0301, 0, 0, 0);
	h2_resetRegisterMasks();
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask initialization\n");
	#endif // H2_DEBUG_REGISTER
	
				tmp0000 = aarch64_genMUL_3(tmp0000, a, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(9)});
			tmp0001 = aarch64_genDIV_3(tmp0001, tmp0000, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(5)});
		if (!tmp0001.dontFree) h2_freeReg(tmp0000.regNro);
		r = aarch64_genADD_3(r, tmp0001, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(32)});
	if (!r.dontFree) h2_freeReg(tmp0001.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		h2_outputVarName = aarch64_genMV_3(h2_outputVarName, r, immValueZero);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	aarch64_genRET_0();
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	/* Call back code for loops */
	h2_save_asm_pc = h2_asm_pc;
	h2_asm_pc = h2_save_asm_pc;
	h2_codeGenTime = h2_getticks() - h2_codeGenTime;
	h2_iflush(ptr, h2_asm_pc);

  return (h2_insn_t *) ptr;
}

h2_insn_t * genF2C(h2_insn_t * ptr)
{
	/* Code Generation of 4 instructions */
	/* Symbol table :*/
	/*VarName = {ValOrLen, arith, vectorLen, wordLen, regNo, ValueImm, dontFree} */
	h2_sValue_t a = {H2REGISTER, 'i', 1, 32, 0, true};
	h2_sValue_t h2_outputVarName = {H2REGISTER, 'i', 1, 32, 0, true};
	h2_sValue_t r = {H2REGISTER, 'i', 1, 32, 9, true};
	h2_sValue_t tmp0000 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0001 = {H2REGISTER, 'i', 1, 32, -1, false};

	/* Label  table :*/
/* No label table to avoid C warning for empty table ... */
	h2_asm_pc = (h2_insn_t *) ptr;
	h2_codeGenerationOK = true;
	h2_codeGenTime = h2_getticks();
	h2_initRegisterMasks(0xFFFF0301, 0, 0, 0);
	h2_resetRegisterMasks();
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask initialization\n");
	#endif // H2_DEBUG_REGISTER
	
		r = aarch64_genSUB_3(r, a, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(32)});
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
			tmp0000 = aarch64_genMUL_3(tmp0000, r, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(5)});
		r = aarch64_genDIV_3(r, tmp0000, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(9)});
	if (!r.dontFree) h2_freeReg(tmp0000.regNro);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		h2_outputVarName = aarch64_genMV_3(h2_outputVarName, r, immValueZero);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	aarch64_genRET_0();
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	/* Call back code for loops */
	h2_save_asm_pc = h2_asm_pc;
	h2_asm_pc = h2_save_asm_pc;
	h2_codeGenTime = h2_getticks() - h2_codeGenTime;
	h2_iflush(ptr, h2_asm_pc);

  return (h2_insn_t *) ptr;
}


int main(int argc, char * argv[])
{
  h2_insn_t * ptr;
  int in0, res, resultOK;
  pifi fC2F, fF2C;

  resultOK = 0;
  if (argc < 2)
    {
      printf("Give 1 values\n");
      exit(-1);
    }
  in0  = atoi (argv[1]);   // Get the users values in0
  printf("// Compilette for conversion from celcius to farenheit\n");
  ptr  = h2_malloc (1024);  // Allocate memory for 1024 instructions
  fC2F = (pifi) genC2F (ptr); //
  res  = fC2F(in0);  // Call generated code
  printf("%d (celcius)   -> (farenheit)%d\n", in0, res);
  if (res != (in0 * 9 / 5 + 32))
	resultOK += 1;
  printf("// Compilette for conversion from farenheit to celcius\n");
  ptr  = h2_malloc (1024);  // Allocate memory for 1024 instructions
  fF2C = (pifi) genF2C (ptr); //
  res  = fF2C(in0);  // Call generated code
  printf("%d (farenheit)   -> (celcius)%d\n", in0, res);
  if (res != ((in0 - 32) * 5 / 9))
	resultOK += 1;

  if (resultOK == 0)
	return 0;
  else
	return -1;
}
