/* Begin Header autogenerated part */
#ifndef H2_COMMON
#define H2_COMMON
/* Common HybroGen inserted code */
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdbool.h>
#include <stdint.h>

bool h2_codeGenerationOK;	 // Does code generation fail ?
typedef int32_t h2_regSet_t; // Register set (signed, use -1 when not allocated)
static  uint32_t h2_insnGenerated;
typedef unsigned long long ticks_t;
static  ticks_t h2_codeGenTime;

typedef enum { H2REGISTER,    H2VALUE, } VALORREG;
typedef struct
{
  int ValOrReg; // is H2REGISTER or immediate VALUE ?
  char arith;   // int, flt or other arithmetic
  int vLen;     // vector len
  int wLen;     // word len
  int regNro;   // register number (if register)
  int valueImm; // immediate value (if not register)
  bool dontFree; // if register, don't free
} h2_sValue_t;
#define sValueDef(VALUE, ARITH, VECTORLEN, WORDLEN, REGNO, IMMVAL) ((h2_sValue_t){.ValOrReg = VALUE, .arith = ARITH, .vLen = VECTORLEN, .wLen = WORDLEN, .regNro = REGNO, .valueImm = IMMVAL})
#define intsValue(V)      sValueDef(H2VALUE, 'i', 1, 32, -1, V)
#define intReg32sValue(R) sValueDef(H2REGISTER, 'i', 1, 32, R, 0)
#define immValueZero intsValue(0)
// Usefull macro instruction to simplify instruction selector code
#define isInt64_1(P)  ((P.arith == 'i') && (P.wLen <= 64) && (P.vLen == 1))
#define isInt32_1(P)  ((P.arith == 'i') && (P.wLen <= 32) && (P.vLen == 1))
#define isInt0(P)     ((P.arith == 'i') && (P.ValOrReg == H2VALUE) && (0 == P.valueImm))
#define isInt1(P)     ((P.arith == 'i') && (P.ValOrReg == H2VALUE) && (1 == P.valueImm))
#define isValue(P)    ((P.arith == 'i') && (P.ValOrReg == H2VALUE))
#define isReg32(P, X) ((P.arith == 'i') && (P.ValOrReg == H2REGISTER) && (X == P.regNro))
#define isRRR(P0, P1, P2) (P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
#define isRRV(P0, P1, P2) (P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)


typedef union {
    float f;
    unsigned long i;
} h2_float_int_u;

static int h2_log2(int value)
{ // integer logarithm
  int log = 0;
  while (value >>= 1) { ++log; }
  return log;
}
// Print register map : F for free register, . for allocated
void printRev (int value, int pos)
{ // Print a bitset in reversal order (recursive)
  if (pos != 0)
	printRev (value >> 1, pos - 1);
  printf ("%1c", (value % 2)?'.':'F');
}

// Dynamic register allocation handling
// h2_regSet mask : 0 mean free register, 1 register set
//  3           2            1  Bit position = reg Number
// 1098 7654 3210 9876 5432 1098 7654 3210
// 1111 1111 1111 1111 0000 0001 0011 1111
typedef struct
{	// Register allocation sets for
  	// int, float, vector of ints, vector of floats
  int intSet, fltSet, vintSet, vfltSet ;
} h2_RegSets_t;

h2_RegSets_t h2_regSet, h2_regSetInit;

// Print integer register set
void printRegState(char * msg, int regNo, int registerSet)
{
  int count = 8 * sizeof (registerSet) - 1;
  h2_regSet_t tmpReg = registerSet;
  printf ("%02d : Reg %s\n", regNo, msg);
  for (int i = count; i >= 0; i--) // Tens
	(0 == (i % 10))?printf ("%d", i/10):printf (" ");
  printf ("\n");
  for (int i = count; i >= 0; i--) // Unit
	  printf ("%d", i%10);
  printf ("\n");
  printRev (tmpReg, count); // Bit set
  printf ("\n");
}

// Initialize registers sets allocation
static void h2_initRegisterMasks(int intmask, int fltmask, int vectorintmask, int vectorfltmask)
{ // See H2SymbolTable & H2RegisterBank
  h2_regSetInit  = (h2_RegSets_t){intmask, fltmask, vectorintmask, vectorfltmask};
}

static void h2_resetRegisterMasks() // Reset register set from initializers
{
  h2_regSet = h2_regSetInit;
#ifdef H2_DEBUG_REGISTER
  printRegState("RESET", -1, h2_regSet.intSet);
#endif // H2_DEBUG_REGISTER
}
int h2_getReg () // Get new register
{
  /* Search for the 1st free register */
  h2_regSet_t tmpReg = h2_regSet.intSet;
  for (int i = 0; i < 8 * sizeof (h2_regSet.intSet); i++)
	{
	  if (tmpReg % 2 == 0)
		{						/* Free register found */
		  h2_regSet.intSet = h2_regSet.intSet | (1 << i); /* Update regSet */
#ifdef H2_DEBUG_REGISTER
		  printRegState("GET", i, h2_regSet.intSet);
#endif // H2_DEBUG_REGISTER
		  return i;
		}
	  tmpReg >>= 1;
	}
  printf ("Register allocation failed\n");
  h2_codeGenerationOK = false;
  return -1;
}

// h2_regSet_t regToBeFreed[32];

void h2_freeReg (h2_regSet_t v) // Free a register
{
#if 1 // TODO : To be rethinked
      // Is the register freeable ?
  int isOK = (h2_regSetInit.intSet >> v) & 1;
  if (0 == isOK)
    {
	h2_regSet.intSet = h2_regSet.intSet & ~(1 << v); /* Update regSet */
#ifdef H2_DEBUG_REGISTER
    printRegState("FREE", v, h2_regSet.intSet);
#endif // H2_DEBUG_REGISTER
    }
#endif
}
#endif /*H2_COMMON*/
#ifndef H2_POWER
#define H2_POWER

#define H2SYS 					/* Has  operating system */

#include <stdint.h>
#ifdef H2SYS
#include <sys/mman.h>
#endif

/* aarch64 / power examples :
   https://github.com/FFTW/fftw3/blob/master/kernel/cycle.h */

typedef uint32_t      h2_insn_t;
static  h2_insn_t     *h2_asm_pc;
static  h2_insn_t     *h2_save_asm_pc;

static ticks_t h2_getticks(void)
{
     unsigned int tbl, tbu0, tbu1;

     do {
	  __asm__ __volatile__ ("mftbu %0" : "=r"(tbu0));
	  __asm__ __volatile__ ("mftb %0" : "=r"(tbl));
	  __asm__ __volatile__ ("mftbu %0" : "=r"(tbu1));
     } while (tbu0 != tbu1);

     return (((unsigned long long)tbu0) << 32) | tbl;
}

static void h2_iflush(void *addr, void *last)
{
	h2_insnGenerated = (last-addr)/sizeof (h2_insn_t);
#ifdef H2SYS
    long pageSize= getpagesize();
    void *ptmp= (char *)((long)addr & ~(pageSize - 1));
    if (mprotect(ptmp, (last - addr), PROT_READ | PROT_WRITE | PROT_EXEC))
    {
        perror("iflush: mprotect");
        exit(-1);
    }
#endif
#ifdef H2_DEBUG
    printf ("Flush data cache from %p to %p\n", addr, last);
	printf ("%ld insn generated in %ld ticks. %ld ticks / insn\n", h2_insnGenerated, h2_codeGenTime, h2_codeGenTime/h2_insnGenerated);
#endif
	if (!h2_codeGenerationOK)
	  {
		fprintf (stderr, "(iflush) Failed code generation\n");
		exit(-5);
	  }
}

static h2_insn_t *h2_malloc (size_t size)
{
  return malloc (size);
}

#endif /*H2_POWER*/
/* In memory instruction generator */
#define power_G32(INSN){ *(h2_asm_pc++) = (INSN);}

/* Single instruction binary code generator*/
#define P1_BLR__I_32_1() do /* ret */ { 	power_G32(((0x4e800020 >> 0) & 0xffffffff)); \
 } while(0);
#define P1_SUBI_RRI_I_32_1(r0,r1,i0) do /* sub */ { 	power_G32(((0xe & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|(((-i0) & 0xffff) >> 0)); } while(0);
#define PPC_SUB_RRR_I_32_1(r0,r2,r1) do /* sub */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x50 & 0x7ff) >> 0)); } while(0);
#define P1_CMPW_RR_I_32_1(r0,r1) do /* cmp */ { 	power_G32(((0x3e0 & 0x7ff) << 21)|((r0 & 0x1f) << 16)|((r1 & 0x1f) << 11)|((0x0 & 0x7ff) >> 0)); } while(0);
#define P1_CMPWI_RI_I_32_1(r0,i1) do /* cmp */ { 	power_G32(((0x160 & 0x7ff) << 21)|((r0 & 0x1f) << 16)|((i1 & 0xffff) >> 0)); } while(0);
#define P1_CMPD_RR_I_64_1(r0,r1) do /* cmp */ { 	power_G32(((0x3e1 & 0x7ff) << 21)|((r0 & 0x1f) << 16)|((r1 & 0x1f) << 11)|((0x0 & 0x7ff) >> 0)); } while(0);
#define P1_CMPDI_RI_I_64_1(r0,i1) do /* cmp */ { 	power_G32(((0x161 & 0x7ff) << 21)|((r0 & 0x1f) << 16)|((i1 & 0xffff) >> 0)); } while(0);
#define V2_03_VSRB_RRR_I_8_16(r0,r1,r2) do /* sr */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x204 & 0x7ff) >> 0)); } while(0);
#define V2_03_VSRH_RRR_I_16_8(r0,r1,r2) do /* sr */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x244 & 0x7ff) >> 0)); } while(0);
#define V2_03_VSRW_RRR_I_32_4(r0,r1,r2) do /* sr */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x284 & 0x7ff) >> 0)); } while(0);
#define V2_07_VSRD_RRR_I_64_2(r0,r1,r2) do /* sr */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x6c4 & 0x7ff) >> 0)); } while(0);
#define V2_03_VSR_RRR_I_128_1(r0,r1,r2) do /* sr */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x2c4 & 0x7ff) >> 0)); } while(0);
#define V2_03_VADDSBS_RRR_I_8_16(r0,r1,r2) do /* add */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x300 & 0x7ff) >> 0)); } while(0);
#define V2_03_VADDUBS_RRR_I_8_16(r0,r1,r2) do /* add */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x200 & 0x7ff) >> 0)); } while(0);
#define V2_03_VADDSHS_RRR_I_16_8(r0,r1,r2) do /* add */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x340 & 0x7ff) >> 0)); } while(0);
#define V2_03_VADDUHS_RRR_I_16_8(r0,r1,r2) do /* add */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x240 & 0x7ff) >> 0)); } while(0);
#define V2_03_VADDUWS_RRR_I_32_4(r0,r1,r2) do /* add */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x280 & 0x7ff) >> 0)); } while(0);
#define P1_ADDI_RRI_I_32_1(r0,r1,i0) do /* add */ { 	power_G32(((0xe & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define V2_03_VADDSWS_RRR_I_32_4(r0,r1,r2) do /* add */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x380 & 0x7ff) >> 0)); } while(0);
#define P1_ADD_RRR_I_32_1(r0,r1,r2) do /* add */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x214 & 0x7ff) >> 0)); } while(0);
#define P1_ADD_RRR_I_64_1(r0,r1,r2) do /* add */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x214 & 0x7ff) >> 0)); } while(0);
#define P1_ADDI_RRI_I_64_1(r0,r1,i0) do /* add */ { 	power_G32(((0xe & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_LI_RI_I_32_1(r0,i0) do /* mv */ { 	power_G32(((0xe & 0x3f) << 26)|((r0 & 0x1f) << 21)|((0x0 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_MV_RR_I_32_1(r0,r1) do /* mv */ { 	power_G32(((0xe & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((0x0 & 0xffff) >> 0)); } while(0);
#define P1_LI_RI_I_64_1(r0,i0) do /* mv */ { 	power_G32(((0xe & 0x3f) << 26)|((r0 & 0x1f) << 21)|((0x0 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_BGE_I_I_32_1(i0) do /* bge */ { 	power_G32(((0x4080 & 0xffff) << 16)|((i0 & 0x3fff) << 2)|((0x0 & 0x3) >> 0)); } while(0);
#define P1_STB_RRI_I_8_1(r1,r0,i0) do /* w */ { 	power_G32(((0x26 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_STBX_RRR_I_8_1(r1,r0,r2) do /* w */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x1ae & 0x7ff) >> 0)); } while(0);
#define P1_STH_RRI_I_16_1(r1,r0,i0) do /* w */ { 	power_G32(((0x2c & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_STW_RRI_I_32_1(r1,r0,i0) do /* w */ { 	power_G32(((0x24 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_STWX_RRR_I_32_1(r0,r1,r2) do /* w */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x12e & 0x7ff) >> 0)); } while(0);
#define PPC_STD_RRI_I_64_1(r1,r0,i0) do /* w */ { 	power_G32(((0x3e & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0x3fff) << 2)|((0x0 & 0x3) >> 0)); } while(0);
#define P1_BL_I_I_32_1(i0) do /* ba */ { 	power_G32(((0x12 & 0x3f) << 26)|((i0 & 0xffffff) << 2)|((0x0 & 0x3) >> 0)); } while(0);
#define V2_03_VSLB_RRR_I_8_16(r0,r1,r2) do /* sl */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x104 & 0x7ff) >> 0)); } while(0);
#define V2_03_VSLH_RRR_I_16_8(r0,r1,r2) do /* sl */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x144 & 0x7ff) >> 0)); } while(0);
#define P1_SLW_RRR_I_32_1(r1,r0,r2) do /* sl */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x30 & 0x7ff) >> 0)); } while(0);
#define P1_SLW__RRR_I_32_1(r1,r0,r2) do /* sl */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x31 & 0x7ff) >> 0)); } while(0);
#define V2_03_VSLW_RRR_I_32_4(r0,r1,r2) do /* sl */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x184 & 0x7ff) >> 0)); } while(0);
#define PPC_SLD_RRR_I_64_1(r1,r0,r2) do /* sl */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x36 & 0x7ff) >> 0)); } while(0);
#define PPC_SLD__RRR_I_64_1(r1,r0,r2) do /* sl */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x37 & 0x7ff) >> 0)); } while(0);
#define V2_07_VSLD_RRR_I_64_2(r0,r1,r2) do /* sl */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x5c4 & 0x7ff) >> 0)); } while(0);
#define V2_03_VSL_RRR_I_128_1(r0,r1,r2) do /* sl */ { 	power_G32(((0x4 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x1c4 & 0x7ff) >> 0)); } while(0);
#define P1_LBZ_RRI_I_8_1(r0,r1,i0) do /* r */ { 	power_G32(((0x22 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_LBZX_RRR_I_8_1(r0,r1,r2) do /* r */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0xae & 0x7ff) >> 0)); } while(0);
#define P1_LHZ_RRI_I_16_1(r0,r1,i0) do /* r */ { 	power_G32(((0x28 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_LWZ_RRI_I_32_1(r0,r1,i0) do /* r */ { 	power_G32(((0x20 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_LWZU_RRI_I_32_1(r0,r1,i0) do /* r */ { 	power_G32(((0x21 & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((i0 & 0xffff) >> 0)); } while(0);
#define P1_LWZUX_RRR_I_32_1(r0,r1,r2) do /* r */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x6e & 0x7ff) >> 0)); } while(0);
#define P1_LWZX_RRR_I_32_1(r0,r1,r2) do /* r */ { 	power_G32(((0x1f & 0x3f) << 26)|((r0 & 0x1f) << 21)|((r1 & 0x1f) << 16)|((r2 & 0x1f) << 11)|((0x2e & 0x7ff) >> 0)); } while(0);
h2_sValue_t power_genCMP_2(h2_sValue_t P0,h2_sValue_t P1);
h2_sValue_t power_genSL_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t power_genSR_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t power_genSUB_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t power_genBA_1(h2_sValue_t P0);
h2_sValue_t power_genBGE_1(h2_sValue_t P0);
h2_sValue_t power_genMV_2(h2_sValue_t P0,h2_sValue_t P1);
h2_sValue_t power_genR_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t power_genRET_0();
h2_sValue_t power_genADD_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t power_genW_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t power_genCMP_2(h2_sValue_t P0,h2_sValue_t P1)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for CMP instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for CMP

// No specific optimisation for CMP/power

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	P1_CMPW_RR_I_32_1(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2VALUE)
    {
	P1_CMPWI_RI_I_32_1(P0.regNro, P1.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	P1_CMPD_RR_I_64_1(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2VALUE)
    {
	P1_CMPDI_RI_I_64_1(P0.regNro, P1.valueImm);
	return P0;
    }
	printf ("Warning, CMP instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);return immValueZero;
}
h2_sValue_t power_genSL_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for SL instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for SL

// No specific optimisation for SL/power

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 16) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VSLB_RRR_I_8_16(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VSLH_RRR_I_16_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_SLW_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_SLW__RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VSLW_RRR_I_32_4(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	PPC_SLD_RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	PPC_SLD__RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_07_VSLD_RRR_I_64_2(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 128) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VSL_RRR_I_128_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, SL instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t power_genSR_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for SR instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for SR

// No specific optimisation for SR/power

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 16) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VSRB_RRR_I_8_16(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VSRH_RRR_I_16_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VSRW_RRR_I_32_4(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 2) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_07_VSRD_RRR_I_64_2(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 128) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VSR_RRR_I_128_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, SR instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t power_genSUB_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for SUB instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
/* -*- c -*- */
// if 2 operands are constants do substraction evaluation (Thanks Kilian for the bug report)
if  ((P2.ValOrReg == H2VALUE) && (P1.ValOrReg == H2VALUE) && (P1.arith == 'i')&& (P2.arith == 'i'))
{
  return (h2_sValue_t) {H2VALUE, P1.arith, P1.vLen, P1.wLen, -1, P1.valueImm - P2.valueImm };
}

// No specific optimisation for SUB/power

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_SUBI_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	PPC_SUB_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, SUB instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t power_genBA_1(h2_sValue_t P0)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for BA instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for BA

// No specific optimisation for BA/power

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2VALUE)
    {
	P1_BL_I_I_32_1(P0.valueImm);
	return P0;
    }
	printf ("Warning, BA instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);return immValueZero;
}
h2_sValue_t power_genBGE_1(h2_sValue_t P0)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for BGE instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for BGE

// No specific optimisation for BGE/power

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2VALUE)
    {
	P1_BGE_I_I_32_1(P0.valueImm);
	return P0;
    }
	printf ("Warning, BGE instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);return immValueZero;
}
h2_sValue_t power_genMV_2(h2_sValue_t P0,h2_sValue_t P1)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for MV instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for MV

// No specific optimisation for MV/power

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2VALUE)
    {
	P1_LI_RI_I_32_1(P0.regNro, P1.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	P1_MV_RR_I_32_1(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2VALUE)
    {
	P1_LI_RI_I_64_1(P0.regNro, P1.valueImm);
	return P0;
    }
	printf ("Warning, MV instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);return immValueZero;
}
h2_sValue_t power_genR_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for R instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for R

// No specific optimisation for R/power

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_LBZ_RRI_I_8_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_LBZX_RRR_I_8_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_LHZ_RRI_I_16_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_LWZ_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_LWZU_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_LWZUX_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_LWZX_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, R instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t power_genRET_0()
{
// No generic optimisation for RET

// No specific optimisation for RET/power

P1_BLR__I_32_1();
	
}
h2_sValue_t power_genADD_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for ADD instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
/* -*- c -*- */
// If 2 operands are constants do addition
if  ((P2.ValOrReg == H2VALUE) && (P1.ValOrReg == H2VALUE) && (P1.arith == 'i')&& (P2.arith == 'i'))
{
  return sValueDef(H2VALUE, P1.arith, P1.vLen, P1.wLen, -1, P1.valueImm + P2.valueImm );
}
if (isInt0 (P2))
  { // P0 = P1 + 0
    #ifdef H2_DEBUG_INSN
	printf ("Optim add for 0 (generic) return reg %d\n", P1.regNro);
    #endif
	P1.dontFree = true;
	return P1;
  }
if (isInt0 (P1))
  { // P0 = 0 + P2
    #ifdef H2_DEBUG_INSN
    printf ("Optim add for 0  (generic) return reg %d\n", P2.regNro);
    #endif
	P2.dontFree = true;
    return P2;
  }

// No specific optimisation for ADD/power

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 16) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VADDSBS_RRR_I_8_16(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 16) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VADDUBS_RRR_I_8_16(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VADDSHS_RRR_I_16_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 8) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VADDUHS_RRR_I_16_8(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VADDUWS_RRR_I_32_4(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_ADDI_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 4) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	V2_03_VADDSWS_RRR_I_32_4(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_ADD_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_ADD_RRR_I_64_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 64) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_ADDI_RRI_I_64_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }
	printf ("Warning, ADD instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t power_genW_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for W instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for W

/* -*- c -*- */
if (isValue(P1))
  { // Store constant (Should use RRI variant)
	h2_sValue_t PTMP = {H2REGISTER, P1.arith, P1.vLen, P1.wLen, h2_getReg()};
    #ifdef H2_DEBUG_INSN
      printf ("Fallback for no RI W (power)\\n");
    #endif
	// MV const in tmp register
	P1 = power_genMV_2(PTMP,  P1);
	// No return continue instruction selection
  }

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P1.arith == 'i') && (P1.wLen <= 8) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_STB_RRI_I_8_1(P0.regNro, P1.regNro, P2.valueImm);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 8) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_STBX_RRR_I_8_1(P0.regNro, P1.regNro, P2.regNro);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 16) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_STH_RRI_I_16_1(P0.regNro, P1.regNro, P2.valueImm);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 32) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	P1_STW_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 32) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	P1_STWX_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 64) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	PPC_STD_RRI_I_64_1(P0.regNro, P1.regNro, P2.valueImm);
	return P1;
    }
	printf ("Warning, W instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}

/* End Header autogenerated part */
// -*- c -*-
#include <stdio.h>
#include <stdlib.h>

typedef  int (*pifii)(int, int);

h2_insn_t * genMul(h2_insn_t * ptr) /* C compilette prototype */
{
	/* Code Generation of 13 instructions */
	/* Symbol table :*/
	/*VarName = {ValOrLen, arith, vectorLen, wordLen, regNo, ValueImm, dontFree} */
	h2_sValue_t increment = {H2REGISTER, 'i', 1, 32, 3, true};
	h2_sValue_t len = {H2REGISTER, 'i', 1, 32, 4, true};
	h2_sValue_t h2_outputVarName = {H2REGISTER, 'i', 1, 32, 3, true};
	h2_sValue_t res = {H2REGISTER, 'i', 1, 32, 14, true};
	h2_sValue_t i = {H2REGISTER, 'i', 1, 32, 15, true};
	h2_sValue_t j = {H2REGISTER, 'i', 1, 32, 16, true};
	h2_sValue_t k = {H2REGISTER, 'i', 1, 32, 17, true};
	h2_sValue_t tmp0000 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0001 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0002 = {H2REGISTER, 'i', 1, 32, -1, false};

	/* Label  table :*/
#define power_genLABEL_1(LABEL_ID) labelAddresses[LABEL_ID] = h2_asm_pc;
h2_insn_t   * labelAddresses []={
	0, /* h2_prologue_00000000 */
	#define h2_prologue_00000000 0
	0, /* h2_begin_00000001 */
	#define h2_begin_00000001 1
	0, /* h2_end_00000002 */
	#define h2_end_00000002 2
	0, /* h2_BA_00000003 */
	#define h2_BA_00000003 3
	};

	h2_asm_pc = (h2_insn_t *) ptr;
	h2_codeGenerationOK = true;
	h2_codeGenTime = h2_getticks();
	h2_initRegisterMasks(0x3F81F, 0, 0, 0);
	h2_resetRegisterMasks();
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask initialization\n");
	#endif // H2_DEBUG_REGISTER
	
		res = power_genMV_2(res, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(0)});
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	power_genLABEL_1(h2_prologue_00000000);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		i = power_genMV_2(i, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(0)});
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	power_genLABEL_1(h2_begin_00000001);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		i = power_genCMP_2(i, len);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	power_genBGE_1(intsValue((labelAddresses [h2_end_00000002] - h2_asm_pc)));
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		res = power_genADD_3(res, res, increment);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		i = power_genADD_3(i, i, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(1)});
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	power_genLABEL_1(h2_BA_00000003);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	power_genBA_1(intsValue((labelAddresses [h2_begin_00000001] - h2_asm_pc)));
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	power_genLABEL_1(h2_end_00000002);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
		h2_outputVarName = power_genMV_2(h2_outputVarName, res);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	power_genRET_0();
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	/* Call back code for loops */
	h2_save_asm_pc = h2_asm_pc;
	h2_asm_pc = labelAddresses [h2_begin_00000001] + 1;
	power_genBGE_1(intsValue((labelAddresses [h2_end_00000002] - h2_asm_pc)));
	h2_asm_pc = labelAddresses [h2_BA_00000003];
	power_genBA_1(intsValue((labelAddresses [h2_begin_00000001] - h2_asm_pc)));
	h2_asm_pc = h2_save_asm_pc;
	h2_codeGenTime = h2_getticks() - h2_codeGenTime;
	h2_iflush(ptr, h2_asm_pc);

 return (h2_insn_t *)ptr;
}

int main(int argc, char * argv[])
{
  h2_insn_t * ptr;
  int in0, in1, res, resultOK;
  pifii fPtr;

  if (argc < 3)
    {
      printf("Give 2 increment values\n");
      exit(-1);
    }
  in0 = atoi (argv[1]);
  in1 = atoi (argv[2]);
  ptr  = h2_malloc (1024);     	 // Allocate memory for 1024 instructions
  fPtr = (pifii) genMul (ptr);   // Generate instructions
  res = fPtr(in0, in1);  	     // Call generated code
  printf("%d * %d = %d\n", in0, in1, res);
  if (res == (in0 * in1))
	return 0;
  else
	return -1;
}
