/* Begin Header autogenerated part */
#ifndef H2_COMMON
#define H2_COMMON
/* Common HybroGen inserted code */
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdbool.h>
#include <stdint.h>

bool h2_codeGenerationOK;	 // Does code generation fail ?
typedef int32_t h2_regSet_t; // Register set (signed, use -1 when not allocated)
static  uint32_t h2_insnGenerated;
typedef unsigned long long ticks_t;
static  ticks_t h2_codeGenTime;

typedef enum { H2REGISTER,    H2VALUE, } VALORREG;
typedef struct
{
  int ValOrReg; // is H2REGISTER or immediate VALUE ?
  char arith;   // int, flt or other arithmetic
  int vLen;     // vector len
  int wLen;     // word len
  int regNro;   // register number (if register)
  int valueImm; // immediate value (if not register)
  bool dontFree; // if register, don't free
} h2_sValue_t;
#define sValueDef(VALUE, ARITH, VECTORLEN, WORDLEN, REGNO, IMMVAL) ((h2_sValue_t){.ValOrReg = VALUE, .arith = ARITH, .vLen = VECTORLEN, .wLen = WORDLEN, .regNro = REGNO, .valueImm = IMMVAL})
#define intsValue(V)      sValueDef(H2VALUE, 'i', 1, 32, -1, V)
#define intReg32sValue(R) sValueDef(H2REGISTER, 'i', 1, 32, R, 0)
#define immValueZero intsValue(0)
// Usefull macro instruction to simplify instruction selector code
#define isInt64_1(P)  ((P.arith == 'i') && (P.wLen <= 64) && (P.vLen == 1))
#define isInt32_1(P)  ((P.arith == 'i') && (P.wLen <= 32) && (P.vLen == 1))
#define isInt0(P)     ((P.arith == 'i') && (P.ValOrReg == H2VALUE) && (0 == P.valueImm))
#define isInt1(P)     ((P.arith == 'i') && (P.ValOrReg == H2VALUE) && (1 == P.valueImm))
#define isValue(P)    ((P.arith == 'i') && (P.ValOrReg == H2VALUE))
#define isReg32(P, X) ((P.arith == 'i') && (P.ValOrReg == H2REGISTER) && (X == P.regNro))
#define isRRR(P0, P1, P2) (P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
#define isRRV(P0, P1, P2) (P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)


typedef union {
    float f;
    unsigned long i;
} h2_float_int_u;

static int h2_log2(int value)
{ // integer logarithm
  int log = 0;
  while (value >>= 1) { ++log; }
  return log;
}
// Print register map : F for free register, . for allocated
void printRev (int value, int pos)
{ // Print a bitset in reversal order (recursive)
  if (pos != 0)
	printRev (value >> 1, pos - 1);
  printf ("%1c", (value % 2)?'.':'F');
}

// Dynamic register allocation handling
// h2_regSet mask : 0 mean free register, 1 register set
//  3           2            1  Bit position = reg Number
// 1098 7654 3210 9876 5432 1098 7654 3210
// 1111 1111 1111 1111 0000 0001 0011 1111
typedef struct
{	// Register allocation sets for
  	// int, float, vector of ints, vector of floats
  int intSet, fltSet, vintSet, vfltSet ;
} h2_RegSets_t;

h2_RegSets_t h2_regSet, h2_regSetInit;

// Print integer register set
void printRegState(char * msg, int regNo, int registerSet)
{
  int count = 8 * sizeof (registerSet) - 1;
  h2_regSet_t tmpReg = registerSet;
  printf ("%02d : Reg %s\n", regNo, msg);
  for (int i = count; i >= 0; i--) // Tens
	(0 == (i % 10))?printf ("%d", i/10):printf (" ");
  printf ("\n");
  for (int i = count; i >= 0; i--) // Unit
	  printf ("%d", i%10);
  printf ("\n");
  printRev (tmpReg, count); // Bit set
  printf ("\n");
}

// Initialize registers sets allocation
static void h2_initRegisterMasks(int intmask, int fltmask, int vectorintmask, int vectorfltmask)
{ // See H2SymbolTable & H2RegisterBank
  h2_regSetInit  = (h2_RegSets_t){intmask, fltmask, vectorintmask, vectorfltmask};
}

static void h2_resetRegisterMasks() // Reset register set from initializers
{
  h2_regSet = h2_regSetInit;
#ifdef H2_DEBUG_REGISTER
  printRegState("RESET", -1, h2_regSet.intSet);
#endif // H2_DEBUG_REGISTER
}
int h2_getReg () // Get new register
{
  /* Search for the 1st free register */
  h2_regSet_t tmpReg = h2_regSet.intSet;
  for (int i = 0; i < 8 * sizeof (h2_regSet.intSet); i++)
	{
	  if (tmpReg % 2 == 0)
		{						/* Free register found */
		  h2_regSet.intSet = h2_regSet.intSet | (1 << i); /* Update regSet */
#ifdef H2_DEBUG_REGISTER
		  printRegState("GET", i, h2_regSet.intSet);
#endif // H2_DEBUG_REGISTER
		  return i;
		}
	  tmpReg >>= 1;
	}
  printf ("Register allocation failed\n");
  h2_codeGenerationOK = false;
  return -1;
}

// h2_regSet_t regToBeFreed[32];

void h2_freeReg (h2_regSet_t v) // Free a register
{
#if 1 // TODO : To be rethinked
      // Is the register freeable ?
  int isOK = (h2_regSetInit.intSet >> v) & 1;
  if (0 == isOK)
    {
	h2_regSet.intSet = h2_regSet.intSet & ~(1 << v); /* Update regSet */
#ifdef H2_DEBUG_REGISTER
    printRegState("FREE", v, h2_regSet.intSet);
#endif // H2_DEBUG_REGISTER
    }
#endif
}
#endif /*H2_COMMON*/
#ifndef H2_RISCV_RV32G
#define H2_RISCV_RV32G

#define H2SYS 					/* Has  operating system */

#include <stdint.h>
#ifdef H2SYS
#include <sys/mman.h>
#endif

typedef uint32_t    h2_insn_t;  /* Instruction size */
static  h2_insn_t   *h2_asm_pc; /* PC for code generation */
static  h2_insn_t    *h2_save_asm_pc;
static int h2_riscvVectorLen = 1;
static int h2_riscvVectorWidth = 1;
static h2_sValue_t SP= {H2REGISTER, 'i', 1, 32, 2, 0};

#if 0
/*
https://stackoverflow.com/questions/52187221/how-to-calculate-the-no-of-clock-cycles-in-riscv-clang
*/

ticks_t h2_getticks(void)
{
    unsigned long dst;
    // output into any register, likely a0
    // regular instruction:
    asm volatile ("csrrs %0, 0xc00, x0" : "=r" (dst) );
    // regular instruction with symbolic csr and register names
    // asm volatile ("csrrs %0, cycle, zero" : "=r" (dst) );
    // pseudo-instruction:
    // asm volatile ("csrr %0, cycle" : "=r" (dst) );
    // pseudo-instruction:
    //asm volatile ("rdcycle %0" : "=r" (dst) );
    return dst;
}
#endif

#if 1
// From https://github.com/FFTW/fftw3/blob/master/kernel/cycle.h
// HW counter measument
ticks_t h2_getticks(void)
{
  uint64_t result;
#if __riscv_xlen == 64
  asm volatile("rdtime %0" : "=r" (result));
#elif __riscv_xlen == 32
  uint32_t l, h, h2;
  do
	{
	  asm volatile(
				   "rdtimeh %0 \n"
				   "rdtime  %1 \n"
				   "rdtimeh %2 \n"
				   : "=r" (h), "=r" (l), "=r" (h2));
	} while (h2 != h);
  result =(((uint64_t)h)<<32) | ((uint64_t)l);
#endif
  return result;
}
#endif


#if 0
// System level clock measurment
#include <sys/time.h>
ticks_t h2_getticks(void)
{
    int res;
    struct timeval My_time;
    uint64_t tick;
    res = gettimeofday(&My_time, NULL);
    tick = My_time.tv_sec * 1000000 + My_time.tv_usec;
    if (0 == res)
	  {
        return tick;
	  } else
	  {
        return 0;
	  }
}
#endif

static void h2_iflush(void *addr, void *last)
{
	h2_insnGenerated = (last-addr)/sizeof (h2_insn_t);
#ifdef H2SYS
    long pageSize= getpagesize();
    void *ptmp= (char *)((long)addr & ~(pageSize - 1));
    if (mprotect(ptmp, (last - addr), PROT_READ | PROT_WRITE | PROT_EXEC))
    {
        perror("iflush: mprotect");
        exit(-1);
    }
    __clear_cache((char *)addr, (char *)last);
#endif
#ifdef H2_DEBUG
    printf ("Flush data cache from %p to %p\n", addr, last);
	printf ("%u insns generated in %lld ticks. %lld ticks / insn\n", (unsigned int)h2_insnGenerated, (long long) h2_codeGenTime,  (long long) h2_codeGenTime/h2_insnGenerated);
#endif
	if (!h2_codeGenerationOK)
	  {
		perror("(iflush) Failed code generation\n");
		exit(-5);
	  }
}

static h2_insn_t *h2_malloc (size_t size)
{
  return malloc (size);
}


#endif /*H2_RISCV_RV32G*/
/* In memory instruction generator */
#define riscv_G32(INSN){ *(h2_asm_pc++) = (INSN);}

/* Single instruction binary code generator*/
void RV32I_RET__I_32_1(){ /* RET */
	riscv_G32(((0x8067 >> 0) & 0xffffffff)); \

#ifdef H2_DEBUG_INSN
printf("%p : RV32I_RET__I_32_1\n", h2_asm_pc);
#endif
}
void RV32I_SUB_RRR_I_32_1(int r3,int r1,int r2){ /* SUB */
	riscv_G32(((0x20 & 0x7f) << 25)|((r2 & 0x1f) << 20)|((r1 & 0x1f) << 15)|((0x0 & 0x7) << 12)|((r3 & 0x1f) << 7)|((0x33 & 0x7f) >> 0));
#ifdef H2_DEBUG_INSN
printf("%p : RV32I_SUB_RRR_I_32_1\n", h2_asm_pc);
#endif
}
void RV32I_MV_RR_I_32_1(int r0,int r1){ /* MV */
	riscv_G32(((0x0 & 0xfff) << 20)|((r1 & 0x1f) << 15)|((0x0 & 0x7) << 12)|((r0 & 0x1f) << 7)|((0x13 & 0x7f) >> 0));
#ifdef H2_DEBUG_INSN
printf("%p : RV32I_MV_RR_I_32_1\n", h2_asm_pc);
#endif
}
void RV32I_MV_RI_I_32_1(int r3,int i1){ /* MV */
	riscv_G32(((i1 & 0xfff) << 20)|((0x6 & 0xff) << 12)|((r3 & 0x1f) << 7)|((0x13 & 0x7f) >> 0));
#ifdef H2_DEBUG_INSN
printf("%p : RV32I_MV_RI_I_32_1\n", h2_asm_pc);
#endif
}
void RV32I_SLLI_RRI_I_32_1(int r3,int r1,int i0){ /* SL */
	riscv_G32(((0x0 & 0x7f) << 25)|((i0 & 0x1f) << 20)|((r1 & 0x1f) << 15)|((0x1 & 0x7) << 12)|((r3 & 0x1f) << 7)|((0x13 & 0x7f) >> 0));
#ifdef H2_DEBUG_INSN
printf("%p : RV32I_SLLI_RRI_I_32_1\n", h2_asm_pc);
#endif
}
void RV32I_SLL_RRR_I_32_1(int r3,int r1,int r2){ /* SL */
	riscv_G32(((0x0 & 0x7f) << 25)|((r2 & 0x1f) << 20)|((r1 & 0x1f) << 15)|((0x1 & 0x7) << 12)|((r3 & 0x1f) << 7)|((0x33 & 0x7f) >> 0));
#ifdef H2_DEBUG_INSN
printf("%p : RV32I_SLL_RRR_I_32_1\n", h2_asm_pc);
#endif
}
void RV32M_MUL_RRR_I_32_1(int r3,int r1,int r2){ /* MUL */
	riscv_G32(((0x1 & 0x7f) << 25)|((r2 & 0x1f) << 20)|((r1 & 0x1f) << 15)|((0x0 & 0x7) << 12)|((r3 & 0x1f) << 7)|((0x33 & 0x7f) >> 0));
#ifdef H2_DEBUG_INSN
printf("%p : RV32M_MUL_RRR_I_32_1\n", h2_asm_pc);
#endif
}
void RV32I_ADDI_RRI_I_32_1(int r1,int r0,int i0){ /* ADD */
	riscv_G32(((i0 & 0xfff) << 20)|((r0 & 0x1f) << 15)|((0x0 & 0x7) << 12)|((r1 & 0x1f) << 7)|((0x13 & 0x7f) >> 0));
#ifdef H2_DEBUG_INSN
printf("%p : RV32I_ADDI_RRI_I_32_1\n", h2_asm_pc);
#endif
}
void RV32I_ADD_RRR_I_32_1(int r3,int r1,int r2){ /* ADD */
	riscv_G32(((0x0 & 0x7f) << 25)|((r2 & 0x1f) << 20)|((r1 & 0x1f) << 15)|((0x0 & 0x7) << 12)|((r3 & 0x1f) << 7)|((0x33 & 0x7f) >> 0));
#ifdef H2_DEBUG_INSN
printf("%p : RV32I_ADD_RRR_I_32_1\n", h2_asm_pc);
#endif
}
void RV32I_LB_RRI_I_8_1(int r3,int r1,int i1){ /* R */
	riscv_G32(((i1 & 0xfff) << 20)|((r1 & 0x1f) << 15)|((0x0 & 0x7) << 12)|((r3 & 0x1f) << 7)|((0x3 & 0x7f) >> 0));
#ifdef H2_DEBUG_INSN
printf("%p : RV32I_LB_RRI_I_8_1\n", h2_asm_pc);
#endif
}
void RV32I_LH_RRI_I_16_1(int r3,int r1,int i1){ /* R */
	riscv_G32(((i1 & 0xfff) << 20)|((r1 & 0x1f) << 15)|((0x1 & 0x7) << 12)|((r3 & 0x1f) << 7)|((0x3 & 0x7f) >> 0));
#ifdef H2_DEBUG_INSN
printf("%p : RV32I_LH_RRI_I_16_1\n", h2_asm_pc);
#endif
}
void RV32I_LW_RRI_I_32_1(int r3,int r1,int i1){ /* R */
	riscv_G32(((i1 & 0xfff) << 20)|((r1 & 0x1f) << 15)|((0x2 & 0x7) << 12)|((r3 & 0x1f) << 7)|((0x3 & 0x7f) >> 0));
#ifdef H2_DEBUG_INSN
printf("%p : RV32I_LW_RRI_I_32_1\n", h2_asm_pc);
#endif
}
void RV32I_SRLI_RRI_I_32_1(int r3,int r1,int i0){ /* SR */
	riscv_G32(((0x0 & 0x7f) << 25)|((i0 & 0x1f) << 20)|((r1 & 0x1f) << 15)|((0x5 & 0x7) << 12)|((r3 & 0x1f) << 7)|((0x13 & 0x7f) >> 0));
#ifdef H2_DEBUG_INSN
printf("%p : RV32I_SRLI_RRI_I_32_1\n", h2_asm_pc);
#endif
}
void RV32I_SRL_RRR_I_32_1(int r3,int r1,int r2){ /* SR */
	riscv_G32(((0x0 & 0x7f) << 25)|((r2 & 0x1f) << 20)|((r1 & 0x1f) << 15)|((0x5 & 0x7) << 12)|((r3 & 0x1f) << 7)|((0x33 & 0x7f) >> 0));
#ifdef H2_DEBUG_INSN
printf("%p : RV32I_SRL_RRR_I_32_1\n", h2_asm_pc);
#endif
}
void RV32I_SB_RRI_I_8_1(int r1,int r2,int i1){ /* W */
	riscv_G32((((i1 >> 5) & 0x7f) << 25)|((r2 & 0x1f) << 20)|((r1 & 0x1f) << 15)|((0x0 & 0x7) << 12)|((i1 & 0x1f) << 7)|((0x23 & 0x7f) >> 0));
#ifdef H2_DEBUG_INSN
printf("%p : RV32I_SB_RRI_I_8_1\n", h2_asm_pc);
#endif
}
void RV32I_SH_RRI_I_16_1(int r1,int r2,int i1){ /* W */
	riscv_G32((((i1 >> 5) & 0x7f) << 25)|((r2 & 0x1f) << 20)|((r1 & 0x1f) << 15)|((0x1 & 0x7) << 12)|((i1 & 0x1f) << 7)|((0x23 & 0x7f) >> 0));
#ifdef H2_DEBUG_INSN
printf("%p : RV32I_SH_RRI_I_16_1\n", h2_asm_pc);
#endif
}
void RV32I_SW_RRI_I_32_1(int r1,int r2,int i1){ /* W */
	riscv_G32((((i1 >> 5) & 0x7f) << 25)|((r2 & 0x1f) << 20)|((r1 & 0x1f) << 15)|((0x2 & 0x7) << 12)|((i1 & 0x1f) << 7)|((0x23 & 0x7f) >> 0));
#ifdef H2_DEBUG_INSN
printf("%p : RV32I_SW_RRI_I_32_1\n", h2_asm_pc);
#endif
}
h2_sValue_t riscv_genW_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t riscv_genSUB_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t riscv_genMUL_4(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2,h2_sValue_t P3);
h2_sValue_t riscv_genMV_2(h2_sValue_t P0,h2_sValue_t P1);
h2_sValue_t riscv_genSL_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t riscv_genADD_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t riscv_genR_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t riscv_genRET_0();
h2_sValue_t riscv_genSR_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2);
h2_sValue_t riscv_genW_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for W instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for W

/* -*- c -*- */
if (isValue(P1))
  { // Store constant (Should use RRI variant)
	h2_sValue_t PTMP = {H2REGISTER, P1.arith, P1.vLen, P1.wLen, h2_getReg()};
    #ifdef H2_DEBUG_INSN
      printf ("Fallback for no RI W (riscv)\\n");
    #endif
	// MV const in tmp register
	P1 = riscv_genMV_2(PTMP,  P1);
	// No return continue instruction selection
  }

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P1.arith == 'i') && (P1.wLen <= 8) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	RV32I_SB_RRI_I_8_1(P0.regNro, P1.regNro, P2.valueImm);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 16) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	RV32I_SH_RRI_I_16_1(P0.regNro, P1.regNro, P2.valueImm);
	return P1;
    }

    if ((P1.arith == 'i') && (P1.wLen <= 32) && (P1.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	RV32I_SW_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P1;
    }
	printf ("Warning, W instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);return immValueZero;
}
h2_sValue_t riscv_genSUB_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for SUB instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
/* -*- c -*- */
// if 2 operands are constants do substraction evaluation (Thanks Kilian for the bug report)
if  ((P2.ValOrReg == H2VALUE) && (P1.ValOrReg == H2VALUE) && (P1.arith == 'i')&& (P2.arith == 'i'))
{
  return (h2_sValue_t) {H2VALUE, P1.arith, P1.vLen, P1.wLen, -1, P1.valueImm - P2.valueImm };
}

/* -*- c -*- */
if  ((P2.ValOrReg == H2VALUE) && (P2.arith == 'i'))
{
	h2_sValue_t PTMP = {H2REGISTER, P2.arith, P2.vLen, P2.wLen, h2_getReg()};
    #ifdef H2_DEBUG_INSN
      printf ("Fallback for no RRI sub (riscv)\\n");
    #endif
	P2 = riscv_genMV_2(PTMP,  P2);
}

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	RV32I_SUB_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, SUB instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t riscv_genMUL_4(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2,h2_sValue_t P3)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for MUL instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
/* -*- c -*- */
  // if 2 operands are constants do multiplication evaluation (Thanks Kilian for the bug report)
  if  ((P2.ValOrReg == H2VALUE) && (P1.ValOrReg == H2VALUE) && (P1.arith == 'i')&& (P2.arith == 'i'))
  {
    return (h2_sValue_t) {H2VALUE, P1.arith, P1.vLen, P1.wLen, -1, P1.valueImm * P2.valueImm };
  }
  /* if (isInt0(P2) || isInt0(P1)) */
  /*  {    // X * 0 = 0 Avoid 1 operation mul & 1 mv */
  /*       #ifdef H2_DEBUG_INSN */
  /*       printf ("Optim for *0 P2 (generic)\n"); */
  /*       #endif */
  /*       return immValueZero; */
  /*   } */
  /* if (isInt1(P2)) */
  /*   { // X * 1 = X propagate register result */
  /*       #ifdef H2_DEBUG_INSN */
  /*       printf ("Optim for *1 P2 (generic)\n"); */
  /*       #endif */
  /* 		P1.dontFree = true; */
  /*       return P1; */
  /*   } */
  /* if (isInt1(P1)) */
  /*   { // 1 * X = X propagate register result */
  /*       #ifdef H2_DEBUG_INSN */
  /*       printf ("Optim for *1 P1 (generic)\n"); */
  /*       #endif */
  /* 		P2.dontFree = true; */
  /*       return P2; */
  /*   } */

/* -*- c -*- */
if (isInt0(P2))
  { //   X * 0 = 0 Avoid 1 operation mul & 1 mv
#ifdef H2_DEBUG_INSN
	printf ("Optim for *0 P2 (riscv)\n");
#endif
	return riscv_genMV_2(P0, immValueZero);
  }

if  (isValue(P2) && ((P2.valueImm != 0) && !(P2.valueImm & (P2.valueImm - 1))))
  {
	int shiftValue = h2_log2(P2.valueImm);
    #ifdef H2_DEBUG_INSN
      printf ("Optim for MUL %d (power of 2) -> sl %d (riscv)\n", P2.valueImm, shiftValue);
    #endif
	P2.valueImm = shiftValue; 	// Instruction shift left immediat
	return riscv_genSL_3(P0, P1, P2);
  }

if  (isValue(P2))
{
	h2_sValue_t PTMP = {H2REGISTER, P2.arith, P2.vLen, P2.wLen, h2_getReg()};
    #ifdef H2_DEBUG_INSN
      printf ("Fallback for no RRI mul (riscv)\n");
    #endif
	P2 = riscv_genMV_2(PTMP,  P2);
	// No return continue instruction selection
}

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	RV32M_MUL_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, MUL instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t riscv_genMV_2(h2_sValue_t P0,h2_sValue_t P1)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for MV instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for MV

// No specific optimisation for MV/riscv

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER)
    {
	RV32I_MV_RR_I_32_1(P0.regNro, P1.regNro);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2VALUE)
    {
	RV32I_MV_RI_I_32_1(P0.regNro, P1.valueImm);
	return P0;
    }
	printf ("Warning, MV instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);return immValueZero;
}
h2_sValue_t riscv_genSL_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for SL instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for SL

// No specific optimisation for SL/riscv

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	RV32I_SLLI_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	RV32I_SLL_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, SL instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t riscv_genADD_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for ADD instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
/* -*- c -*- */
// If 2 operands are constants do addition
if  ((P2.ValOrReg == H2VALUE) && (P1.ValOrReg == H2VALUE) && (P1.arith == 'i')&& (P2.arith == 'i'))
{
  return sValueDef(H2VALUE, P1.arith, P1.vLen, P1.wLen, -1, P1.valueImm + P2.valueImm );
}
if (isInt0 (P2))
  { // P0 = P1 + 0
    #ifdef H2_DEBUG_INSN
	printf ("Optim add for 0 (generic) return reg %d\n", P1.regNro);
    #endif
	P1.dontFree = true;
	return P1;
  }
if (isInt0 (P1))
  { // P0 = 0 + P2
    #ifdef H2_DEBUG_INSN
    printf ("Optim add for 0  (generic) return reg %d\n", P2.regNro);
    #endif
	P2.dontFree = true;
    return P2;
  }

// No specific optimisation for ADD/riscv

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	RV32I_ADDI_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	RV32I_ADD_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, ADD instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}
h2_sValue_t riscv_genR_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for R instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for R

// No specific optimisation for R/riscv

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 8) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	RV32I_LB_RRI_I_8_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 16) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	RV32I_LH_RRI_I_16_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	RV32I_LW_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }
	printf ("Warning, R instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);return immValueZero;
}
h2_sValue_t riscv_genRET_0()
{
// No generic optimisation for RET

// No specific optimisation for RET/riscv

RV32I_RET__I_32_1();
	
}
h2_sValue_t riscv_genSR_3(h2_sValue_t P0,h2_sValue_t P1,h2_sValue_t P2)
{
#ifdef H2_DEBUG_INSN
	printf ("Start code gen for SR instruction\n");
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");
	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);
	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);
#endif // H2_DEBUG_INSN
// No generic optimisation for SR

// No specific optimisation for SR/riscv

	if ((P0.ValOrReg == H2REGISTER) && (P0.regNro == -1))
		P0.regNro = h2_getReg();
	if ((P1.ValOrReg == H2REGISTER) && (P1.regNro == -1))
		P1.regNro = h2_getReg();

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2VALUE)
    {
	RV32I_SRLI_RRI_I_32_1(P0.regNro, P1.regNro, P2.valueImm);
	return P0;
    }

    if ((P0.arith == 'i') && (P0.wLen <= 32) && (P0.vLen == 1) && P0.ValOrReg == H2REGISTER && P1.ValOrReg == H2REGISTER && P2.ValOrReg == H2REGISTER)
    {
	RV32I_SRL_RRR_I_32_1(P0.regNro, P1.regNro, P2.regNro);
	return P0;
    }
	printf ("Warning, SR instruction generation failed\n");
	h2_codeGenerationOK = false;
	printf ("ValOrReg / arith / wLen / vLen / regNro / valueImm\n");	printf ("P%d: %s/%c/%d/%d/%d\n", 0, (0==P0.ValOrReg)?"REG":"VAL", P0.arith, P0.wLen, P0.vLen, P0.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 1, (0==P1.ValOrReg)?"REG":"VAL", P1.arith, P1.wLen, P1.vLen, P1.valueImm);	printf ("P%d: %s/%c/%d/%d/%d\n", 2, (0==P2.ValOrReg)?"REG":"VAL", P2.arith, P2.wLen, P2.vLen, P2.valueImm);return immValueZero;
}

/* End Header autogenerated part */
/* -*- c -*- */
// https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/mesa/math/m_matrix.c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <strings.h>
#define T 4
typedef int d_t;
typedef d_t matrix_t [T][T];
typedef d_t vector_t [T];
typedef d_t (*pifvv)(vector_t, vector_t);

pifvv genVectorMatrixProduct(pifvv ptr, matrix_t m)
{
	/* Code Generation of 5 instructions */
	/* Symbol table :*/
	/*VarName = {ValOrLen, arith, vectorLen, wordLen, regNo, ValueImm, dontFree} */
	h2_sValue_t o = {H2REGISTER, 'i', 1, 32, 10, true};
	h2_sValue_t i = {H2REGISTER, 'i', 1, 32, 11, true};
	h2_sValue_t h2_outputVarName = {H2REGISTER, 'i', 1, 32, 10, true};
	h2_sValue_t tmp0000 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0001 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0002 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0003 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0004 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0005 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0006 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0007 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0008 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0009 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0010 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0011 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0012 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0013 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0014 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0015 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0016 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0017 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0018 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0019 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0020 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0021 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0022 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0023 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0024 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0025 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0026 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0027 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0028 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0029 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0030 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0031 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0032 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0033 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0034 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0035 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0036 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0037 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0038 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0039 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0040 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0041 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0042 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0043 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0044 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0045 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0046 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0047 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0048 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0049 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0050 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0051 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0052 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0053 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0054 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0055 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0056 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0057 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0058 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0059 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0060 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0061 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0062 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0063 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0064 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0065 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0066 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0067 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0068 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0069 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0070 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0071 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0072 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0073 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0074 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0075 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0076 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0077 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0078 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0079 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0080 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0081 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0082 = {H2REGISTER, 'i', 1, 32, -1, false};
	h2_sValue_t tmp0083 = {H2REGISTER, 'i', 1, 32, -1, false};

	/* Label  table :*/
/* No label table to avoid C warning for empty table ... */
	h2_asm_pc = (h2_insn_t *) ptr;
	h2_codeGenerationOK = true;
	h2_codeGenTime = h2_getticks();
	h2_initRegisterMasks(0xF1F, 0, 0, 0);
	h2_resetRegisterMasks();
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask initialization\n");
	#endif // H2_DEBUG_REGISTER
	riscv_genADD_3(SP, SP, intsValue(-48));
riscv_genW_3(SP, intReg32sValue(18), intsValue(44));
riscv_genW_3(SP, intReg32sValue(19), intsValue(40));
riscv_genW_3(SP, intReg32sValue(20), intsValue(36));
riscv_genW_3(SP, intReg32sValue(21), intsValue(32));
riscv_genW_3(SP, intReg32sValue(22), intsValue(28));
riscv_genW_3(SP, intReg32sValue(23), intsValue(24));
riscv_genW_3(SP, intReg32sValue(24), intsValue(20));
riscv_genW_3(SP, intReg32sValue(25), intsValue(16));
riscv_genW_3(SP, intReg32sValue(26), intsValue(12));
riscv_genW_3(SP, intReg32sValue(27), intsValue(8));
				tmp0000 = riscv_genMUL_4(tmp0000, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(0)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
				tmp0001 = riscv_genADD_3(tmp0001, o, tmp0000);
		if (!tmp0001.dontFree) h2_freeReg(tmp0000.regNro);
									tmp0002 = riscv_genMUL_4(tmp0002, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(0)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
									tmp0003 = riscv_genADD_3(tmp0003, i, tmp0002);
							if (!tmp0003.dontFree) h2_freeReg(tmp0002.regNro);
							tmp0004 = riscv_genR_3(tmp0004, tmp0003, immValueZero);
						tmp0005 = riscv_genMUL_4(tmp0005, tmp0004, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((m[0][0]))}, immValueZero);
					if (!tmp0005.dontFree) h2_freeReg(tmp0004.regNro);
									tmp0006 = riscv_genMUL_4(tmp0006, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(1)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
									tmp0007 = riscv_genADD_3(tmp0007, i, tmp0006);
							if (!tmp0007.dontFree) h2_freeReg(tmp0006.regNro);
							tmp0008 = riscv_genR_3(tmp0008, tmp0007, immValueZero);
						tmp0009 = riscv_genMUL_4(tmp0009, tmp0008, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((m[1][0]))}, immValueZero);
					if (!tmp0009.dontFree) h2_freeReg(tmp0008.regNro);
						tmp0010 = riscv_genADD_3(tmp0010, tmp0005, tmp0009);
				if (!tmp0010.dontFree) h2_freeReg(tmp0005.regNro);
				if (!tmp0010.dontFree) h2_freeReg(tmp0009.regNro);
								tmp0011 = riscv_genMUL_4(tmp0011, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(2)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
								tmp0012 = riscv_genADD_3(tmp0012, i, tmp0011);
						if (!tmp0012.dontFree) h2_freeReg(tmp0011.regNro);
						tmp0013 = riscv_genR_3(tmp0013, tmp0012, immValueZero);
					tmp0014 = riscv_genMUL_4(tmp0014, tmp0013, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((m[2][0]))}, immValueZero);
				if (!tmp0014.dontFree) h2_freeReg(tmp0013.regNro);
					tmp0015 = riscv_genADD_3(tmp0015, tmp0010, tmp0014);
			if (!tmp0015.dontFree) h2_freeReg(tmp0010.regNro);
			if (!tmp0015.dontFree) h2_freeReg(tmp0014.regNro);
							tmp0016 = riscv_genMUL_4(tmp0016, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(3)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
							tmp0017 = riscv_genADD_3(tmp0017, i, tmp0016);
					if (!tmp0017.dontFree) h2_freeReg(tmp0016.regNro);
					tmp0018 = riscv_genR_3(tmp0018, tmp0017, immValueZero);
				tmp0019 = riscv_genMUL_4(tmp0019, tmp0018, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((m[3][0]))}, immValueZero);
			if (!tmp0019.dontFree) h2_freeReg(tmp0018.regNro);
				tmp0020 = riscv_genADD_3(tmp0020, tmp0015, tmp0019);
		if (!tmp0020.dontFree) h2_freeReg(tmp0015.regNro);
		if (!tmp0020.dontFree) h2_freeReg(tmp0019.regNro);
		riscv_genW_3(tmp0001, tmp0020, immValueZero);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
				tmp0021 = riscv_genMUL_4(tmp0021, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(1)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
				tmp0022 = riscv_genADD_3(tmp0022, o, tmp0021);
		if (!tmp0022.dontFree) h2_freeReg(tmp0021.regNro);
									tmp0023 = riscv_genMUL_4(tmp0023, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(0)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
									tmp0024 = riscv_genADD_3(tmp0024, i, tmp0023);
							if (!tmp0024.dontFree) h2_freeReg(tmp0023.regNro);
							tmp0025 = riscv_genR_3(tmp0025, tmp0024, immValueZero);
						tmp0026 = riscv_genMUL_4(tmp0026, tmp0025, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((m[0][1]))}, immValueZero);
					if (!tmp0026.dontFree) h2_freeReg(tmp0025.regNro);
									tmp0027 = riscv_genMUL_4(tmp0027, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(1)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
									tmp0028 = riscv_genADD_3(tmp0028, i, tmp0027);
							if (!tmp0028.dontFree) h2_freeReg(tmp0027.regNro);
							tmp0029 = riscv_genR_3(tmp0029, tmp0028, immValueZero);
						tmp0030 = riscv_genMUL_4(tmp0030, tmp0029, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((m[1][1]))}, immValueZero);
					if (!tmp0030.dontFree) h2_freeReg(tmp0029.regNro);
						tmp0031 = riscv_genADD_3(tmp0031, tmp0026, tmp0030);
				if (!tmp0031.dontFree) h2_freeReg(tmp0026.regNro);
				if (!tmp0031.dontFree) h2_freeReg(tmp0030.regNro);
								tmp0032 = riscv_genMUL_4(tmp0032, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(2)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
								tmp0033 = riscv_genADD_3(tmp0033, i, tmp0032);
						if (!tmp0033.dontFree) h2_freeReg(tmp0032.regNro);
						tmp0034 = riscv_genR_3(tmp0034, tmp0033, immValueZero);
					tmp0035 = riscv_genMUL_4(tmp0035, tmp0034, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((m[2][1]))}, immValueZero);
				if (!tmp0035.dontFree) h2_freeReg(tmp0034.regNro);
					tmp0036 = riscv_genADD_3(tmp0036, tmp0031, tmp0035);
			if (!tmp0036.dontFree) h2_freeReg(tmp0031.regNro);
			if (!tmp0036.dontFree) h2_freeReg(tmp0035.regNro);
							tmp0037 = riscv_genMUL_4(tmp0037, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(3)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
							tmp0038 = riscv_genADD_3(tmp0038, i, tmp0037);
					if (!tmp0038.dontFree) h2_freeReg(tmp0037.regNro);
					tmp0039 = riscv_genR_3(tmp0039, tmp0038, immValueZero);
				tmp0040 = riscv_genMUL_4(tmp0040, tmp0039, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((m[3][1]))}, immValueZero);
			if (!tmp0040.dontFree) h2_freeReg(tmp0039.regNro);
				tmp0041 = riscv_genADD_3(tmp0041, tmp0036, tmp0040);
		if (!tmp0041.dontFree) h2_freeReg(tmp0036.regNro);
		if (!tmp0041.dontFree) h2_freeReg(tmp0040.regNro);
		riscv_genW_3(tmp0022, tmp0041, immValueZero);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
				tmp0042 = riscv_genMUL_4(tmp0042, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(2)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
				tmp0043 = riscv_genADD_3(tmp0043, o, tmp0042);
		if (!tmp0043.dontFree) h2_freeReg(tmp0042.regNro);
									tmp0044 = riscv_genMUL_4(tmp0044, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(0)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
									tmp0045 = riscv_genADD_3(tmp0045, i, tmp0044);
							if (!tmp0045.dontFree) h2_freeReg(tmp0044.regNro);
							tmp0046 = riscv_genR_3(tmp0046, tmp0045, immValueZero);
						tmp0047 = riscv_genMUL_4(tmp0047, tmp0046, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((m[0][2]))}, immValueZero);
					if (!tmp0047.dontFree) h2_freeReg(tmp0046.regNro);
									tmp0048 = riscv_genMUL_4(tmp0048, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(1)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
									tmp0049 = riscv_genADD_3(tmp0049, i, tmp0048);
							if (!tmp0049.dontFree) h2_freeReg(tmp0048.regNro);
							tmp0050 = riscv_genR_3(tmp0050, tmp0049, immValueZero);
						tmp0051 = riscv_genMUL_4(tmp0051, tmp0050, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((m[1][2]))}, immValueZero);
					if (!tmp0051.dontFree) h2_freeReg(tmp0050.regNro);
						tmp0052 = riscv_genADD_3(tmp0052, tmp0047, tmp0051);
				if (!tmp0052.dontFree) h2_freeReg(tmp0047.regNro);
				if (!tmp0052.dontFree) h2_freeReg(tmp0051.regNro);
								tmp0053 = riscv_genMUL_4(tmp0053, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(2)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
								tmp0054 = riscv_genADD_3(tmp0054, i, tmp0053);
						if (!tmp0054.dontFree) h2_freeReg(tmp0053.regNro);
						tmp0055 = riscv_genR_3(tmp0055, tmp0054, immValueZero);
					tmp0056 = riscv_genMUL_4(tmp0056, tmp0055, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((m[2][2]))}, immValueZero);
				if (!tmp0056.dontFree) h2_freeReg(tmp0055.regNro);
					tmp0057 = riscv_genADD_3(tmp0057, tmp0052, tmp0056);
			if (!tmp0057.dontFree) h2_freeReg(tmp0052.regNro);
			if (!tmp0057.dontFree) h2_freeReg(tmp0056.regNro);
							tmp0058 = riscv_genMUL_4(tmp0058, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(3)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
							tmp0059 = riscv_genADD_3(tmp0059, i, tmp0058);
					if (!tmp0059.dontFree) h2_freeReg(tmp0058.regNro);
					tmp0060 = riscv_genR_3(tmp0060, tmp0059, immValueZero);
				tmp0061 = riscv_genMUL_4(tmp0061, tmp0060, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((m[3][2]))}, immValueZero);
			if (!tmp0061.dontFree) h2_freeReg(tmp0060.regNro);
				tmp0062 = riscv_genADD_3(tmp0062, tmp0057, tmp0061);
		if (!tmp0062.dontFree) h2_freeReg(tmp0057.regNro);
		if (!tmp0062.dontFree) h2_freeReg(tmp0061.regNro);
		riscv_genW_3(tmp0043, tmp0062, immValueZero);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
				tmp0063 = riscv_genMUL_4(tmp0063, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(3)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
				tmp0064 = riscv_genADD_3(tmp0064, o, tmp0063);
		if (!tmp0064.dontFree) h2_freeReg(tmp0063.regNro);
									tmp0065 = riscv_genMUL_4(tmp0065, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(0)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
									tmp0066 = riscv_genADD_3(tmp0066, i, tmp0065);
							if (!tmp0066.dontFree) h2_freeReg(tmp0065.regNro);
							tmp0067 = riscv_genR_3(tmp0067, tmp0066, immValueZero);
						tmp0068 = riscv_genMUL_4(tmp0068, tmp0067, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((m[0][3]))}, immValueZero);
					if (!tmp0068.dontFree) h2_freeReg(tmp0067.regNro);
									tmp0069 = riscv_genMUL_4(tmp0069, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(1)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
									tmp0070 = riscv_genADD_3(tmp0070, i, tmp0069);
							if (!tmp0070.dontFree) h2_freeReg(tmp0069.regNro);
							tmp0071 = riscv_genR_3(tmp0071, tmp0070, immValueZero);
						tmp0072 = riscv_genMUL_4(tmp0072, tmp0071, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((m[1][3]))}, immValueZero);
					if (!tmp0072.dontFree) h2_freeReg(tmp0071.regNro);
						tmp0073 = riscv_genADD_3(tmp0073, tmp0068, tmp0072);
				if (!tmp0073.dontFree) h2_freeReg(tmp0068.regNro);
				if (!tmp0073.dontFree) h2_freeReg(tmp0072.regNro);
								tmp0074 = riscv_genMUL_4(tmp0074, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(2)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
								tmp0075 = riscv_genADD_3(tmp0075, i, tmp0074);
						if (!tmp0075.dontFree) h2_freeReg(tmp0074.regNro);
						tmp0076 = riscv_genR_3(tmp0076, tmp0075, immValueZero);
					tmp0077 = riscv_genMUL_4(tmp0077, tmp0076, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((m[2][3]))}, immValueZero);
				if (!tmp0077.dontFree) h2_freeReg(tmp0076.regNro);
					tmp0078 = riscv_genADD_3(tmp0078, tmp0073, tmp0077);
			if (!tmp0078.dontFree) h2_freeReg(tmp0073.regNro);
			if (!tmp0078.dontFree) h2_freeReg(tmp0077.regNro);
							tmp0079 = riscv_genMUL_4(tmp0079, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)(3)}, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((1 * 32) / 8)}, immValueZero);
							tmp0080 = riscv_genADD_3(tmp0080, i, tmp0079);
					if (!tmp0080.dontFree) h2_freeReg(tmp0079.regNro);
					tmp0081 = riscv_genR_3(tmp0081, tmp0080, immValueZero);
				tmp0082 = riscv_genMUL_4(tmp0082, tmp0081, (h2_sValue_t) {H2VALUE, 'i', 1, 32, 0, (int)((m[3][3]))}, immValueZero);
			if (!tmp0082.dontFree) h2_freeReg(tmp0081.regNro);
				tmp0083 = riscv_genADD_3(tmp0083, tmp0078, tmp0082);
		if (!tmp0083.dontFree) h2_freeReg(tmp0078.regNro);
		if (!tmp0083.dontFree) h2_freeReg(tmp0082.regNro);
		riscv_genW_3(tmp0064, tmp0083, immValueZero);
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	riscv_genR_3(intReg32sValue(18), SP, intsValue(44));
	riscv_genR_3(intReg32sValue(19), SP, intsValue(40));
	riscv_genR_3(intReg32sValue(20), SP, intsValue(36));
	riscv_genR_3(intReg32sValue(21), SP, intsValue(32));
	riscv_genR_3(intReg32sValue(22), SP, intsValue(28));
	riscv_genR_3(intReg32sValue(23), SP, intsValue(24));
	riscv_genR_3(intReg32sValue(24), SP, intsValue(20));
	riscv_genR_3(intReg32sValue(25), SP, intsValue(16));
	riscv_genR_3(intReg32sValue(26), SP, intsValue(12));
	riscv_genR_3(intReg32sValue(27), SP, intsValue(8));
	riscv_genADD_3(SP, SP, intsValue(48));
	riscv_genRET_0();
	#ifdef H2_DEBUG_REGISTER
	printf("Tmp registers mask reset\n");
	#endif // H2_DEBUG_REGISTER
	h2_resetRegisterMasks();
	/* Call back code for loops */
	h2_save_asm_pc = h2_asm_pc;
	h2_asm_pc = h2_save_asm_pc;
	h2_codeGenTime = h2_getticks() - h2_codeGenTime;
	h2_iflush(ptr, h2_asm_pc);

  return ptr;
}

d_t VectorMatrixProductUnrolled (vector_t o, vector_t i, matrix_t m)
{
  o[0] = i[0]*m[0][0] + i[1]*m[1][0] + i[2]*m[2][0] + i[3]*m[3][0];
  o[1] = i[0]*m[0][1] + i[1]*m[1][1] + i[2]*m[2][1] + i[3]*m[3][1];
  o[2] = i[0]*m[0][2] + i[1]*m[1][2] + i[2]*m[2][2] + i[3]*m[3][2];
  o[3] = i[0]*m[0][3] + i[1]*m[1][3] + i[2]*m[2][3] + i[3]*m[3][3];
  return o[3];
}

#if 0 // What the binary code should be with a translation matrix
d_t VectorMatrixProductUnrolledSR(vector_t o, vector_t i, matrix_t m)
{

  o[0] = m[0][0] * i[0] +                                 + m[3][0] * i[3];
  o[1] =                  m[1][1] * i[1] +                + m[3][1] * i[3];
  o[2] =                                   m[2][2] * i[2] + m[3][2] * i[3];
  o[3] =                                                  +           i[3];
  return o[3];
}
#endif
d_t VectorMatrixProduct (vector_t o, vector_t i, matrix_t m)
{
  for (int column = 0; column < T; column++)
    {
      o[column] = 0;
      for (int line = 0; line < T; line++)
        {
          o[column] += i[line] * m[line][column];

        }
    }
  return o[3];
}


int VectorMatrixProductCount(matrix_t mat)
{
  int op = 0;
  for (int column = 0; column < T; column++)
    {
      for (int line = 0; line < T; line++)
        {
          switch (mat[line][column])
            {
            case 0 : op += 0; break;
            case 1 : op += 1; break;
            default: op += 2; break;
            }
        }
    }
  return op;
}


void printMatrix (matrix_t m, char msg[])
{
  printf ("%s:\n", msg);
  for (int column = 0; column < T; column++)
    {
      for (int line = 0; line < T; line++)
        {
          printf ("%4d ", m[line][column]);
        }
      printf ("\n");
    }
  printf ("\n");
}

void printVector (vector_t v, char msg[])
{
  for (int i = 0; i < T; i++)
    printf ("%4d ", v[i]);
  printf ("%s\n", msg);
}

bool vectorCompare(vector_t ref[], vector_t other[], char * msg, int doPrint, int nVector)
{
  int has_differences = false;
  for (int line = 0; line < nVector; line++)
	for (int i = 0; i < T; i++)
	  {
		if (ref[line][i] != other[line][i])
		  has_differences = true;
		if (doPrint)
		  printf("%4d ", other[line][i]);
    }
  /* printf("%s : ", msg); */
  /* printf(" %s\n", (has_differences)?"NOT OK":"OK"); */
  return has_differences;
}

int main (int argc, char *argv[])
{
  matrix_t m;
  char *matrixName;
  //  vector_t in0  = {1, 2, 3, 4}, in1  = {5, 6, 7, 8};
  vector_t *out, *cout, *in;
  uint64_t timeGeneral, timeCompilette;
  pifvv vmProduct;
  int tmp, doPrint, nXperiment;
  unsigned long acc;
  bool resultValid;

  if (argc != 19)
    {
      printf ("Not enough arguments %d\n", argc);
      printf ("VectorMatrix ExperimentNumber MatrixName M11 M12 ... M44\n");
      exit (-1);
    }
  doPrint = 0;
  acc = 0;
  nXperiment = atoi (argv[1]);
  matrixName = argv[2];
  for (int line = 0; line < 4; line++)
    for (int column = 0; column < 4; column++)
      {
        m[line][column] = atoi (argv[3 + line*4+column]);
      }
#ifdef VERBOSE
  printMatrix(m, matrixName);
#endif

  in   = calloc(nXperiment, sizeof (vector_t));
  out  = calloc(nXperiment, sizeof (vector_t));
  cout = calloc(nXperiment, sizeof (vector_t));

  for (int line = 0; line < nXperiment; line++)
	for (int column = 0; column < 4; column++)
	  in[line][column] = random () % 1000;

  tmp = VectorMatrixProductCount (m);
  printf("Operation count Matrix %s : %d theoretical speedup %.1f\n", matrixName, tmp, (0==tmp)?32:32.0/tmp);

// Repeat one instruction and count ticks
#define DO(INSN, REPEAT, TIME) {uint64_t tickCount = h2_getticks();for (int i = 0; i < REPEAT; i++) INSN;  TIME = h2_getticks() - tickCount;}

#ifdef VERBOSE
  printVector (in[0], "Input vector #0");
#endif

  acc += VectorMatrixProduct (out[0], in[0], m); /* Cold start */
  DO(acc += VectorMatrixProduct (out[i], in[i], m), nXperiment, timeGeneral)

#ifdef VERBOSE
  printVector (out[0], "Output vector #0 (general)");
#endif

#if 0 // Possible test with a source level unrolled version
  uint64_t timeUnrolled;
  vector_t uout0, uout1;
  acc += VectorMatrixProductUnrolled (uout0, in0, m);
  DO(acc += VectorMatrixProductUnrolled (uout1, in1, m), nXperiment, timeUnrolled);
  vectorCompare(out1, uout1, "Unrolled out0", doPrint);
#endif

  vmProduct = (pifvv) h2_malloc(1024);
  vmProduct = genVectorMatrixProduct (vmProduct, m);
  acc += vmProduct (cout[0], in[0]);
  DO(acc += vmProduct (cout[i], in[i]), nXperiment, timeCompilette);

#ifdef VERBOSE
  printVector (cout[0], "Output vector #0 (compilette)");
#endif

  resultValid = vectorCompare(out, cout, "Compilette", doPrint, nXperiment);

  printf ("%s;%d;%lu;%lu;%lld;%d;%s\n",
		  matrixName, nXperiment,
		  timeGeneral, timeCompilette,
		  h2_codeGenTime, h2_insnGenerated,
		  resultValid?"true":"false");
  return resultValid;
}
