name: CD

on:
  workflow_run:
    workflows: ["CI Test"]
    types: [completed]

jobs:
  deploy:

    if: ${{ github.event.workflow_run.conclusion == 'success'  && github.event.workflow_run.head_branch == 'main' }}

    runs-on: ubuntu-22.04

    strategy:
        matrix:
            port: [60000, 65000, 65001,65002,65003]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        run: |
          gh run download ${{ github.event.workflow_run.id }} -n hybrogen-artifacts -D artifacts
          gh run download ${{ github.event.workflow_run.id }} -n toolchains -D toolchains
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move artifacts
        run: |
          rm -rf ./HybroGen ./HybroLang
          mv artifacts/generated/HybroGen ./
          mv artifacts/generated/HybroLang ./
          rm -rf artifacts/

      - name: Clean machine
        uses: appleboy/ssh-action@v1
        with:
          host: home.hpch.net
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ matrix.port }}
          script: |
            rm -rf ~/FromCD
            mkdir ~/FromCD

      - name: Copy artifacts via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: home.hpch.net
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ matrix.port }}
          source: "."
          target: "~/FromCD/"