name: CI Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/Checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # to change

      - name: Install QEMU dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libglib2.0-dev \
            libpixman-1-dev \
            zlib1g-dev \
            pkg-config

      - name: Create temp folder
        env:
          TEMP_DIR: ${{ runner.temp }}/my_temp
        run: |
          echo "Using temp folder: $RUNNER_TEMP/my_temp"
          mkdir -p $RUNNER_TEMP/my_temp
          export TEMP_DIR="$RUNNER_TEMP/my_temp"


  build-GenCrossTools:
    if: contains(github.event.head_commit.modified, 'GenCrossTools.py')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/Checkout@v4
    - name: GenCrossTools test on each arch
      env:
        TEMP_DIR: ${{ runner.temp }}/my_temp
      run: |
        echo "Start Gen cross tools test"
        python GenCrossTools.py -a aarch64  -p "$TEMP_DIR" -w "$TEMP_DIR/" 
        echo "Aarch64 arch has been setup with GenCrossTools"
        python GenCrossTools.py -a riscv  -p "$TEMP_DIR" -w "$TEMP_DIR/" 
        echo "riscv arch has been setup with GenCrossTools"
        python GenCrossTools.py -a power  -p "$TEMP_DIR" -w "$TEMP_DIR/" 
        echo "power arch has been setup with GenCrossTools"

  regression-test:
    runs-on: ubuntu-latest
    steps:
    - name: Regression test on each arch
      env:
        TEMP_DIR: ${{ runner.temp }}/my_temp
      run: |
        cd CodeExamples && ./Regression.py aarch64 riscv power

