name: CI Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  build-toolschains:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/Checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # to change

      - name: Install QEMU dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libglib2.0-dev \
            libpixman-1-dev \
            zlib1g-dev \
            pkg-config

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: toolchains
          key: toolchain-${{ hashFiles('GenCrossTools.py') }}

      - name: Build toolchains
        env:
          TOOLCHAIN_DIR: ${{ github.workspace }}/toolchains
        run: |
          mkdir -p "$TOOLCHAIN_DIR"
          python GenCrossTools.py -a aarch64 -p "$TOOLCHAIN_DIR" -w "$TOOLCHAIN_DIR/"
          python GenCrossTools.py -a riscv  -p "$TOOLCHAIN_DIR" -w "$TOOLCHAIN_DIR/"
          python GenCrossTools.py -a power  -p "$TOOLCHAIN_DIR" -w "$TOOLCHAIN_DIR/"

      - name: Create tar archive
        run: |
          tar -czf toolchains.tar.gz -C toolchains .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: toolchains
          path: toolchains.tar.gz

  build-grammar-and-dataBase:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/Checkout@v4
      - name: Install ANTLR4 via apt
        run: |
          sudo apt update          
          sudo apt install -y antlr4      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Get ANTLR version
        id: antlr-version
        run: |
          VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
          echo "ANTLR version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Install ANTLR4 for H2ISA
        run: | # BE CAREFUL antlr4-python3-runtime==4.7.2 Doit etre tenu a jour ou trouver une manière de synchroniser antlr4 version et antlr4 python runtime
          sudo apt update
          sudo apt install -y python3-antlr4
          python -m pip install --upgrade pip
          pip install antlr4-python3-runtime==${VERSION}
          

      - name: LaunchConstruction
        run: | 
            make buildGrammar
      
      - name: builded file present 
        run: |
            test -f ./HybroGen/IsaDescriptionLexer.py
            test -f ./HybroGen/IsaDescriptionParser.py

            
      - name: Try import
        run: |
          python -c "from HybroGen.IsaDescriptionLexer import IsaDescriptionLexer"
          python -c "from HybroGen.IsaDescriptionParser import IsaDescriptionParser"




      
      - name: make Db
        run: |
          make DbPopulate
    
  regression-test-aarch64:
    runs-on: ubuntu-latest
    needs: [build-toolschains,build-grammar-and-dataBase] 
    steps:
      
    - name: Checkout repo
      uses: actions/Checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: toolchains

    - name: Extract toolchains
      run: |
        mkdir toolchains
        tar -xzf toolchains.tar.gz -C toolchains

    - name: Verify files
      run: |
        ls -l ./toolchains
    - name: Regression test on each arch
      run: |
        make aarch64

  regression-test-riscv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/Checkout@v4
    - name: Regression test on each arch
      run: |
        make riscv

  regression-test-power:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/Checkout@v4
    - name: Regression test on each arch
      run: |
        make power
        