name: HybroGen_CD_Workflow

on:
  workflow_call:


jobs:
  deploy:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
          - arch: riscv
            port: 60000

          - arch: aarch64
            port: 65000

          - arch: aarch64
            port: 65001

          - arch: aarch64
            port: 65002

          - arch: aarch64
            port: 65003

    steps:

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Install ANTLR4 via apt
        run: |
          sudo apt update          
          sudo apt install -y antlr4    
          VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
          sudo apt install -y python3-antlr4
          python -m pip install --upgrade pip
          python -m pip install antlr4-python3-runtime==${VERSION}
          python -m pip install psycopg2-binary 

      - name: Download artifacts
        run: |
          gh run download ${{ github.event.workflow_run.id }} -n hybrogen-artifacts -D artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move artifacts
        run: |
          rm -rf ./HybroGen ./HybroLang
          mv artifacts/generated/HybroGen ./HybroGen
          mv artifacts/generated/HybroLang ./HybroLang
          rm -rf artifacts/
          ls

      - name: Build C file
        run: |
          cd ./Demos
          cd ./Stencil/ && make make build  ARCH=${{  matrix.arch }}
          cd ../VectorMatrix && make build  ARCH=${{  matrix.arch }}
          cd ../Newton-SquareRoot-VariablePrecision && make build  ARCH=${{  matrix.arch }}


      - name: Debug secrets
        env:
          HOST: ${{ secrets.SSH_ADDR_DEST }}
        run: |
          if [ -z "$HOST" ]; then
            echo "SECRET VIDE"
          else
            echo "SECRET PRESENT"
          fi

      - name: Clean machine
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.SSH_ADDR_DEST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ matrix.port }}
          script: |
            rm -rf ~/FromCD
            mkdir ~/FromCD

      - name: Copy artifacts via SCP
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345
        with:
          host: ${{ secrets.SSH_ADDR_DEST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ matrix.port }}
          source: "./Demos"
          target: "~/FromCD/"

      - name: Compile Program and generate Plot
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.SSH_ADDR_DEST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ matrix.port }}
          script: |
            cd ~/FromCD/Demos/Stencil/ && make allNative ARCH=${{ matrix.arch }} CFLAGS=-O0 CC=cc RUNNER="\"\"" LOG=${{ matrix.arch }}-native-O0.log            
            cd ~/FromCD/Demos/Stencil/ && make allNative ARCH=${{ matrix.arch }} CFLAGS=-O3 CC=cc RUNNER="\"\"" LOG=${{ matrix.arch }}-native-O3.log
            cd ~/FromCD/Demos/VectorMatrix/ && 	make run  ARCH=${{ matrix.arch}} CFLAGS=O3 RUNNER=""" REPEAT=1000000   >> VectorMatrixLogO3.log
            cd ~/FromCD/Demos/VectorMatrix/ && 	make run  ARCH=${{ matrix.arch}} CFLAGS=O0 RUNNER=""" REPEAT=1000000   >> VectorMatrixLogO0.log
            cd ~/FromCD/Demos/VectorMatrix/ && pthon3 PlotResults.py VectorMatrixLogO0.log VectorMatrixLogO3.log 1000000
#Ajouter l'option de run NewtonSquareRoot en natif et faire un truc avec les logs#cd ~/FromCD/Demos/NewtonSquareRoot/ && make allNative ARCH=$ CC=cc RUNNER="" LOG=riscv-native-`date +"%Y-%m-%d-%H-%M-%S"`.log

            