name: HybroGen_CI_Workflow


# https://docs.github.com/fr/actions
on:
  push: # on push branch main and on push CI CD branch developpment
    branches:
      - 'main'
      - 'HybroGen_CI/CD_Developpment'
  pull_request: # on pull request on main branch
    branches:
      - 'main'

permissions:
  contents: read

jobs:


  #######################################################################################
  ###################### Building of HybroGen ###########################################
  #######################################################################################
  build-toolschains:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        architecture: [aarch64, riscv, power]
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: '3.11'  # to change

      - name: Install QEMU dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libglib2.0-dev \
            libpixman-1-dev \
            zlib1g-dev \
            pkg-config 
            sudo apt install -y libc6

      - name: Restore cache
        id: toolchain-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ./${{matrix.architecture}}
          key: ${{matrix.architecture}}-${{ hashFiles('GenCrossTools.py') }}

      - name: Build toolchains
        if: steps.toolchain-cache.outputs.cache-hit != 'true'
        env:
          TOOLCHAIN_DIR: ${{ github.workspace }}/
        run: |
          python GenCrossTools.py -a ${{matrix.architecture}}  -p "$TOOLCHAIN_DIR" -w "$TOOLCHAIN_DIR/"
          python GenCrossTools.py -a ${{matrix.architecture}}  -p "$TOOLCHAIN_DIR" -w "$TOOLCHAIN_DIR/" -s

      - name: Check bashrc
        run: |
          test -e ./${{matrix.architecture}}/.bashrc

      
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: ${{matrix.architecture}}
          path: ./${{matrix.architecture}}
          include-hidden-files: true
          if-no-files-found: error

  build-grammar-and-dataBase:
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      
      - name: Install ANTLR4 via apt
        run: |
          sudo apt update          
          sudo apt install -y antlr4      

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: '3.11'
          
      - name: Get ANTLR version
        id: antlr-version
        run: |
          VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
          echo "ANTLR version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Install ANTLR4 for H2ISA
        run: | # BE CAREFUL antlr4-python3-runtime==4.7.2 Doit etre tenu a jour ou trouver une manière de synchroniser antlr4 version et antlr4 python runtime
          sudo apt update
          sudo apt install -y python3-antlr4
          sudo apt install -y sqlite3 libsqlite3-dev
          python -m pip install --upgrade pip
          python -m pip install antlr4-python3-runtime==${VERSION}

      - name: LaunchConstruction
        run: | 
            make buildGrammar
      
      - name: builded file present 
        run: |
            test -f ./HybroGen/IsaDescriptionLexer.py
            test -f ./HybroGen/IsaDescriptionParser.py

      - name: Try import
        run: |
          python -c "from HybroGen.IsaDescriptionLexer import IsaDescriptionLexer"
          python -c "from HybroGen.IsaDescriptionParser import IsaDescriptionParser"

      - name: make Db
        run: |
          make DbPopulate

      - name: Copy generated code
        run: |
          mkdir -p artifacts/generated
          cp -r ./HybroGen artifacts/generated/
          cp -r ./HybroLang artifacts/generated/

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: hybrogen-artifacts
          path: artifacts/
          if-no-files-found: error

  #######################################################################################
  ###################### Regression test ################################################
  #######################################################################################

  regression-test:
    runs-on: ubuntu-24.04
    needs: [build-toolschains,build-grammar-and-dataBase] 

    strategy:
      matrix:
        architecture: [aarch64, riscv, power]
    steps:
      
    - name: Checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: ${{matrix.architecture}}
        path: ./${{matrix.architecture}}

    - name: Download artifacts
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Regression test on ${{matrix.architecture}}
      env:
        BASH_ENV: ./${{matrix.architecture}}/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        sudo apt install -y sqlite3 libsqlite3-dev
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        chmod -R +x ./${{matrix.architecture}}/
        make ${{matrix.architecture}}

  #######################################################################################
  ###################### Regression Single Op ###########################################
  #######################################################################################
        ###Stand by

  regression-singleOp-test:
    runs-on: ubuntu-24.04
    needs: [build-toolschains,build-grammar-and-dataBase] 

    
    strategy:
      matrix:
        architecture: [aarch64, riscv, power]
    steps:
      
    - name: Checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0   
      with:           
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
      with:
        python-version: '3.11'


    - name: Download artifact
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: ${{matrix.architecture}}
        path: ./${{matrix.architecture}}

    - name: Download artifacts
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Regression test on ${{matrix.architecture}}
      continue-on-error: true
      env:
        BASH_ENV: ./${{matrix.architecture}}/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        sudo apt install -y sqlite3 libsqlite3-dev
        python -m pip install --upgrade pip
        chmod -R +x ./${{matrix.architecture}}/
        cd ./CodeExamples/ && python3 RegressionSingleOp.py -v -a ${{matrix.architecture}}
        ls ./CodeExamples/json/
    


    - name: Upload artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      with:
        name: RegressionSingleOp-${{matrix.architecture}}.json
        path: ./CodeExamples/json/RegressionSingleOp-${{matrix.architecture}}.json
        if-no-files-found: error



  actualise-json:
    runs-on: ubuntu-24.04
    needs: [regression-singleOp-test] 
    permissions:
      contents: write

    strategy:
      matrix:
        architecture: [aarch64, riscv, power]
    steps:

    - name: Download artefact for each
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        for arch in riscv aarch64 powerpc; do

          echo "Downloading artifact for $arch"

          gh run download \
            ${{ github.run_id }} \
            --name "RegressionSingleOp-${{matrix.architecture}}.json" \
            --dir "./CodeExamples/json/"

          echo "Testing $arch"

          python test.py "./artifacts/$arch"

        done

    - name: commit changes and push it on the repository
      run: |
          git config user.name "HybroGenCI"
          git config user.email "hybrogen.ci@users.noreply.github.com"
          git add ./CodeExamples/json/
          if ! git diff --cached --quiet; then
            git commit -m "chore: update for ${{matrix.architecture}} regression results [skip ci]"
            git push
          fi
  #######################################################################################
  ###################### Demo Stencil ###################################################
  #######################################################################################
  demo-stencil:
    runs-on: ubuntu-24.04
    needs: [regression-test] 

    strategy:
      matrix:
        architecture: [aarch64, riscv, power]
    steps:
      
    - name: Checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: ${{matrix.architecture}}
        path: ./${{matrix.architecture}}/

    - name: Download artifacts
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Stencil test on ${{matrix.architecture}}
      env:
        BASH_ENV: ${{ github.workspace }}/${{matrix.architecture}}/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        sudo apt install -y sqlite3 libsqlite3-dev
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        chmod -R +x ./${{matrix.architecture}}/
        cd ./Demos/Stencil && make all${{matrix.architecture}}Qemu

  #######################################################################################
  ###################### Demo Vector Matrix ###################################################
  #######################################################################################


  demo-vectorMatrix:
    runs-on: ubuntu-24.04
    needs: [regression-test] 

    strategy:
      matrix:
        architecture: [aarch64, riscv, power]
    steps:
      
    - name: Checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: ${{matrix.architecture}}
        path: ./${{matrix.architecture}}/

    - name: Download artifacts
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Test Vector
      env:
        BASH_ENV: ${{ github.workspace }}/${{matrix.architecture}}/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        sudo apt install -y sqlite3 libsqlite3-dev
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        chmod -R +x ./${{matrix.architecture}}/
        cd ./Demos/VectorMatrix && make ${{matrix.architecture}}

  #######################################################################################
  ###################### Newton SquareRoot demo #########################################
  #######################################################################################

  demo-NewtonSquareRoot:
    runs-on: ubuntu-24.04
    needs: [regression-test] 

    strategy:
      matrix:
        architecture: [aarch64, riscv, power]
    steps:
      
    - name: Checkout repo
      uses: actions/Checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: ${{matrix.architecture}}
        path: ./${{matrix.architecture}}/

    - name: Download artifacts
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Run Demo newtonSquareRoot
      env:
        BASH_ENV: ${{ github.workspace }}/${{matrix.architecture}}/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        sudo apt install -y sqlite3 libsqlite3-dev
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        chmod -R +x ./${{matrix.architecture}}/
        cd ./Demos/Newton-SquareRoot-VariablePrecision && make demo-${{matrix.architecture}}


  #######################################################################################
  ###################### Launch CD For deployment #######################################
  #######################################################################################

  launch_CD:
    needs: [demo-NewtonSquareRoot,demo-stencil,demo-vectorMatrix]
    uses: ./.github/workflows/HybroGenMainCD.yml
    secrets: inherit
    if: success() || failure()
    

