name: HybroGen_CI_Workflow


# https://docs.github.com/fr/actions
on:
  push: # on push branch main and on push CI CD branch developpment
    branches:
      - 'main'
      - 'HybroGen_CI/CD_Developpment'
  pull_request: # on pull request on main branch
    branches:
      - 'main'

permissions: #permission for safety
  contents: read

jobs:


  #######################################################################################
  ###################### Building of HybroGen ###########################################
  #######################################################################################
  build-toolschains:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        architecture: [aarch64, riscv, power]
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: '3.11'  # to change

      - name: Install QEMU dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libglib2.0-dev \
            libpixman-1-dev \
            zlib1g-dev \
            pkg-config 
            sudo apt install -y libc6

      - name: Restore cache #job that use cache to accelerate the CI. The generation of GenCrossTools has a high cost in ressources and time so if GenCrossTools.py has not changed since the last commit we use cache to skip the generation jobs
        id: toolchain-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ./${{matrix.architecture}}
          key: ${{matrix.architecture}}-${{ hashFiles('GenCrossTools.py') }}

      - name: Build toolchains # Build toolchains to use (ex aarch64)
        if: steps.toolchain-cache.outputs.cache-hit != 'true'
        env:
          TOOLCHAIN_DIR: ${{ github.workspace }}/
        run: |
          python GenCrossTools.py -a ${{matrix.architecture}}  -p "$TOOLCHAIN_DIR" -w "$TOOLCHAIN_DIR/"
          python GenCrossTools.py -a ${{matrix.architecture}}  -p "$TOOLCHAIN_DIR" -w "$TOOLCHAIN_DIR/" -s

      - name: Check bashrc #check if bashrc is well generated
        run: |
          test -e ./${{matrix.architecture}}/.bashrc

      
      - name: Upload artifact #Upload toolchains has an artefact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: ${{matrix.architecture}}
          path: ./${{matrix.architecture}}
          include-hidden-files: true # ex .bashrc
          if-no-files-found: error #generate error if artifact does not exist


  build-grammar-and-dataBase: #jobs that build grammar using the .isa and the sqLite data base of hybrogen
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      
      - name: Install ANTLR4 via apt
        run: |
          sudo apt update          
          sudo apt install -y antlr4      

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: '3.11'
          
      - name: Get ANTLR version
        id: antlr-version
        run: |
          VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
          echo "ANTLR version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Install ANTLR4
        run: | # BE CAREFUL antlr4-python3-runtime==4.7.2 Doit etre tenu a jour ou trouver une manière de synchroniser antlr4 version et antlr4 python runtime
          sudo apt update
          sudo apt install -y python3-antlr4
          sudo apt install -y sqlite3 libsqlite3-dev
          python -m pip install --upgrade pip
          python -m pip install antlr4-python3-runtime==${VERSION}

      - name: LaunchConstruction #Build grammar for all arch
        run: | 
            make buildGrammar
      
      - name: builded file present  #test if build file are present
        run: |
            test -f ./HybroGen/IsaDescriptionLexer.py
            test -f ./HybroGen/IsaDescriptionParser.py

      - name: Try import # test import to see if there is an error of version
        run: |
          python -c "from HybroGen.IsaDescriptionLexer import IsaDescriptionLexer"
          python -c "from HybroGen.IsaDescriptionParser import IsaDescriptionParser"

      - name: make Db # Create the database
        run: |
          make DbPopulate

      - name: Copy generated code #Copy the generated file into an artefact for future jobs
        run: |
          mkdir -p artifacts/generated
          cp -r ./HybroGen artifacts/generated/
          cp -r ./HybroLang artifacts/generated/

      - name: Upload artifacts #Upload the artifact which contains the generated file
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: hybrogen-artifacts
          path: artifacts/
          if-no-files-found: error

  #######################################################################################
  ###################### Regression test ################################################
  #######################################################################################

  regression-test: #jobs that launch regression test to test a lot of cases present in ./CodeExamples
    runs-on: ubuntu-24.04
    needs: [build-toolschains,build-grammar-and-dataBase] 

    #Strategy to launch multiple vm per architecture to launch all regression test "simultaniously"
    strategy:
      matrix:
        architecture: [aarch64, riscv, power]
    steps:
      
    - name: Checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact # Download toolchains
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: ${{matrix.architecture}}
        path: ./${{matrix.architecture}}

    - name: Download artifacts #Download dataBase and build grammar
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts #Replace repo old directory by the artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Regression test on ${{matrix.architecture}} #Launch regression on each architecture using the .bashrc generate with GencrossTools as environmtent for the VM
      env:
        BASH_ENV: ./${{matrix.architecture}}/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        sudo apt install -y sqlite3 libsqlite3-dev
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        chmod -R +x ./${{matrix.architecture}}/
        make ${{matrix.architecture}}

  #######################################################################################
  ###################### Regression Single Op ###########################################
  #######################################################################################
        ###Stand by

  regression-singleOp-test: #The job of this job is to launch the regressionSingleOp.py and to update the json associated to it. To let the user know which operation are working, not working or not supported on Hybrogen
    runs-on: ubuntu-24.04
    needs: [build-toolschains,build-grammar-and-dataBase] 
    concurrency:
      group: singleOp-json-${{ github.ref }}
      cancel-in-progress: false
      
    #Strategy to launch multiple vm per architecture to launch all regressionSingleOp "simultaniously"
    strategy:
      matrix:
        architecture: [aarch64, riscv, power]
    steps:
      
    - name: Checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0   

    - name: Setup Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
      with:
        python-version: '3.11'


    - name: Download artifact #Download toolchains
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: ${{matrix.architecture}}
        path: ./${{matrix.architecture}}

    - name: Download artifacts #Download grammar build and DataBase
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts #Replace repo old directory by the artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Regression Single op test on ${{matrix.architecture}} #Launch regression Single Op
      continue-on-error: true
      env:
        BASH_ENV: ./${{matrix.architecture}}/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        sudo apt install -y sqlite3 libsqlite3-dev
        python -m pip install --upgrade pip
        chmod -R +x ./${{matrix.architecture}}/
        cd ./CodeExamples/ && python3 RegressionSingleOp.py -v -a ${{matrix.architecture}}
        ls ./CodeExamples/json/
    


    - name: Upload artifacts #Store the json as an artifact to update it on the repo later
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      with:
        name: RegressionSingleOp-${{matrix.architecture}}.json
        path: ./CodeExamples/json/RegressionSingleOp-${{matrix.architecture}}.json
        if-no-files-found: error



  actualise-json: #This job has for mission to take the json filled in regression-singleOp-test and push it into the branch to update it
    runs-on: ubuntu-24.04
    needs: [regression-singleOp-test] 
    permissions: #Permission to write into the repo
      contents: write
    concurrency:
      group: singleOp-json-${{ github.ref }}
      cancel-in-progress: false
      
    steps:
    - name: Checkout repo #Checkout repo and use a token for permission to push
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0   
      with:           
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}

    - name: Download artefact for each  #Download each json for each architecture
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        for arch in riscv aarch64 power; do

          echo "Downloading artifact for $arch"
          rm -f ./CodeExamples/json/RegressionSingleOp-$arch.json
          gh run download \
            ${{ github.run_id }} \
            --name "RegressionSingleOp-$arch.json" \
            --dir "./CodeExamples/json/"

        done

    - name: commit changes and push it on the repository # Git add All json commit by the CI and push it with the mention [skip ci] to avoid infinite loop CI
      run: |
          git config user.name "HybroGenCI"
          git config user.email "hybrogen.ci@users.noreply.github.com"
          git add ./CodeExamples/json/
          if ! git diff --cached --quiet; then
            git commit -m "chore: update for ${{matrix.architecture}} regression results [skip ci]"
            git push origin HEAD:${{ github.ref_name }}
          fi


  #######################################################################################
  ###################### Demo Stencil ###################################################
  #######################################################################################
  
  demo-stencil: #Job to launch demo stencil and check if result are good on qemu
    runs-on: ubuntu-24.04
    needs: [regression-test] 

    #Strategy to launch multiple vm per architecture to launch all stencil demo on each arch "simultaniously"
    strategy:
      matrix:
        architecture: [aarch64, riscv, power]
    steps:
      
    - name: Checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact #Download toolchains
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: ${{matrix.architecture}}
        path: ./${{matrix.architecture}}/

    - name: Download artifacts #Download dataBase and Grammar build
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts #Replace repo old directory by the artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Stencil test on ${{matrix.architecture}} #Launch demo stencil on qemu matrix.architecture 
      env:
        BASH_ENV: ${{ github.workspace }}/${{matrix.architecture}}/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        sudo apt install -y sqlite3 libsqlite3-dev
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        chmod -R +x ./${{matrix.architecture}}/
        cd ./Demos/Stencil && make all${{matrix.architecture}}Qemu

  #######################################################################################
  ###################### Demo Vector Matrix #############################################
  #######################################################################################


  demo-vectorMatrix: #Job to launch demo VectorMatrix and check if result are good on qemu
    runs-on: ubuntu-24.04
    needs: [regression-test] 

    #Strategy to launch multiple vm per architecture to launch all VectorMatrix demo on each arch "simultaniously"

    strategy:
      matrix:
        architecture: [aarch64, riscv, power]
    steps:
      
    - name: Checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update
        sudo apt install -y antlr4
        
    - name: Setup Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact #Download toolchains 
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: ${{matrix.architecture}}
        path: ./${{matrix.architecture}}/

    - name: Download artifacts #Download db and grammarBuild
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts #Replace repo old directory by the artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Test Vector on ${{matrix.architecture}} #Launch demo VectorMatrix on qemu matrix.architecture 
      env:
        BASH_ENV: ${{ github.workspace }}/${{matrix.architecture}}/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        sudo apt install -y sqlite3 libsqlite3-dev
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        chmod -R +x ./${{matrix.architecture}}/
        cd ./Demos/VectorMatrix && make ${{matrix.architecture}}

  #######################################################################################
  ###################### Newton SquareRoot demo #########################################
  #######################################################################################

  demo-NewtonSquareRoot:
    runs-on: ubuntu-24.04
    needs: [regression-test] 

    strategy:
      matrix:
        architecture: [aarch64, riscv, power]
    steps:
      
    - name: Checkout repo
      uses: actions/Checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact #Download toolchains
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: ${{matrix.architecture}}
        path: ./${{matrix.architecture}}/

    - name: Download artifacts #Download DataBase and grammar build
      uses: actions/download-artifact@f99b3e3d1560723c9a3e30e653411513bc69cedb
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts #Replace repo old directory by the artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Run Demo newtonSquareRoot #Launch demo newtonSquareRoot on qemu matrix.architecture 
      env:
        BASH_ENV: ${{ github.workspace }}/${{matrix.architecture}}/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        sudo apt install -y sqlite3 libsqlite3-dev
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        chmod -R +x ./${{matrix.architecture}}/
        cd ./Demos/Newton-SquareRoot-VariablePrecision && make demo-${{matrix.architecture}}


  #######################################################################################
  ###################### Launch CD For deployment #######################################
  #######################################################################################

  launch_CD: # this Job has to launch CD 
    needs: [demo-NewtonSquareRoot,demo-stencil,demo-vectorMatrix]
    uses: ./.github/workflows/HybroGenMainCD.yml
    secrets: inherit #Secret Heritage
    #CD can't make the CI fail
    if: success() || failure()  
    

