name: HybroGen_CI_Workflow


# https://docs.github.com/fr/actions
# test refus de commit on main pour garder une branch main toujours fonctionnel
on:
  push: # on push branch main
    branches:
      - 'main'
      - 'HybroGen_CI/CD_Developpment'
  pull_request: # on pull request on all branch
    branches:
      - 'main'

jobs:

  #######################################################################################
  ###################### Building of HybroGen ###########################################
  #######################################################################################
  build-toolschains-riscv:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/Checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # to change

      - name: Install QEMU dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libglib2.0-dev \
            libpixman-1-dev \
            zlib1g-dev \
            pkg-config 
            sudo apt install -y libc6

      - name: Restore cache
        id: toolchain-cache
        uses: actions/cache@v4
        with:
          path: toolchains/riscv
          key: toolchain/riscv-${{ hashFiles('GenCrossTools.py') }}

      - name: Build toolchains
        if: steps.toolchain-cache.outputs.cache-hit != 'true'
        env:
          TOOLCHAIN_DIR: ${{ github.workspace }}/toolchains
        run: |
          mkdir -p "$TOOLCHAIN_DIR"
          python GenCrossTools.py -a riscv  -p "$TOOLCHAIN_DIR" -w "$TOOLCHAIN_DIR/"
          python GenCrossTools.py -a riscv  -p "$TOOLCHAIN_DIR" -w "$TOOLCHAIN_DIR/" -s

      - name: Check bashrc
        run: |
          test -e ./toolchains/riscv/.bashrc

      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: riscv
          path: toolchains/riscv
          include-hidden-files: true
          if-no-files-found: error
  
  build-toolschains-power:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/Checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # to change

      - name: Install QEMU dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libglib2.0-dev \
            libpixman-1-dev \
            zlib1g-dev \
            pkg-config 
            sudo apt install -y libc6

      - name: Restore cache
        id: toolchain-cache
        uses: actions/cache@v4
        with:
          path: toolchains/power
          key: toolchain/power-${{ hashFiles('GenCrossTools.py') }}

      - name: Build toolchains
        if: steps.toolchain-cache.outputs.cache-hit != 'true'
        env:
          TOOLCHAIN_DIR: ${{ github.workspace }}/toolchains
        run: |
          mkdir -p "$TOOLCHAIN_DIR"
          python GenCrossTools.py -a power  -p "$TOOLCHAIN_DIR" -w "$TOOLCHAIN_DIR/"
          python GenCrossTools.py -a power  -p "$TOOLCHAIN_DIR" -w "$TOOLCHAIN_DIR/" -s

      - name: Check bashrc
        run: |
          test -e ./toolchains/power/.bashrc

      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: power
          path: toolchains/power
          include-hidden-files: true
          if-no-files-found: error
  
  build-toolschains-aarch64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/Checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # to change

      - name: Install QEMU dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libglib2.0-dev \
            libpixman-1-dev \
            zlib1g-dev \
            pkg-config 
            sudo apt install -y libc6

      - name: Restore cache
        id: toolchain-cache
        uses: actions/cache@v4
        with:
          path: toolchains/aarch64
          key: toolchain/aarch64-${{ hashFiles('GenCrossTools.py') }}

      - name: Build toolchains
        if: steps.toolchain-cache.outputs.cache-hit != 'true'
        env:
          TOOLCHAIN_DIR: ${{ github.workspace }}/toolchains
        run: |
          mkdir -p "$TOOLCHAIN_DIR"
          python GenCrossTools.py -a aarch64 -p "$TOOLCHAIN_DIR" -w "$TOOLCHAIN_DIR/" 
          python GenCrossTools.py -a aarch64 -p "$TOOLCHAIN_DIR" -w "$TOOLCHAIN_DIR/" -s

      - name: Check bashrc
        run: |
          test -e ./toolchains/aarch64/.bashrc

      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aarch64
          path: toolchains/aarch64
          include-hidden-files: true
          if-no-files-found: error

  build-grammar-and-dataBase:
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hybrogen
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:

      - name: Checkout repo
        uses: actions/Checkout@v4
      
      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Create hybrogen dataBase and schema
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -d hybrogen <<EOF
          CREATE USER hybrogen WITH PASSWORD 'hybrogen';
          GRANT ALL PRIVILEGES ON DATABASE hybrogen TO hybrogen;
          CREATE SCHEMA IF NOT EXISTS hybrogen AUTHORIZATION hybrogen;
          EOF
      
      - name: Install ANTLR4 via apt
        run: |
          sudo apt update          
          sudo apt install -y antlr4      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Get ANTLR version
        id: antlr-version
        run: |
          VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
          echo "ANTLR version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Install ANTLR4 for H2ISA
        run: | # BE CAREFUL antlr4-python3-runtime==4.7.2 Doit etre tenu a jour ou trouver une manière de synchroniser antlr4 version et antlr4 python runtime
          sudo apt update
          sudo apt install -y python3-antlr4
          python -m pip install --upgrade pip
          python -m pip install antlr4-python3-runtime==${VERSION}
          python -m pip install psycopg2-binary

      - name: LaunchConstruction
        run: | 
            make buildGrammar
      
      - name: builded file present 
        run: |
            test -f ./HybroGen/IsaDescriptionLexer.py
            test -f ./HybroGen/IsaDescriptionParser.py

            
      - name: Try import
        run: |
          python -c "from HybroGen.IsaDescriptionLexer import IsaDescriptionLexer"
          python -c "from HybroGen.IsaDescriptionParser import IsaDescriptionParser"

      - name: make Db
        run: |
          make DbPopulate

      - name: Dump database
        env:
          PGUSER: hybrogen
          PGPASSWORD: hybrogen
        run: |
          mkdir -p artifacts
          pg_dump -h localhost > artifacts/hybrogen.sql

      - name: Copy generated code
        run: |
          mkdir -p artifacts/generated
          cp -r ./HybroGen artifacts/generated/
          cp -r ./HybroLang artifacts/generated/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hybrogen-artifacts
          path: artifacts/
          if-no-files-found: error

  #######################################################################################
  ###################### Regression test ################################################
  #######################################################################################

  regression-test-aarch64:
    runs-on: ubuntu-24.04
    needs: [build-toolschains-aarch64,build-grammar-and-dataBase] 
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hybrogen
          POSTGRES_PASSWORD: hybrogen
          POSTGRES_DB: hybrogen
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U hybrogen"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      
    - name: Checkout repo
      uses: actions/Checkout@v4

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: aarch64
        path: ./aarch64/

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Restore database
      env:
        PGPASSWORD: hybrogen
      run: |
        until pg_isready -h localhost -p 5432 -U hybrogen; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        psql -h localhost -U hybrogen -d hybrogen < artifacts/hybrogen.sql

    - name: Regression test on aarch64
      env:
        BASH_ENV: ./aarch64/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        python -m pip install psycopg2-binary
        chmod -R +x ./aarch64/
        make aarch64
      
  regression-test-riscv:
    runs-on: ubuntu-24.04
    needs: [build-toolschains-riscv,build-grammar-and-dataBase] 
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hybrogen
          POSTGRES_PASSWORD: hybrogen
          POSTGRES_DB: hybrogen
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U hybrogen"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      
    - name: Checkout repo
      uses: actions/Checkout@v4

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: riscv
        path: ./riscv/

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Restore database
      env:
        PGPASSWORD: hybrogen
      run: |
        until pg_isready -h localhost -p 5432 -U hybrogen; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        psql -h localhost -U hybrogen -d hybrogen < artifacts/hybrogen.sql

    - name: Regression test on riscv
      env:
        BASH_ENV: ${{ github.workspace }}/riscv/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        python -m pip install psycopg2-binary
        chmod -R +x ./riscv/
        make riscv

  regression-test-power:
    runs-on: ubuntu-24.04
    needs: [build-toolschains-power,build-grammar-and-dataBase] 
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hybrogen
          POSTGRES_PASSWORD: hybrogen
          POSTGRES_DB: hybrogen
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U hybrogen"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      
    - name: Checkout repo
      uses: actions/Checkout@v4

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: power
        path: ./

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Restore database
      env:
        PGPASSWORD: hybrogen
      run: |
        until pg_isready -h localhost -p 5432 -U hybrogen; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        psql -h localhost -U hybrogen -d hybrogen < artifacts/hybrogen.sql

    - name: Regression test on power
      env:
        BASH_ENV: ${{ github.workspace }}/power/.bashrc
      run: |
        ls ./power/
        sudo apt update
        sudo apt install -y python3-antlr4
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        python -m pip install psycopg2-binary
        chmod -R +x ./power/
        make power

  #######################################################################################
  ###################### Regression Single Op ###########################################
  #######################################################################################
        ###Stand by

  #######################################################################################
  ###################### Demo Stencil ###################################################
  #######################################################################################
  demo-stencil-riscv:
    runs-on: ubuntu-24.04
    needs: [regression-test-riscv] 
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hybrogen
          POSTGRES_PASSWORD: hybrogen
          POSTGRES_DB: hybrogen
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U hybrogen"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      
    - name: Checkout repo
      uses: actions/Checkout@v4

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: riscv
        path: ./riscv/

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Restore database
      env:
        PGPASSWORD: hybrogen
      run: |
        until pg_isready -h localhost -p 5432 -U hybrogen; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        psql -h localhost -U hybrogen -d hybrogen < artifacts/hybrogen.sql

    - name: Stencil test on riscv
      env:
        BASH_ENV: ${{ github.workspace }}/riscv/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        python -m pip install psycopg2-binary
        chmod -R +x ./riscv/
        cd ./Demos/Stencil && make allRiscvQemu



  demo-stencil-aarch64:
    runs-on: ubuntu-24.04
    needs: [regression-test-aarch64] 
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hybrogen
          POSTGRES_PASSWORD: hybrogen
          POSTGRES_DB: hybrogen
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U hybrogen"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      
    - name: Checkout repo
      uses: actions/Checkout@v4

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: aarch64
        path: ./aarch64/

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        ls ./aarch64/
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Restore database
      env:
        PGPASSWORD: hybrogen
      run: |
        until pg_isready -h localhost -p 5432 -U hybrogen; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        psql -h localhost -U hybrogen -d hybrogen < artifacts/hybrogen.sql

    - name: Stencil test on aarch64
      env:
        BASH_ENV: ${{ github.workspace }}/aarch64/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        python -m pip install psycopg2-binary
        chmod -R +x ./aarch64/
        cd ./Demos/Stencil && make allAarch64Qemu

  demo-stencil-power:
    runs-on: ubuntu-24.04
    needs: [regression-test-power] 
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hybrogen
          POSTGRES_PASSWORD: hybrogen
          POSTGRES_DB: hybrogen
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U hybrogen"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      
    - name: Checkout repo
      uses: actions/Checkout@v4

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: power
        path: ./power/

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Restore database
      env:
        PGPASSWORD: hybrogen
      run: |
        until pg_isready -h localhost -p 5432 -U hybrogen; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        psql -h localhost -U hybrogen -d hybrogen < artifacts/hybrogen.sql

    - name: Stencil test on power
      env:
        BASH_ENV: ${{ github.workspace }}/power/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        python -m pip install psycopg2-binary
        chmod -R +x ./power/
        cd ./Demos/Stencil && make allPowerQemu

  #######################################################################################
  ###################### Demo Vector Matrix ###################################################
  #######################################################################################


  demo-vectorMatrix-aarch64:
    runs-on: ubuntu-24.04
    needs: [regression-test-aarch64] 
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hybrogen
          POSTGRES_PASSWORD: hybrogen
          POSTGRES_DB: hybrogen
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U hybrogen"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      
    - name: Checkout repo
      uses: actions/Checkout@v4

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: aarch64
        path: ./aarch64/

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Restore database
      env:
        PGPASSWORD: hybrogen
      run: |
        until pg_isready -h localhost -p 5432 -U hybrogen; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        psql -h localhost -U hybrogen -d hybrogen < artifacts/hybrogen.sql

    - name: Test Vector
      env:
        BASH_ENV: ${{ github.workspace }}/aarch64/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        python -m pip install psycopg2-binary
        chmod -R +x ./aarch64/
        cd ./Demos/VectorMatrix && make aarch64

  demo-vectorMatrix-riscv:
    runs-on: ubuntu-24.04
    needs: [regression-test-riscv] 
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hybrogen
          POSTGRES_PASSWORD: hybrogen
          POSTGRES_DB: hybrogen
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U hybrogen"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      
    - name: Checkout repo
      uses: actions/Checkout@v4

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: riscv
        path: ./riscv/

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Restore database
      env:
        PGPASSWORD: hybrogen
      run: |
        until pg_isready -h localhost -p 5432 -U hybrogen; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        psql -h localhost -U hybrogen -d hybrogen < artifacts/hybrogen.sql

        
    - name: Test Vector
      env:
        BASH_ENV: ${{ github.workspace }}/riscv/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        python -m pip install psycopg2-binary
        chmod -R +x ./riscv/
        cd ./Demos/VectorMatrix && make riscv


  demo-vectorMatrix-power:
    runs-on: ubuntu-24.04
    needs: [regression-test-power] 
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hybrogen
          POSTGRES_PASSWORD: hybrogen
          POSTGRES_DB: hybrogen
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U hybrogen"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      
    - name: Checkout repo
      uses: actions/Checkout@v4

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: power
        path: ./power/

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Restore database
      env:
        PGPASSWORD: hybrogen
      run: |
        until pg_isready -h localhost -p 5432 -U hybrogen; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        psql -h localhost -U hybrogen -d hybrogen < artifacts/hybrogen.sql

    - name: Test Vector
      env:
        BASH_ENV: ${{ github.workspace }}/power/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        python -m pip install psycopg2-binary
        chmod -R +x ./power/
        cd ./Demos/VectorMatrix && make power


  #######################################################################################
  ###################### Newton SquareRoot demo #########################################
  #######################################################################################

  demo-NewtonSquareRoot-aarch64:
    runs-on: ubuntu-24.04
    needs: [regression-test-aarch64] 
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hybrogen
          POSTGRES_PASSWORD: hybrogen
          POSTGRES_DB: hybrogen
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U hybrogen"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      
    - name: Checkout repo
      uses: actions/Checkout@v4

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: aarch64
        path: ./aarch64/

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Restore database
      env:
        PGPASSWORD: hybrogen
      run: |
        until pg_isready -h localhost -p 5432 -U hybrogen; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        psql -h localhost -U hybrogen -d hybrogen < artifacts/hybrogen.sql

    - name: Run Demo newtonSquareRoot
      env:
        BASH_ENV: ${{ github.workspace }}/aarch64/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        python -m pip install psycopg2-binary
        chmod -R +x ./aarch64/
        cd ./Demos/Newton-SquareRoot-VariablePrecision && make demo-aarch64


  demo-NewtonSquareRoot-riscv:
    runs-on: ubuntu-24.04
    needs: [regression-test-riscv] 
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hybrogen
          POSTGRES_PASSWORD: hybrogen
          POSTGRES_DB: hybrogen
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U hybrogen"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      
    - name: Checkout repo
      uses: actions/Checkout@v4

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: riscv
        path: ./riscv/

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Restore database
      env:
        PGPASSWORD: hybrogen
      run: |
        until pg_isready -h localhost -p 5432 -U hybrogen; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        psql -h localhost -U hybrogen -d hybrogen < artifacts/hybrogen.sql

    - name: Run Demo newtonSquareRoot
      env:
        BASH_ENV: ${{ github.workspace }}/riscv/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        python -m pip install psycopg2-binary
        chmod -R +x ./riscv/
        cd ./Demos/Newton-SquareRoot-VariablePrecision && make demo-riscv

  demo-NewtonSquareRoot-power:
    runs-on: ubuntu-24.04
    needs: [regression-test-power] 
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hybrogen
          POSTGRES_PASSWORD: hybrogen
          POSTGRES_DB: hybrogen
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U hybrogen"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      
    - name: Checkout repo
      uses: actions/Checkout@v4

    
    - name: Install ANTLR4 via apt
      run: |
        sudo apt update          
        sudo apt install -y antlr4      
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Get ANTLR version
      id: antlr-version
      run: |
        VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
        echo "ANTLR version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
  

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: power
        path: ./power/

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: hybrogen-artifacts
        path: ./artifacts

    - name: Move artifacts
      run: |
        rm -rf ./HybroGen ./HybroLang
        mv artifacts/generated/HybroGen ./
        mv artifacts/generated/HybroLang ./

    - name: Restore database
      env:
        PGPASSWORD: hybrogen
      run: |
        until pg_isready -h localhost -p 5432 -U hybrogen; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        psql -h localhost -U hybrogen -d hybrogen < artifacts/hybrogen.sql

    - name: Run Demo newtonSquareRoot
      env:
        BASH_ENV: ${{ github.workspace }}/power/.bashrc
      run: |
        sudo apt update
        sudo apt install -y python3-antlr4
        python -m pip install --upgrade pip
        python -m pip install antlr4-python3-runtime==${VERSION}
        python -m pip install psycopg2-binary
        chmod -R +x ./power/
        cd ./Demos/Newton-SquareRoot-VariablePrecision && make demo-power