name: HybroGen_CD_Workflow

#the CI call the CD for simplicity
on:
  workflow_call:
permissions: #Permission for safety
  contents: read

jobs:
  deploy:
    # if deploy fail the CI still noted as success
    continue-on-error: true
    runs-on: ubuntu-24.04 #Version that we ensure hybrogen work on

    #Strategy to launch multiple vm to connect wth ssh to all the MC and run the demo native
    strategy:
      matrix:
        include:
        #  - arch: riscv
        #    port: 60000
        # set in pause the riscv calculus and deployment because of segfault on riscv machine
          - arch: aarch64
            port: 65000

          - arch: aarch64
            port: 65001

          - arch: aarch64
            port: 65002

          - arch: aarch64
            port: 65003

    concurrency: # if 2 CD is launch at the same time this concurrency stategy garantee that the last CD will wait until first is finished
      group: shared-machines-${{ matrix.arch }}-${{ matrix.port }}
      cancel-in-progress: true # If true the first CD stop everything to let the second run
#To test concurrency
    steps:

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Install ANTLR4 via apt
        run: |
          sudo apt update          
          sudo apt install -y antlr4    
          VERSION=$(antlr4 2>/dev/null | grep 'ANTLR Parser Generator' | awk '{print $5}')
          sudo apt install -y python3-antlr4
          python -m pip install --upgrade pip
          python -m pip install antlr4-python3-runtime==${VERSION}

      - name: Download artifacts #Download artifacts generated during the CI
        run: |
          gh run download ${{ github.event.workflow_run.id }} -n hybrogen-artifacts -D artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move artifacts # Move artefact into current checkout
        run: |
          rm -rf ./HybroGen ./HybroLang
          mv artifacts/generated/HybroGen ./HybroGen
          mv artifacts/generated/HybroLang ./HybroLang
          rm -rf artifacts/
          ls

      - name: Build C file # Use Hybrolang.py to generate the good C file needed (ex. Stencil.aarch64.c)
        run: |
          cd ./Demos
          cd ./Stencil/ && make build  ARCH=${{  matrix.arch }}
          cd ../VectorMatrix && make build  ARCH=${{  matrix.arch }}
          cd ../Newton-SquareRoot-VariablePrecision && make build  ARCH=${{  matrix.arch }}


      - name: Clean machine #Delete last deploy directory to clean machine
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.SSH_ADDR_DEST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ matrix.port }}
          script: |
            rm -rf ~/FromCD
            mkdir ~/FromCD

      - name: Copy artifacts via SCP # copy repository into the MC
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345
        with:
          host: ${{ secrets.SSH_ADDR_DEST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ matrix.port }}
          source: "./Demos"
          target: "~/FromCD/"

      - name: Compile Program and generate Plot #Compile all C file using -O0 and -O3 flag and run it on the machine to generate (in the best case) a plot 
        timeout-minutes: 200
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        with:
          host: ${{ secrets.SSH_ADDR_DEST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ matrix.port }}
          command_timeout: 40m
          script: |
            cd ~/FromCD/Demos/Stencil/ && make allNative ARCH=${{ matrix.arch }} CFLAGS=-O0 CC=cc RUNNER="\"\"" LOG=${{ matrix.arch }}-native-O0.log            
            cd ~/FromCD/Demos/Stencil/ && make allNative ARCH=${{ matrix.arch }} CFLAGS=-O3 CC=cc RUNNER="\"\"" LOG=${{ matrix.arch }}-native-O3.log
            cd ~/FromCD/Demos/Stencil/Results/ && make all DATAFILES="../${{ matrix.arch }}-native-O0.log ../${{ matrix.arch }}-native-O3.log"
            cd ~/FromCD/Demos/VectorMatrix/ && 	make buildAndRun  ARCH=${{ matrix.arch}} CFLAGS=-O3 CC=cc RUNNER="\"\"" REPEAT=1000000 LOG=VectorMatrixLog-O3.log
            cd ~/FromCD/Demos/VectorMatrix/ && 	make buildAndRun  ARCH=${{ matrix.arch}} CFLAGS=-O0 CC=cc RUNNER="\"\"" REPEAT=1000000 LOG=VectorMatrixLog-O0.log
            cd ~/FromCD/Demos/VectorMatrix/ && python3 PlotResults.py VectorMatrixLog-O0.log VectorMatrixLog-O3.log 1000000
#Ajouter l'option de run NewtonSquareRoot en natif et faire un truc avec les logs#cd ~/FromCD/Demos/NewtonSquareRoot/ && make allNative ARCH=$ CC=cc RUNNER="" LOG=riscv-native-`date +"%Y-%m-%d-%H-%M-%S"`.log

            